### ISSUE TITLE
XLights Does Not Automatically Transition Audio Output

### ISSUE THREAD

**Issue by dragonzpneuma** [smeighan/xLights#1044]
I almost always do my sequencing with USB headphones on.  At times I want to unplug the headphones and let my wife hear and see what I've done so far.  When I unplug the headphones the program does not automatically revert to the computer speakers.  The audio output of XLights appears to lock up and I have to shut it down and restart to get it to revert to the PC speakers.  Same thing when I want to go back to the headphones.

**Comment by keithsw1111** [comment]
That is not something we can do anything about without a bunch of platform dependent code. Speak to your O/S vendor ... it should not require us to switch audio when a device disappears. It makes more sense for them to switch any audio ... or that is by design in which case our behaviour is consistent with that design.
