### ISSUE TITLE
Perspectives - Sequencer Tab

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#105]
After creating a new Perspective.  it is created, This works.

However after hitting the "-" minus (delete) key the selected perspective remains and is not deleted.

-Blu

**Comment by AzGilrock** [comment]
I think this is documented elsewhere but I'm not able to keep up anymore.  This is really part of a lot of functionality that was never coded yet.  Dave created a bunch of stuff that wasn't finished yet and now all the unfinished stuff is being documented as bugs.  I really didn't want this software being in Beta at this point because it makes it look like we forgot to do stuff that we hadn't had time to code yet.

**Comment by bluzervic** [comment]
Understood, you did not forget anything, this is a new feature :) And I do not look at it that way.
I just want to be helpful as I want you to have a rock solid finished product.
Feedback from the community is one of the best ways to QA a product.
Having written Software and QA'd it I hope I can provide enough information so you can pinpoint the affected area.

If you have a prefered area you want us to test, we can stick to that area.

JCMarksafb and I are basically on the same page and testing the same stuff.

-Blu

**Comment by AzGilrock** [comment]
Sorry its nothing your doing wrong.  I'm just getting beat down fighting bugs at work and in this program. :)

**Comment by stevegiron** [comment]
Marking this one as Trivial "Doesn't affecting sequencing". It's on the developer to-do list.
