### ISSUE TITLE
Enhancement Request: Layer Settings - Transformation

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1102]
Would it be possible to incorporate an option to rotate the buffer to a specific degree?  Trying to create two additional rings at 60 and 120 degrees.  Roto Zoom can't do it with the Z rotation.

<img width="951" alt="screen shot 2018-03-01 at 7 22 22 pm" src="https://user-images.githubusercontent.com/12144876/36878863-82f580d8-1d86-11e8-9ce5-6863423d3daf.png">

**Comment by keithsw1111** [comment]
Not really ... because that would not leave a rectangular buffer ... unless the buffer becomes larger and only partially populated with lights.

You could use rotozoom ... although I think it applies the rotation in the wrong order for what i suspect you are after.

Maybe instead I could allow you to specify the order in which rotozoom rotates things ... the six combinations of x, y, z

**Comment by kppankratz** [comment]
I'm trying to mimic this but can't rotate the effect properly using Roto Zoom.
![giphy](https://user-images.githubusercontent.com/12144876/36880449-5d44c0bc-1d8e-11e8-91ee-4695a86e218c.gif)

**Comment by keithsw1111** [comment]
Have you considered spirograph

**Comment by keithsw1111** [comment]
I am almost certain you could never ever achieve this with rotozoom

**Comment by kppankratz** [comment]
The best I can figure this out is using the Z & X Rotor-Zoom settings, duplicate effect on a second layer and rotate the buffer 90 degrees.  Spriograph is a no go.

<img width="432" alt="screen shot 2018-03-01 at 10 08 35 pm" src="https://user-images.githubusercontent.com/12144876/36883082-57a317da-1d9d-11e8-8097-4e4faf84ab8b.png">

**Comment by kppankratz** [comment]
Looks like your checkin works and allows the Z axis to pivot on the center to rotate.  Thank you.
