### ISSUE TITLE
Bug: Value Curves

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1117]
I believe the recent value curve fix broke something else.  When applying a value curve, ramp up/down 1 - 5 - 1, the spiral effect reverses direction instead of simply slowing down after reaching the peak value.

[Spiral VC.mov.zip](https://github.com/smeighan/xLights/files/1891954/Spiral.VC.mov.zip)

**Comment by keithsw1111** [comment]
Can you post the value curve settings and which property you were setting it on.

**Comment by keithsw1111** [comment]
Even package a sample sequence.

**Comment by kppankratz** [comment]
[Spiral VC Bug.zip](https://github.com/smeighan/xLights/files/1892200/Spiral.VC.Bug.zip)
<img width="485" alt="screen shot 2018-04-09 at 5 41 05 pm" src="https://user-images.githubusercontent.com/12144876/38526867-9d8ecf8e-3c1d-11e8-9d95-a89266c5bd29.png">

Using 2018.10

**Comment by keithsw1111** [comment]
This is going to sound really strange ... but it isnt actually broken ... the way the spirals effect works this is actually the right result.

The movement value effectively defined a position given by the equation p = movement * time.

So when you reduce the movement it should go backwards ... if you go too far. If you change the third parameter from 1 to 3 you will actually get the value you expect

I realise that isnt obvious ... but it is the right behaviour for the spirals effect algorithm.

The previous behaviour was actually incorrect.

**Comment by AzGilrock** [comment]
Kevin we will get it sorted out.  If Movement is using a decimal point type control then I believe it does have a bug because currently any value curve with a divisor is not returning the correct values vs when the curve is turned off.

**Comment by kppankratz** [comment]
Not a top priority by any means.  I just though it was odd that ramping down on a value curve would make the effect move backwards (right to left) even though the values were positive.  Does that mean if you were to do a negative ramp, the movement would be forwards (left to right).  Will have to try that one out.

**Comment by AzGilrock** [comment]
The movement thing I can understand cause the same thing happens with Marquee.  As you change the speed value you can increase the value and actually cause it to appear to be moving backwards.  The reason in that case is because if you have a segment size of 8 and you advance it forward by 7 it appears to be moving backwards by 1.

**Comment by keithsw1111** [comment]
Actually the reason it works the way it does is because movement is not used as an incremental change to the spiral ... instead what it does is ask where should the spiral be at this point if the movement had been this value since the start of the effect. So when you move the value back to zero it obviously has to be back where it started. As i said it is a side effect of the algorithm.

**Comment by keithsw1111** [comment]
Ok ... so we were both right ... it seems that effects that call the get double version of the function expect it pre-divided. Those that call the int version of the function expect it undivided.

I have reversed the int change and made the value curve dialog smart enough to handle both ... hopefully it is right now.
