### ISSUE TITLE
Twinkle not properly selecting random pixels from model

### ISSUE THREAD

**Issue by gayde2** [smeighan/xLights#1124]
When adding the twinkle effect, XLights is not properly selecting random elements in a model to turn on and off. Selecting "Re-Randomize after twinkle" doesn't help. It appears as if it selects a predefined subset of pixels in a model and randomly turns those on and off. This means some of the lights will never turn on and this makes the effect look bad. To fix this, XLights should turn on random lights at random times instead predefined lights at random times.

**Comment by AzGilrock** [comment]
I looked at the code.  It randomizes the duration and color if you re-randomize.  The pixels that light up are determined by the Steps parameter.  It does a modulo and when the pixel number divided by Step number equals 1 that pixel gets a random duration/color.  So if you set Steps to 1 then every pixel has a random chance of turning on but since every pixel will probably get some amount of duration it will look like they are all on.  So the problem with requests like this is it puts the burden on us who didn't even write the effect to think of a new algorithm.  Since you're telling us how it should work lets see the algorithm to go with it and by the way you can't mess up everyone's existing sequences when you make the change.

**Comment by stevegiron** [comment]
If you need more twinkle, add another layer with different settings. Works for me.

**Comment by keithsw1111** [comment]
Have you considered sparkles?

**Comment by AzGilrock** [comment]
I fixed the Twinkle effect so it now will cycle through all pixels randomly.  Old algorithm can still be selected if desired.
