### ISSUE TITLE
Allow speed changes on single strand effect with value curves

### ISSUE THREAD

**Issue by networx** [smeighan/xLights#1141]
Value curve on the speed setting for Single Strand does not work like you would expect.

I would like the chase on a single strand to start slow and end faster. Or start fast and end slower.

**Comment by keithsw1111** [comment]
If its there then it works as it should. Value curves change the setting ... they dont have some uber power to work the way you think they should.

**Comment by danvisibleman** [comment]
I do know what networx might be referring to. Just yesterday I used the VC on Cycles parameter of SS effect, and it kind've "spazzed out" during the transitionary part of the curve. I kept it cuz I liked the effect, but it did act a bit... wonky? 

Either way, I'm curious if there would be any issues or difficulties in adding a second digit of precision to the Cycles parameter, so I could set it to "3.14" instead of "3.1" or "3.2", for instance.

**Comment by networx** [comment]
Sorry. I shouldn't have opened this as a bug or said it doesn't work how "you" would expect. Just doesn't work how *I* expected.

I want just one cycle. But I want the speed of the chase to be slow at the beginning of the cycle and fast at the end of the cycle. Like the lights are accelerating as they proceed through a single cycle.

I see if I ramp up the number of cycles in the value curve they do increase in speed. But I only want one cycle to begin with. So it doesn't really give my desired result.

**Comment by AzGilrock** [comment]
Use a Morph...it's always a single cycle.

**Comment by networx** [comment]
Thanks. That was what I was looking for.
