### ISSUE TITLE
crash - export model to dump the csv file .. v30

### ISSUE THREAD

**Issue by darylerwin** [smeighan/xLights#1222]
I had completed copying spiral tree a number of times - no crash there - good.. then changed the universe, ok, then check sequence showed an error.
Non contiguous channels on controller ports
    ERR: Model 'Tree branches' and Model 'Spiral Tree-2R' are on controller IP '192.168.0.171' Output Connection 'WS2811:12' but there is a gap of -540 channels between them.

So I updated the output connection then went to export the model to see all the controller ports - crashed there.

[xLights_dbgrpt-4920-20180826T214103.zip](https://github.com/smeighan/xLights/files/2322124/xLights_dbgrpt-4920-20180826T214103.zip)

**Comment by keithsw1111** [comment]
This one example of a set of known crashes we have not resolved. The problem here is not specifically related to the actions described by actually a crash in the render code as a result of changes on the layout tab.

To minimise the chances of this happening we recommend you not change the layout and setup with a sequence open ... while this should not cause problems ... and most of the time it doesnt ... from time to time this occurs.

**Comment by darylerwin** [comment]
okay I was able to duplicate this one here .. might it be fixed already with the prior issue? I will upload a screengrab here too.. Seems very similar to what you said you fixed in .31

**Comment by darylerwin** [comment]
[exportmodel.zip](https://github.com/smeighan/xLights/files/2333067/exportmodel.zip)
[xLights_dbgrpt-13116-20180829T130716.zip](https://github.com/smeighan/xLights/files/2333069/xLights_dbgrpt-13116-20180829T130716.zip)

**Comment by keithsw1111** [comment]
I believe this is related to the other crash. Can you retest in .31 when it comes out in a day or so and close the issue if it is fixed.

**Comment by darylerwin** [comment]
Works fine in .31 .. ps sorry about the crappy screen grab - looks like I used the wrong settings.
