### ISSUE TITLE
Windows 7 access violation error on start

### ISSUE THREAD

**Issue by gpfransen** [smeighan/xLights#1230]
Hi,

I am trying to get xlights running on a Windows 7 machine.

Install all goes fine, but when opening xlights the banner shows and directly I get an access violation error.

Tried versions 2018.31(64/32)/2018.30(32)/2018.1(32)
 
Started from CMD with /w flag

Installed/ran with admin, tried compatibility mode.

I do not get a debug dialog to save any logs?
Is there a way I can generate these?

Only info I have so far is from windows access violation error;

2018.30(32)
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	xLights.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5b7d2663
  Fault Module Name:	xLights.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5b7d2663
  Exception Code:	c0000005
  Exception Offset:	0080f9ec
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	2703
  Additional Information 2:	27037d0c23985da9ada1af1c65ee6840
  Additional Information 3:	0dfd
  Additional Information 4:	0dfdd2401ee219b9aa729ed5d4a64e70

2018.1(32)
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	xLights.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5a4ea1c5
  Fault Module Name:	xLights.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5a4ea1c5
  Exception Code:	c0000005
  Exception Offset:	006fadfe
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	2703
  Additional Information 2:	27037d0c23985da9ada1af1c65ee6840
  Additional Information 3:	2fd8
  Additional Information 4:	2fd8b1695c898b51c4ffe76672e2cfc3

xSchedule does start but there does not seem to be an network XML in the xLights or its subfolders?
xRender (2018.01) starts without error.

Any help is greatly appreciated!

**Comment by keithsw1111** [comment]
Grab your log from c:\users\<you>\AppData\Roaming ... xlights_log4cpp.log I think is its name.

**Comment by AzGilrock** [comment]
So based on the debug print statements its crashing inside the MainSequencer constructor somewhere before the Waveform constructor.  It would appear the only other thing that could crash between there is the Timeline constructor but I don't see anything that could cause a crash.  This might need more debug statements to isolate.

**Comment by gpfransen** [comment]
Thanks for having a look at the files!

I have attached the 9 more dumps, I hope this helps!

[xLights.exe.dumps9x.zip](https://github.com/smeighan/xLights/files/2350052/xLights.exe.dumps9x.zip)

**Comment by AzGilrock** [comment]
I don't think those dump files are useful plus its just gonna keep crashing in the same spot so until we give you a new version to try there's not much more you can do unless you can try another computer.

**Comment by keithsw1111** [comment]
In my experience the best way to solve this is to find a time when you can join us in a zoom session and we just create versions until we get some logging that tells us exactly what the problem is. This is really only practical when we have a block of time and are online together. So things like timezone and availability become important.

**Comment by gpfransen** [comment]
Thanks for the replies, better support than most commercial products!

I did have some other software packages that needed windows so went for my most comfortable option W7 on this machine but will change this to W10 and I assume that this should be resolved.

I will report back as soon this has been done.
Many thanks!

**Comment by keithsw1111** [comment]
There is no reason to believe a windows upgrade would help.

**Comment by keithsw1111** [comment]
When .32 comes out I have added some logging. If it loads correctly it should look like this

2018-09-06 12:10:38,924 2824 log_base [DEBUG] CreateSequencer: Creating Panels.
2018-09-06 12:10:38,924 2824 log_base [DEBUG]         Sequencer grid.
2018-09-06 12:10:38,927 2824 log_base [DEBUG]                 Creating main sequencer <YOURS CRASHES AFTER HERE>
2018-09-06 12:10:38,942 2824 log_base [DEBUG]                 Creating Timeline
2018-09-06 12:10:38,985 2824 log_base [DEBUG]                     Creating GL Canvas for WaveForm <YOURS CRASHES BEFORE HERE>
2018-09-06 12:10:38,986 2824 log_base [DEBUG]                 Creating Waveform
2018-09-06 12:10:38,988 2824 log_base [DEBUG]                 Creating RowHeading
2018-09-06 12:10:39,032 2824 log_base [DEBUG]                     Creating GL Canvas for EffectGrid

Also can i suggest you upload your video drivers to the latest from the manufacturer rather than from Microsoft.

**Comment by keithsw1111** [comment]
Can you try again with .32 or .33 and post the log.

**Comment by keithsw1111** [comment]
Bueller?
