### ISSUE TITLE
Adding a effect on a single model causing artifacts with effects on the whole house group. 

### ISSUE THREAD

**Issue by madsci1016** [smeighan/xLights#1253]
Video of bug: https://www.youtube.com/watch?v=dJBdXnPE8bg

Basically I have a strobe on a whole house group. As I add effects to individual models, the strobe gets more and more dense until I click render-all. 

Best guess is renders are getting kicked off on the whole house group effects by adding effects to models but the fseq data is not cleared out first, so strobe is randomly adding more and more strobes each render kickoff. 

I can provide package sequences to Devs on request, did not want to post it publicly. This is Bill Porter.

**Comment by madsci1016** [comment]
To add: I've verified I'm in Render Mode: Erase and layer blending does not have canvas mode checked.

**Comment by keithsw1111** [comment]
You need to send us the sequence and your logs.

**Comment by keithsw1111** [comment]
Bill sent me a super simple sequence which shows the issue.
1. A strobe effect on whole house model with 300 strobes ... this isnt many because of model size.
2. A lightning effect on a model underneath it in the master view.

Then by resizing the lightning effect (click size drop) many times the strobe density progressively increases.

Rendering all or even just clicking on the strobe effect re-renders and resets the strobe count.

Interestingly changing the blend between models to off stops the problem ... so it seems to be a render tree issue.

**Comment by keithsw1111** [comment]
Looking into this I dont see how model blend ever renders correctly when you click on a model. It just renders the clicked on effect ... when it really needs to render any prior models with overlapping ranges ... and of course if you do that you then need to rerender all the models contained in those groups if they appear under the group ... its a bloody nightmare ... you almost just need to render the effect range.

**Comment by dkulp** [comment]
Can you send me the sequence? It is supposed to render all the models it depends on (and those that it depend on) but restrict the channel range for what is rendered to the channels used in that model.
