### ISSUE TITLE
ENHANCEMENT: Effect 'snap to timing mark'

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#132]
OSX 4.0.10
Would it be possible to have the effects use a 'snap to timing mark' much like you can snap two timing marks together as one. Then if you move timing marks the effects move with them. 

I attempted to use the 'fit to time' selection thinking it would snap to the timing mark that the effect was placed into it and it did not.

Could this be a global setting that all effects would use as you place them in, and you can turn it off so you can change individual ones, or add ones that are snapped enabled?

Those, however; that were placed with the snap to timing mark move whenever the timing marks are moved as well. 

The effects that were not configured with snap to, remain static with their original timings as is.

**Comment by jcmarksafb** [comment]
I wouldn't mind a snap to grid function as long as it is an option, on or off.
 


     On Wednesday, April 1, 2015 10:59 AM, LightsOnHudson <notifications@github.com> wrote:
   

 OSX 4.0.10
Would it be possible to have the effects use a 'snap to timing mark' much like you can snap two timing marks together as one. Then if you move timing marks the effects move with them. I attempted to use the 'fit to time' selection thinking it would snap to the timing mark that the effect was placed into it and it did not.Could this be a global setting that all effects would use as you place them in, and you can turn it off so you can change individual ones, or add ones that are snapped enabled?Those, however; that were placed with the snap to timing mark move whenever the timing marks are moved as well. The effects that were not configured with snap to, remain static with their original timings as is.—

**Comment by AzGilrock** [comment]
Effect end markers already snap to grid.  Like if you select 50ms timing marks you can't locate one at 25ms.  For timing marks the problem is you can have unlimited numbers of timing layers and there is no association between an effect and the timing layers to know which timing mark you would like it to attach to.  We've given the the capability to drag a box around all the effect markers in a column and move them all as a single unit.  That accomplishes the same thing.

**Comment by LightsOnHudson** [comment]
In the timing layers, you have the bubble to enable that timing layer or not. And what I see when I turn on that bubble of the timing track are the timing marks that are created.

I'm using a starting point with an empty timing track and creating timing marks in a new sequence.

I understand they are snapping to a grid, but the ability to snap to the timing mark that they are inside of (start and end) would allow all effects to move at once when timing marks are zoomed in and fine tuned according to the music/beat.. etc.

**Comment by smeighan** [comment]
I am not understanding the question. You can think of xlights as always having grid timing. 25,50, 100ms. you cannot put a timing mark except where the grid exists. We store effects in a fixed timing grid for performance (I have tested xlights to 200K channels). If you have 50 ms frame timing then your effects can ONLY be 0.0, 0.05, 0.1, 0.150 .etc. That is how the data is stored internally.

LOR and others allowed variable timing marks, 0.13, 0.372. We will always truncate a timing that we import to the nearest frame timing. In this example to 0.15 and to 0.350 is using 50ms frame timing.

This idea of snapping to a grid is confusing to me since xlights and nutcracker have always had fixed frame timing for years. 

So, import timing from audacity but the timing will be snapped to the nearest frame timing. 

Also, you do NOT need to create a timing track for the grid (Settings, Sequence Settings,Timings, Fixed Timing Interval, 25/50/100). Put in the timings you will use (mostly 2 to 5 seconds is typical).
This is because the internal timing grid is always present.

Why use 25ms? It makes smoother fades. It allows better sync to Papagayo singing faces
Why use 50ms? (This is what I use). Your sequence files will be twice as small. I dont notice the difference in the fades. If I get Papagayo, I will change to 25ms.

**Comment by AzGilrock** [comment]
It sounded to me like he wanted an option where all the effects that are dropped between timing marks become associated with that timing mark and move when the timing mark is moved.  That's why I said if you want them to move as a group you can always select them as a group and hold down ctrl or shift to move them.  So the capability to accomplish what you want is there.  I don't think it's worth it having an option to associate every effect to timing marks.  Too many features in the code are going to bloat it and slow things down.

**Comment by LightsOnHudson** [comment]
Yes, I understand the confusion Sean. The Snap to grid when placing effects I should have been a little more clear.

Yes, the effects initially do 'snap' to the start and the end of the Timing marks. But let say you adjust it, playing around with it, and you make it shorter in duration, than your current timing span. Now you want to put it back to the true start and end time that it was originally inserted with.

You can slide the front or the end of the effect and visually try to line it up with the timing marks but it may be a bit 'off'. 

So, in this case, like you demonstrated in the demo, you can drag a timing mark close to another one and it will link together, thus making one timing mark. So if you are working with Effects, and get the effect start or end near/on top of and stop - it can attach to the timing mark and move with the timing mark. The effect will grow or shrink in duration along with the moving of the timing mark start or end point.
![screen shot 2015-04-01 at 3 53 56 pm](https://cloud.githubusercontent.com/assets/10136122/6953609/b01aa7ec-d887-11e4-8356-48e3004d4ddc.png)


So I pulled up the effect timing options and clicked 'fit to time' and the effect did not 're-snap' back to the timing marks as I visually would have thought it would have done.

I also attempted using CTRL , The Apple Key, the Shift key to select different effects to move them or timing marks, and they did not move together (they didn't highlight/select together either).


See the attachment.

**Comment by LightsOnHudson** [comment]
![screen shot 2015-04-01 at 3 53 56 pm](https://cloud.githubusercontent.com/assets/10136122/6953617/be7b050c-d887-11e4-920b-f405848f1a3e.png)

**Comment by PhilHilton** [comment]
I would very much like to see this. Currently timings are only useful when an effect is first applied. When re-sizing/dragging an effect around it ignores the timing grid. The timings would be useful here if the drag handle was "magnetic" and sticky with the timing marks in the currently active grid (and even more useful if it was sticky to other effects above/below it the drag handle, as more often than not I'm trying to align them together anyway).  Would be toggle-able, and turned off contextually by holding a modifier key while dragging.

Every used adobe premiere? The timeline there has the exact behavior I'd like to see here.

When working out intricate music riffs manually (and you aren't using the piano tool) is where this would be most helpful (and where I've found the absence of it to be the most frustrating the past couple days)

**Comment by PhilHilton** [comment]
Demo of Adobe Premiere snapping (skip to 1:44): 
https://youtu.be/R2ZVVAjcvOM?t=104

**Comment by idleup** [comment]
I also would like to see a behavior where the timing mark is "magnetic" when dragging and end of an effect near it.

**Comment by stevegiron** [comment]
This is now functional with Control+Shift + left  or right arrow

**Comment by PhilHilton** [comment]
This is cool, useful, and certainly appreciated (sincerely) but that's not quite the same thing. 

That moves the entire effect, and only the start of it snaps to timing marks (the tail end is still un-snappable, for lack of a better word). 

It's useful, no doubt, but not quite there.

Really wish I had more time to work on this.

**Comment by keithsw1111** [comment]
Then you are using it wrong because it absolutely does stretch the effect.

**Comment by PhilHilton** [comment]
It's possible I'm using an older implementation of this I guess. I'll check it out again tomorrow, making sure I have the latest and post vid if still seeing the other behavior.

**Comment by PhilHilton** [comment]
...and it's possible that it's command-shift on a Mac rather than control... Got it.

Would still rather have toggle-able drag behavior but this will do the job. Many thanks.

**Comment by AzGilrock** [comment]
I was planning on doing this at some point.  The spirit of this issue was not fixed.  It should be a snap to timing mark as you are dragging it.

**Comment by AzGilrock** [comment]
Got this implemented and it seems to work well.  Might need to adjust the snap zone.  For now its 10 pixels on either side of a timing mark.
