### ISSUE TITLE
Keybinding file nearly empty on 2018.56

### ISSUE THREAD

**Issue by TxBillbr** [smeighan/xLights#1375]
only F9-F11, End, Pause, Home, Space,. ,n, o, s, A, a and ESC are mapped. See  attached file. 
[xlights_keybindings.zip](https://github.com/smeighan/xLights/files/2706084/xlights_keybindings.zip)

Expecting standard sequencing keys (t, etc)

**Comment by AzGilrock** [comment]
Just delete it and startup xLights it should recreate a good one.

**Comment by TxBillbr** [comment]
Does this mean that one is not expected to add/change the keybindings?

**Comment by TxBillbr** [comment]
ok. Thanks for the follow-up.  I may write a small tool to set  my custom key mapping.

**Comment by keithsw1111** [comment]
There is a bug in there somewhere that I am trying to find that corrupts it. Once fixed we should be all good.

**Comment by TxBillbr** [comment]
Keith, It is not high priority. I just wanted to report its existence. It is more of a nuisance bug.

**Comment by jeffla** [comment]
FYI, I got an alert asking if I wanted to save my keybindings file when I switched show directories last night. I said "no." Not sure if it's related, but adding info.

**Comment by TxBillbr** [comment]
Jeff, are you running released or an unreleased version?

**Comment by jeffla** [comment]
2018.55

**Comment by TxBillbr** [comment]
ok. I've been running 2018.56 and haven't seen that. Since I imported a bunch of other sequences this year, I have changed show directories a lot.

**Comment by jeffla** [comment]
Admittedly, it was an older show directory, but I hadn't made any changes so thought it was odd especially since my main keybindings file got corrupted a while back (timing "T" wouldn't work after an upgrade and it had no association in the file). Easily fixable, but something I noticed. Can't remember the version I noticed it on so not very helpful. OK, I'll just be quiet now. :)
