### ISSUE TITLE
Sequence Duration - Stops prematurely - Animation converted to Musical

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#138]
OSX 4.0.10
These are the steps that I used to see this issue.

Original Sequence as 35 second Animation sequence.

Configured a few Timing marks.

The sequence played from start to end of 35 seconds.

In the Sequence settings, converted from Animation to Musical Sequence. The music file added to the Sequence was only 25 seconds long, the sequence now only plays from the beginning of the Sequence to the end of the music file.

The Sequence duration states 25.xxx seconds.

However; updating the sequence duration to the original 35 seconds does not allow the sequence to play to the end. See attached screenshot.

![screen shot 2015-04-01 at 4 25 18 pm](https://cloud.githubusercontent.com/assets/10136122/6954191/493a9302-d88c-11e4-817f-965616165021.png)

**Comment by AzGilrock** [comment]
Yeah the problem is we don't have the ToDo list and/or the known shortcoming well documented.  I added that sequence duration with the intent to be able to do exactly what you are trying but internally it hasn't been connected to be used everywhere.  Most of the internal logic still uses the media length whereas I wanted everyone to call for the sequence duration from the xml file object.  So long story short yep it's an issue we knew about but didn't document.
