### ISSUE TITLE
Marquee issue with buffer window settings

### ISSUE THREAD

**Issue by TKW1969** [smeighan/xLights#1421]
When creating Marquee affect on matrix if you change to middle or right thirds its not correct.
Same as when you edit the left or bottom buffer size. I have video and here is the link to it.

https://vimeo.com/user39012174/review/311563485/badef64f18

**Comment by AzGilrock** [comment]
That link didn't work for me.

**Comment by patdelaney** [comment]
ME either :-)

**Comment by AzGilrock** [comment]
Hmm...maybe I didn't understand how those buffers work.  I thought it created a new buffer and fed it to the effect but the way it's reacting it appears to be scaling the result of the effect rendering which would explain why you get a double line because of the resampling.  If that's the case its not anything inside the effect code and not sure it can be fixed.

**Comment by keithsw1111** [comment]
Looks like a rounding issue to me ... and not necessarily an issue ... but maybe.

**Comment by keithsw1111** [comment]
Yep ... a rounding issue ... and i am not sure it is fixable ... I have tried but getting odd behaviour.

**Comment by AzGilrock** [comment]
Yeah but where is the rounding issue?  Is it inside the effect render or is it a buffer resizing thing?  I still don't know how that buffer size change code works on whether it is pre or post effect render.  I just didn't think it was possible to be a problem inside the effect because the "thickness" is just a simple for loop so it wouldn't have rounding errors.

**Comment by keithsw1111** [comment]
In ComputeSubbuffer in PixelBuffer.cpp.

It does a std::ceil on the buffer size which causes the issue (although i dont think the right answer is to remove this because of the impact it would have) ... and my attempts to fix it for particular use cases caused other issues ... specifically the marquee to double the left hand edge ... so there is something going on i am not seeing.

**Comment by AzGilrock** [comment]
I still have no idea if the buffer gets resized pre-render or post-render.

**Comment by keithsw1111** [comment]
It is pre-render ... it has to be so the effect knows how big the buffer is. I am just missing something.

**Comment by AzGilrock** [comment]
Well then I'm missing something also.  Even if the width and height calculated off by 1 I don't see how the effect draws a double line on one edge unless I didn't see the video correctly.  The Marquee code doesn't look like it could draw 2 columns for one edge.

**Comment by dkulp** [comment]
unless the "wrap" flag to SetPixel is also behaving wrong for a sub buffer case so the off-by-one is causing marquee to add a pixel off the edge of the real buffer and this is causing that pixel to wrap back somehow.  Strange.

**Comment by AzGilrock** [comment]
Even if it wrapped with Thickness set to 1 it only goes through the "for" loop once so it should only be possible to draw 4 lines.  I'm not on my home computer so no way to verify anything.

**Comment by dkulp** [comment]
Got this fixed... It's a "subtraction" issue when it crosses 0.   If "x1" is 10.2, X pos of "11" minus that is 0, but so is X pos of 10.  Thus, we get two colums/rows of 0.  I'm rounding the offsets to an int prior to the subtraction so the values should be more exact.
