### ISSUE TITLE
Poly Line causes crash in 2019.6

### ISSUE THREAD

**Issue by DevDavidW** [smeighan/xLights#1436]
I'm working on upgrading to the latest version. I started with renaming my original xLights folder, then copied over just the 3 xlights files (keys, networks, and effects). Every time I started xLights it crashed. So I spent some time cutting out components within the effects file until I narrowed down the issue. It comes down to one (my only) poly line model. If I remove only that model from my layout, it opens fine. So I swapped it around and made it the only model and confirmed it still causes a crash. I remove that model, then create a new Poly Line, and it works. So I'm not sure what is wrong with my old poly line. I reinstalled 2018.59 to test and this same effects file opens fine and displays the Poly Line as it should. I hope this helps.
[xlights_PolyLine_issue.zip](https://github.com/smeighan/xLights/files/2799199/xlights_PolyLine_issue.zip)

**Comment by DevDavidW** [comment]
Great! Glad you were able to figure it out. Yes according to my backups, that poly line goes back to at least 2016 (time to purge those again). As for older versions of xLights, I keep the installers for a few versions back but I always just replace the currently installed version. However, I don't always go to the latest right away. I'll watch the forum and wait for feedback and if I don't see any complaints or major issues then I'll upgrade. So far I've only had to go back to an older version once. I would think having multiple versions installed would get confusing. And with only two show directories (Christmas and Halloween) if any changes occur in a newer version that isn't backwards compatible, I'd get errors trying to go back anyway. I do appreciate knowing there is code that detects older versions of files and "upgrades" them! Thanks for following up!

**Comment by AzGilrock** [comment]
Having multiple versions is not confusing at all.  The icon on the desktop always opens the latest version I've installed.  If I want to run an older version I just navigate to Program Files and dive into whatever folder I want and double-click xLights.exe.  The only purpose for the older versions is when Joe Blow says function XYZ broke and he doesn't tell us what version he was using before he upgraded I have to do the work I wish Joe would have done and try a bunch of older versions to try to find where maybe it used to work and now it doesn't.  I'm never saving anything when I run in the older version so it never breaks my files and if there is truly a compatibility issue I just open a new blank show folder because I'm really just testing whether some feature got broken.
