### ISSUE TITLE
Minor copy and paste issue

### ISSUE THREAD

**Issue by ebuechner** [smeighan/xLights#1486]
I'm on 2019.13 and I've noticed that copy and paste Buy cell has a minor bug that skews things slightly. 

https://youtu.be/pLcTXL4FPcU

**Comment by AzGilrock** [comment]
That's because we have to calculate a percentage for how much of the cell is taken up by the effect and we save that as an integer so if it was 50.4% it gets saved as 50%.  So when we convert back from percentage to time it could shift a smidge.   Only way to fix would be to store as floating point but that would be a huge impact because it would invalidate all the existing data that relies on paste like keyboard shortcuts and effect presets which are inserted using paste.  It would require a new copy/paste format and then the old format would need to be deprecated (again) and then the code would need to detect which of the 3 paste versions you are using for all those operations.  "Paste by Cell" was designed to be pasting into cells that did not match the original size so it only needed to get you close to the percentage.  "Paste by Time" was for exact matching.  We can see if the others think we should implement a paste format change.  It would impact the size of the copy/paste data structure so if you were copying a big block it means a lot more memory usage.

**Comment by ebuechner** [comment]
That makes sense.
I didn't see it as a big deal at all, I can select Pace by time.
When I ran across it I thought I would document it just in case it was something that needed to be addressed.
Cut and paste was the only thing I ever thought needed to be added but even that would only save a couple of steps. 

Should we close this one?
