### ISSUE TITLE
3D handles

### ISSUE THREAD

**Issue by skulltronix** [smeighan/xLights#1508]
User interface suggestion for future consideration:
The handles that are used to manipulate a model in 3D space are often too small to click on. (In my experience)
I suggest the handles be moved into a corner of the screen away from the model itself and always be the same size. In addition, place the text entry areas for location and rotation there with the handles so that access is quick and always in view. 
Thank you!

**Comment by AzGilrock** [comment]
Yeah the opposite is what always bothers me.  I don't like the handles getting really big when I zoom in.  If they are too small to click you probably need to zoom in.  I tried to make the handles always be the same size but I failed and give up.  The idea to leave them down in a corner doesn't sound good to me because lets say you put it in the left corner and then want to move something to the left your cursor is immediately off the page.
