### ISSUE TITLE
XLights Color GUI's not showing up on Ubuntu 19.04 when using latest AppImage xLights-2019.34.glibc2.17-x86_64

### ISSUE THREAD

**Issue by foss365** [smeighan/xLights#1605]
XLights Color GUI's not showing up on Ubuntu 19.04 when using latest AppImage xLights-2019.34.glibc2.17-x86_64

**Comment by foss365** [comment]
![xlights](https://user-images.githubusercontent.com/16073383/61178850-6cd76180-a5bc-11e9-8668-d8273959e02e.png)

**Comment by foss365** [comment]
Version Version: 2019.16 64bit from the PPA is fine ( as seen below ) but not very close to the latest release.

**Comment by foss365** [comment]
![xlights](https://user-images.githubusercontent.com/16073383/61178885-f850f280-a5bc-11e9-9573-062c506eaff2.png)

**Comment by foss365** [comment]
I'm going to try and push some Linux training on XLights and would like to use a version closer to release. I can try and compile it but end users won't want to do that.

**Comment by keithsw1111** [comment]
Not sure ... Chris or someone else familiar with Linux will need to look at this.
You could help but isolating in which release it broke.

**Comment by foss365** [comment]
Okay I'll look for the previous appimages.

**Comment by foss365** [comment]
So it looks like it's specifically related to the appimage formats themselves. When I install XLights version 16 from the PPA, everything is fine. If I run the version 16 appimage the color selectors are missing.

**Comment by foss365** [comment]
So I compiled (using the Makefile ) the latest version (34) and ran into some issues. After compiling and installing xlights per the instructions, the program would not start. After reading the secondary way of compiling I read that you needed libwxsmithlib0 installed for Codeblock compiling. After installing libwxsmithlib0 the xlights program started and worked fine. Color selectors were available in the compiled version.

The appimage version (34) still does not have the color selectors. This leads me to think it's an issue with an include in the appimage.

**Comment by tgodfrey73** [comment]
For what it's worth - I haven't noticed any issues with the color window running any of the appImage's on Ubuntu 18.04.3 LTS including 2019.34. Currently running 2019.38.

**Comment by cjd** [comment]
I've been doing some work today on changing how the appimage is made - would you be willing to try a test version for me?

**Comment by cjd** [comment]
There are two versions - one for GTK2 and one for GTK3
They can be grabbed from
https://www.adebenham.com/wp-content/uploads/xlights/test/xLights-2019.40-x86_64.AppImage-gtk2
https://www.adebenham.com/wp-content/uploads/xlights/test/xLights-2019.40-x86_64.AppImage-gtk3

If people could test/give feedback on how they run that would be great

**Comment by tgodfrey73** [comment]
I'll give them a try tomorrow evening and then next couple of nights. Working on Halloween sequences so I've been fairly active lately.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Chris Debenham <notifications@github.com> Date: 8/13/19  11:03 PM  (GMT-06:00) To: smeighan/xLights <xLights@noreply.github.com> Cc: tgodfrey73 <tgodfrey@argcommunications.net>, Comment <comment@noreply.github.com> Subject: Re: [smeighan/xLights] XLights Color GUI's not showing up on Ubuntu 19.04 when using latest AppImage xLights-2019.34.glibc2.17-x86_64 (#1605) There are two versions - one for GTK2 and one for GTK3
They can be grabbed from
https://www.adebenham.com/wp-content/uploads/xlights/test/xLights-2019.40-x86_64.AppImage-gtk2
https://www.adebenham.com/wp-content/uploads/xlights/test/xLights-2019.40-x86_64.AppImage-gtk3
If people could test/give feedback on how they run that would be great

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/smeighan/xLights/issues/1605?email_source=notifications\u0026email_token=ABLF7RR5DP5QI6BL5SEIQD3QEN725A5CNFSM4IDHCGXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4HUEAA#issuecomment-521093632",
"url": "https://github.com/smeighan/xLights/issues/1605?email_source=notifications\u0026email_token=ABLF7RR5DP5QI6BL5SEIQD3QEN725A5CNFSM4IDHCGXKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4HUEAA#issuecomment-521093632",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tgodfrey73** [comment]
noticed the scroll bar arrows missing from the gtk3 version. Haven't had any crashes. Had some funky issues with the sequencer window when applying a video and a shader effect in the same time box but that didn't seem specific to these builds as it happened on the other builds I tried. 
![scrollBarArrowsMissingGtk3](https://user-images.githubusercontent.com/5660614/63137539-4d0cd200-bf9c-11e9-9ea3-12738caf6f51.png)

**Comment by cjd** [comment]
The missing scrollbar arrows are due to the gtk3 theme rather than xlights itself.
You can still drag the bar (the darker gary bit in your screenshot) left/right to scroll around

**Comment by tgodfrey73** [comment]
Yup, can still drag or use ctrl + mouse wheel. --- Used the GTK3 version since you mentioned it. Just finished a sequence on it. Can't say I noticed any out of the ordinary problems with it. Is there something specific your concerned about or questioning?

**Comment by cjd** [comment]
There were previously some problems with icons/buttons not being visible/usable - and coincidentally a problem with the colour dialog.
@foss365 - have you had a chance to try the newer appimage test versions?
If so - did either help?

**Comment by foss365** [comment]
Yes, GTK2 version now has the color wheel. The GTK3 version won't run on my Ubuntu Studio 19.4 but I'm assuming that's because my OS doesn't support it or I need to download GTK3 libs.

I'll do more extensive review on the new appimage very soon. Thank you for your work on this, I think Linux people will appreciate the program. I feel it's mostly Windows users but I bet it's because most Linux users don't know about it. I'll be trying to change that :)

**Comment by foss365** [comment]
![xlights](https://user-images.githubusercontent.com/16073383/63654806-d8c4f200-c744-11e9-86e4-09928853b345.png)

**Comment by foss365** [comment]
If you ever need/want a tester give me a shout out. If you do Facebook you can hit me up with an IM if you want faster response time.

https://www.facebook.com/tommorleyoswego

**Comment by foss365** [comment]
This is the error I get when trying to run the GTK3 version

'/home/tom/Apps/XLights/xLights-2019.40-x86_64.AppImage-gtk3'
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this
./src/common/stdpbase.cpp(62): assert ""traits"" failed in Get(): create wxApp before calling this

(xLights-2019.40-x86_64.AppImage-gtk3:9379): Gtk-WARNING **: 19:59:30.747: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:/build/gtk+3.0-NmdvYo/gtk+3.0-3.22.11/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
Aborted (core dumped)

**Comment by cjd** [comment]
I just installed a VM with UbuntuStudio 19.04 and tried the gtk3 appimage.
I loaded/ran fine from there.
Can you grab the /tmp/xLights_l4cpp.log file from after it has crashed?
Also - try moving aside ~/.xLights-2019* (this is where the config sits) to see if it is a odd config issue.

Thanks

**Comment by cjd** [comment]
Closing off old linux issues - reopen if still occurring
