### ISSUE TITLE
Enhancement Request - Expand/Contract Whole house Groups

### ISSUE THREAD

**Issue by Xenialights** [smeighan/xLights#163]
Once a group is created with a corresponding whole house model, have a way (+) to expand or contract the whole house model so that the corresponding models open or close as needed to make it easier to work on a sequence.

**Comment by AzGilrock** [comment]
Currently the whole house models are not associated in any way with the models you used to create it.  I had suggested that earlier and the problem turned out to be that you can create several whole house models from the same set of models with the models moved around the screen.  I wanted to have every model groups automatically be a sequenceable display element but the flexibility in how you can use WHM's causes an issue.

**Comment by Xenialights** [comment]
Thanks Gil,  It would be a nice convenience but not nearly  as critical to functionality as dropping an effect on a whole house group like you are showing on your tutorial.

**Comment by stevegiron** [comment]
Can we close this issue request?

**Comment by AzGilrock** [comment]
We now have the ability to expand/contract model groups.
