### ISSUE TITLE
Metronome Timings not making timing marks

### ISSUE THREAD

**Issue by nato595** [smeighan/xLights#1641]
**Describe the bug**
When adding a new timing track, and choosing Metronome with a custom value, the timing marks are not created.  50 and 100 work, but no other values work - even when a multiple of the base as the manual says is needed.

**To Reproduce**
1. Create a new Animation Sequence.
2. Chose 20fps (50ms).
3. Quick Start.
4. Right-click New Timing and chose Add Timing Track.
5. Select Metronome and click OK
6. Type 500 in the milliseconds field and click OK.
7. See that no timing marks are present.
8. Notice that if you chose 50ms or 100ms rather than Metronome in steps 5/6 that it does work as expected.

**Expected behavior**
I would expect a timing marks every half second for a value of 500ms, or every second for a value of 1000ms.

**Screenshots**
Attached screenshot showing 50ms and 100ms have timing marks, but both Metronome tracks do not.
![Capture](https://user-images.githubusercontent.com/53949935/62797712-30026b80-ba91-11e9-923f-e4d0c701b4c0.PNG)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.38 64-bit

**Additional context**
n/a

**Attachments**
n/a

**Comment by keithsw1111** [comment]
This was fixed in .39. Please only report bugs in the latest version.

Sent from my iPhone

On 10 Aug 2019, at 3:34 am, nato595 <notifications@github.com<mailto:notifications@github.com>> wrote:


Describe the bug
When adding a new timing track, and choosing Metronome with a custom value, the timing marks are not created. 50 and 100 work, but no other values work - even when a multiple of the base as the manual says is needed.

To Reproduce

  1.  Create a new Animation Sequence.
  2.  Chose 20fps (50ms).
  3.  Quick Start.
  4.  Right-click New Timing and chose Add Timing Track.
  5.  Select Metronome and click OK
  6.  Type 500 in the milliseconds field and click OK.
  7.  See that no timing marks are present.
  8.  Notice that if you chose 50ms or 100ms rather than Metronome in steps 5/6 that it does work as expected.

Expected behavior
I would expect a timing marks every half second for a value of 500ms, or every second for a value of 1000ms.

Screenshots
Attached screenshot showing 50ms and 100ms have timing marks, but both Metronome tracks do not.
[Capture]<https://user-images.githubusercontent.com/53949935/62797712-30026b80-ba91-11e9-923f-e4d0c701b4c0.PNG>

Versions (please complete the following information):

  *   OS: Windows 10
  *   xLights version 2019.38 64-bit

Additional context
n/a

Attachments
n/a
