### ISSUE TITLE
Rotated matrix isn't displayed correctly in House Preview

### ISSUE THREAD

**Issue by tmeyermn** [smeighan/xLights#1719]
**Describe the bug**
If you rotate a matrix 180 degrees around Y the image isn't reversed on the House Preview but is on the Model Preview.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1.  Create a default matrix
2.  Rotate it 180 around y
3.  Drop some text on it
4.  Text is not reversed on the House Preview but it is in the Model Preview

**Expected behavior**
The text or any other effects/video should be reversed when looking at it in the House Preview as well as the Model Preview.

**Screenshots**
![image](https://user-images.githubusercontent.com/43391347/65195069-3ea25200-da43-11e9-9c3c-c165b26a4701.png)

**Versions (please complete the following information):**
 - OS: Windows 10 x64 Home
 - xLights version 2019.50

**Comment by AzGilrock** [comment]
I see the opposite when I do the same test.  It's reversed on the House Preview but not the model preview which is actually correct behavior because we do not rotate the model in the Model Preview window.

**Comment by tmeyermn** [comment]
Thanks Gil, I see that as well when I recreated it but then I think I found what was messing me up.  The second I click on the grid and try to tilt it rotates 180 degrees....
https://youtu.be/pmMqXX_uAtw

**Comment by tmeyermn** [comment]
Also, I'm seeing that the preview reverse if you change the starting location from Bottom Left to Bottom Right

**Comment by AzGilrock** [comment]
Well yeah the effect has to be re-rendered if you switch-up things in layout.  Otherwise the pixels move around but the data has been rendered to the old locations.

**Comment by tmeyermn** [comment]
So besides the flipping display on the layout tab  https://youtu.be/pmMqXX_uAtw

I found more information on the matrix I was working with.  The matrix was put into a group all by itself.  When you put effects on the group with "per preview" render style for that single matrix, it ignores the rotation values for the model.  Other render styles didn't seem to work either.  It also seemed to shrink the size of the text.  I had to put the effects directly on the model level and it worked as expected.

**Comment by AzGilrock** [comment]
Once you place a model in a group then where the pixels reside in the final buffer now become a calculated value instead of a precise value.  The code basically has to reverse calculate where the pixel lands on the 2D display screen by inversing the projection and view matrices with the model matrix.  I've seen all this positional stuff tested and I demonstrated it in my 3D presentation.  Also my display doesn't flip.  I didn't have audio so not sure if you said what you were doing but I just click and drag and everything scrolls smooth.  You know "Per Preview" means the render buffer is the size of the entire display?  You would need to define the group as Minimal Grid which should have been the default but there would be no reason to stick a matrix in a group by itself and I won't even waste time debugging that.

**Comment by tmeyermn** [comment]
Thanks for the explanation Gil, you can go ahead and close out the report.

**Comment by AzGilrock** [comment]
So I got home where I could see your video better.  You're using that Reset command.  I believe that was added while I was taking a break from coding.  It looks like its not resetting the latched positions so as soon as you click it jumps back to where you were last time you did a drag.  That is something I can fix.

**Comment by tmeyermn** [comment]
Awesome, thanks Gil!

**Comment by keithsw1111** [comment]
Tested Gil's fix it seems to work
