### ISSUE TITLE
Setting show directory changed all 3 folders

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#173]
Using OSX 4.0.14
Originally my Show directory was different than the Media and FSEQ directory.
I just clicked on Show directory Change button and changed it to /Users/bshaver/Desktop/xLights 2015/Halloween and when I selected, CHOOSE in the chooser window, the Setup tab set all three : Show, Media, FSEQ to the same folder.

**Comment by AzGilrock** [comment]
Ok I see why this is happening.  We store the folder settings in the xlights_networks.xml file.  So when you change the show directory we are reading the settings from the file in that new folder so it causes them to change to whatever you have set when you are in that directory.  These would need to change to some type of global setting and we've seen trouble with that not working on some versions of windows because they love to change how application settings are stored.
