### ISSUE TITLE
Bug: Fold Transition

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#1733]
Applying the fold, out transition results in the image being reversed at the beginning of the transition, resulting in an animation that jumps and does not look correct.

I would expect the animation to remain right reading at the beginning of the fold transition, not being reversed first then the fold transition applied.

macOS 10.14.6
xLights 2019.54

[Screen Recording 2019-09-29 at 2.07.01 PM.zip](https://github.com/smeighan/xLights/files/3667974/Screen.Recording.2019-09-29.at.2.07.01.PM.zip)

[Screen Recording 2019-09-29 at 2.18.26 PM.zip](https://github.com/smeighan/xLights/files/3667978/Screen.Recording.2019-09-29.at.2.18.26.PM.zip)

**Comment by keithsw1111** [comment]
Do you have a demo sequence?

**Comment by keithsw1111** [comment]
We need @KMojek  to weigh in on this as I am not sure if it is wrong or right.

**Comment by kppankratz** [comment]
I will attach a sequence later today.

**Comment by KMojek** [comment]
I will see if this is repro-able on Windows once we have a demo sequence. There is some weirdness with wipe as an out transition that may or may not be related.

**Comment by kppankratz** [comment]
Here's a simple 6 second sequence with the picture effect.  The moment the fold out transition begins, the image is mirrored first then rotates to finally stop in its default view.

You can change the effect to anything and still get the same odd behavior in my opinion.  The picture and text effect introduces a latent image as it is transitioning too.

[Fold Transition Bug.zip](https://github.com/smeighan/xLights/files/3678962/Fold.Transition.Bug.zip)

**Comment by KMojek** [comment]
Okay, it seems to behave as expected for me if I
* enable canvas mode on the effect
* insert an empty layer below the effect
I don't think either of those was necessary when I first added it; I'll see if I made some incorrect assumptions about rendering.

**Comment by KMojek** [comment]
Alright, it doesn't seem to be handling transparency correctly. If I save that same image with a black background instead of transparent, it seems to work as expected. If I swap out the effect for a butterfly or something else that won't generate transparency, it seems okay. Easily reproducible with a text effect, which presumably has transparency.

**Comment by kppankratz** [comment]
Canvas mode and the empty layer definitely gets rid of the latent images during the transition.

In the first attached recording, I added the fold to the beginning as well.

I guess my expectations is that it would produce a fluid spinning of the effect having both in and out set to fold and not the jerky animation result currently.

I played around a little more and was able to produce what I was after.  See second attached recording.  I ended up placing two 3 second effects, both with a 3 second in fold transition.  The second effect I had to apply the flip horizontal transformation to the buffer.

I now understand that the fold transition reverses the effect immediately for both in and out, and I wasn't expecting that.

[Screen Recording 2019-10-01 at 10.36.49 PM.zip](https://github.com/smeighan/xLights/files/3679378/Screen.Recording.2019-10-01.at.10.36.49.PM.zip)

[Screen Recording 2019-10-01 at 10.54.36 PM.zip](https://github.com/smeighan/xLights/files/3679414/Screen.Recording.2019-10-01.at.10.54.36.PM.zip)

**Comment by kppankratz** [comment]
The best way I can describe why I think this is a bug is by comparing fade in/out to the fold in/out.

0 - 100 fade in
100 - 0 fade out

This produces a seamless look to the effect because the out transition is the reverse of the in.

The fold transition does not work the same way.

0 - 100 fold in
0 - 100 fold out

The transition is the same no matter if it's applied to the in or out settings and that's why I'm seeing the jerky animation when fold is applied to both the in and out on one effect.

Using two effects and flipping the buffer on the second in transition/effect I've now manipulated the numbers to be...

0 - 100 fold in (first effect)
100 - 0 fold in (second effect, flipped buffer)

The second fold transition is now the reverse of the first and resulted in the seamless spinning motion I was after.

I hope this makes sense?

**Comment by AzGilrock** [comment]
A transition that spins or flips the buffer for video usually does look the same no matter whether its In or Out.  I'm not seeing this described as a bug it just sounds different than what you expected.  Not sure a change should be made that impacts everyone's existing sequences because what if everyone else expected it to work as is?

**Comment by KMojek** [comment]
I agree that it makes sense for the in-transition behavior to match the out-transition behavior unless there is an obvious way they should be different. This seems like a legitimate bug to me because the behavior with a text effect or image effect using an image with alpha is not what I intended. Below is the result of a potential fix... the fix here is that the transition always outputs fully-opaque colors. I think that makes sense, given that it always updates every pixel in the buffer but I need to do more testing and consideration if it could potentially break existing sequences.

![fold transition bug fix](https://user-images.githubusercontent.com/3072583/66100482-1c4b2100-e579-11e9-8e4d-582c3c7d22d5.gif)
