### ISSUE TITLE
Enhancement: When adding layers, layers (for the model) turn to LAYERED mode

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#180]
When adding layers, the effects on the top most layers should be set to LAYERED so as to reveal them through the entire model.
If you add layers to a model, currently you only see the top most layer and need to turn on the different reveal options in order to see the layers below it.

**Comment by AzGilrock** [comment]
Yeah I was actually in favor of something a little different where most of the effects would default to a "Normal" blend mode and then Layers themselves would have a blend mode.  I'd like to see it modeled after Photoshop since most people are familiar with blending in that program.  So we would do the Layer blend mode and then only apply an effect blend mode if it was something other than "Normal".  But that might have a big impact and would need team discussions.

**Comment by stevegiron** [comment]
Ability to move layers, add layers above and below fixes the second part of this issue request. 
Setting default to Layered is a personal preference. I for example hide effects on layers for later use, copying, etc. Setting top layer to layered would not be good.

**Comment by AzGilrock** [comment]
I'm closing this one because the blend mode defaults to whatever you had last selected so its not always true that you can't see the effects in the new layers.  Most of the time you should be using "Normal" and then all layers you add will default to "Normal" and will blend with lower layers.
