### ISSUE TITLE
Audio Dropouts on 2019.62

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#1804]
Starting on version 2019.62, the audio drops out and comes back on every sequence played.  It occurs generally at about one third of the way through sequence but each sequence has a different drop out time.  Time of playback drop out is consistent on each play.

Others have noted this and reported on Facebook xLights group.

**Comment by keithsw1111** [comment]
Files, logs ... something ... anything to go on? This is no more useful than the posts on facebook as is. Where are all the things the template asked for?

**Comment by schuricg** [comment]
Keith,

Here is a copy of my log file after the problem occurred. The sound dropped out at about  1:48 and came back on at about 1:49. The song file is the Greatest Showman.  It also happened after I rendered and played a second sequence. IN that song it started in a different time but the gap in each song while starting on  different times is repeatable every time the song is played or rendered again.

 I can not test it doing an export to FPP so not sure if it is just a audio output issue on the windows computer or not.

I can plan a time to Zoom and share the computer if that would be helpful?


[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3801075/xLightsProblem.zip)

**Comment by jediosu** [comment]
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3801071/xLightsProblem.zip)

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
While playing the sequence using the sequence tab, the audio mutes for a few seconds around 26 seconds to 29 seconds in my particular sequence. If I change the waveform to treble, bass, non vocal, etc. it plays as expected. If I switch back to raw the problem remains or sometimes gets worse (more time is muted.)

**To Reproduce**
Most Wonderful Time-mute.xml has the issue, I created a new sequence and imported my effects from this file into Most Wonderful Time.xml and it doesn't appear to be affected.

**Expected behavior**
Audio playback as usual


**Versions (please complete the following information):**
Windows 10 pro 1903 build 18362.449
Xlights 2019.62

**Additional context**
attached logs and sequences, if you want the mp3 let me know.

Thank you

**Comment by keithsw1111** [comment]
We believe this is fixed in .63
