### ISSUE TITLE
Pixel Lag Issues

### ISSUE THREAD

**Issue by chowell21** [smeighan/xLights#1845]
First year user of Xlights, long time user of LOR.  I've got everything up and running.  I am using 9 Alphapix 16 output controllers in unicast.  When I play my preview in each of my six sequences it looks great.  When I run the show live I have significant lag in every song.  What are some things I can troubleshoot to try and speed up?  I do not have "suppress duplicate frames" checked on my controller setup.  Do I need to turn off my wifi on my pc?  These are things I have seen touched on but nobody has offered up one single solution to the lag.  Is there a simple way to just adjust all timings in my sequences?  I remember in LOR there was a command to move all timings up or back at once.  Any help would be greatly appreciated.

**Comment by keithsw1111** [comment]
If using xSchedule ... try some of these recommendations to optimise your show:

1. Turn off OS update. The last thing you want is an outage mid-show while your machine reboots and tries to install an update.
2. Turn off power savings settings. You don’t want your machine going to sleep or slowing down just because you have not touched it for the last 5 minutes. THIS CAN IMPACT LAG
3. Consider setting up something like https://bitbucket.org/keit…/taskdaemon/…/master/bin/Release/ to monitor xSchedule's execution and restart it if it happens to fail for some reason
4. Set the following options to ensure that if xSchedule fails it restarts as close as possible to where it left off
"Late starting scheduled sequence uses time to determine start location"
"Silently exit after sending crash log" or "Silently exit without sending crash log"
5. Run check schedule and check for any issues with your setup
6. Remove any schedules and playlists you are not using ... while they may not be running they have to be checked and that consumes resources. If you want to save them just grab a copy of your .xSchedule file and you can put it back later. THIS CAN IMPACT LAG
7. If you are not looping your playlists then ensure the start/end times are not unnecessarily far apart as that requires xSchedule to hold things open. THIS CAN IMPACT LAG
8. Ensure your files are on a fast storage device ... not an old USB stick. THIS CAN IMPACT LAG
9. Consider carefully the use of fast start audio ... there are trade-offs in using it. Generally i would leave it off unless you really need it to speed up song starts.
10. If you are showing video from xSchedule try out hardware decoding ... if it works it can really help performance. If it doesn’t just turn it off again. THIS CAN IMPACT LAG BUT ONLY IF YOU ARE PLAYING VIDEO
11. Take the time to set up custom buttons for things you might need during your show.
12. Get the web client working and use the buttons plugins to control your show on your phone.
13. Consider moving your sequences back to the V1 file format. THIS CAN IMPACT LAG
14. Consider bumping up the priority of the xSchedule process in task manager. THIS CAN IMPACT LAG
15. Check any firewall you mights have turned on is set to allow xschedule to send out data.

**Comment by keithsw1111** [comment]
Did any of this fix it?

**Comment by chowell21** [comment]
Keith, thank you for responding.  Nice to hear from you after watching so
many of your youtube videos!  Some of these did make a slight difference,
however I discovered the real culprit.  I sequenced all of my songs using a
bluetooth connected speaker instead of a hard wired speaker.  It created a
delay in every song.  I had to go back and slide all of my timings to an
earlier spot.  Hard lesson learned!  Thank you again for taking the time to
try and correct my problem.  As a long time LOR user and first year Xlights
convert I was worried I had made a bad decision switching.  Not so!  Loving
Xlights so far and have a ton to learn about it yet!

Thanks again!
Corey
