### ISSUE TITLE
Add indication that Controller Config needs to be uploaded if changed.

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#1856]
**Is your feature request related to a problem? Please describe.**
Under the model properties, there is the box for the controller connection settings.  It is not clear to some that these properties do not change anything unless uploaded to the controller.

**Describe the solution you'd like**
Add some type of warning or maybe a line to check sequence, that indicates that if any of the controller connection settings were changed since the last upload to controller, that re-uploading may be necessary.

**Comment by keithsw1111** [comment]
I wont say never but the only way to really do this is to download and compare the actual config with the config xLights think it should be.

Its kind of like me asking you the config of your grandmothers computer. Sure you might be the IT guru that fixes everything when she has a problem but you cant be certain that she or someone else hasnt changed something when you werent there. Because xLights cant guarantee it is the only thing changing the controller there is no way for us to really know it needs updating. Maybe you are changing xLights to match the controller. Maybe you changed something 3 days ago and didnt upload it then ... do I have to remember?

**Comment by deplanche** [comment]
I do agree that this would be lots of hand holding, and should be necessary.  Just been seeing several cases over the last week or so where people are changing the controller configuration settings in xlights and then running into problems because nothing is changing.  They aren't realizing, or remembering, that anything is that area doesn't do anything unless it's uploaded.  Just thinking there could be a way to let them know that.  Might just need to get people used to it rather than trying to add something to handle that for all cases.

**Comment by craiggunther** [comment]
Seems like you could just keep a "dirty" flag. When the configuration is modified you set the dirty flag. When the configuration is uploaded you clear the dirty flag. Any time the dirty flag is set you have an icon that indicates the config "on this computer" has not been uploaded.
If someone is using multiple computers to configure a system then they are digging their own hole and will need to worry about coordination between computers themselves.
    On Thursday, December 5, 2019, 11:54:48 AM MST, deplanche <notifications@github.com> wrote:  
 
 
I do agree that this would be lots of hand holding, and should be necessary. Just been seeing several cases over the last week or so where people are changing the controller configuration settings in xlights and then running into problems because nothing is changing. They aren't realizing, or remembering, that anything is that area doesn't do anything unless it's uploaded. Just thinking there could be a way to let them know that. Might just need to get people used to it rather than trying to add something to handle that for all cases.

**Comment by keithsw1111** [comment]
This problem is already solved ... I called it zcpp. It guarantees your controller is configured correctly when you turn on your lights. Others disagree that is a problem and decided the protocol should not be supported on other platforms. That is their choice. I would suggest people move to a platform that understands the problem and has a solution for it.
