### ISSUE TITLE
3d objects are not displaying properly in 2019.74

### ISSUE THREAD

**Issue by ChonLee** [smeighan/xLights#1895]
When opening my layout in 2019.74, 3D objects are not where they were in previous versions.  Also, attempting to resize my OBJ tree (bothersome tree) it does not result in the actual model resizing. 

[3DLayout.zip](https://github.com/smeighan/xLights/files/4013833/3DLayout.zip)

**Comment by bhensley86** [comment]
I'm having the same problem. I updated from 2019.67 to 74 and my previous layout mesh house isn't sized correctly. So I try resizing it and it won't. Then I tried deleting my mesh layout and adding a new one. The new one won't resize either. Please fix....

**Comment by AzGilrock** [comment]
Yeah we knew way before you guys posted.  You must not hangout where the rest of us talk about all this.  The rotation upgrade accidentally removed the scaling matrix from the multiply so if you weren't using a 1,1,1 scaling its messed up.  If you browse code checkins you can see I fixed it before the issue was posted.

**Comment by AzGilrock** [comment]
Ok I tested your layout in my latest code.  It helped out because you had negative X rotation and I found I also needed to invert it on the upgrade like I do with Y.  So it looks like next release should fix everything.
