### ISSUE TITLE
Playback on sequencer tab will not stop with stop button randomly

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#192]
I noticed this starting at ~4.0.14 and up through 4.0.17 on 2 different computers

Sometimes when I start a sequence playback (Sequencer tab) with the toolbar button, the sequence does not stop when I try to click the stop button. The stop button will grey out with the song still playing.

I will then have to go to the Preview tab and stop the sequence there.

**Comment by AzGilrock** [comment]
Do you mean only the audio doesn't stop or does the play marker keep moving and data keeps rendering to the preview windows?

**Comment by stevegiron** [comment]
The scrubber line stops the rendering stops but the audio keeps playing. Must be my good music choices!

**Comment by AzGilrock** [comment]
The funny thing is version 4.0.14 actually had a fix to correct something similar to what you are describing.  The problem was if you clicked on an effect while paused it started effect play so I changed it to disallow effect play while model play is active or paused.  If you've hit another way to get into this scenario we need to figure out what else you are clicking inbetween play and stop.

**Comment by stevegiron** [comment]
Ok, I'll try to recreate and capture this one.

**Comment by stevegiron** [comment]
Issue not observed in several past updates. Closing this issue.
