### ISSUE TITLE
2020.4 Linux move to GTK3 tracking bug

### ISSUE THREAD

**Issue by cjd** [smeighan/xLights#1933]
This bug is to track current move from WxWidgets 3.1.2 and GTK2 to WxWidgets 3.1.1 and GTK3 for the appimage build.
Current appimage is at https://www.adebenham.com/wp-content/uploads/xlights/xLights-2020.4-x86_64.AppImage
This is a flow on from https://github.com/smeighan/xLights/issues/1922

**Comment by extremeskillz** [comment]
Just tried 2020.4 on Ubuntu 18.04lts and I'm getting a crash when add or deleting models. Everything else seems to be fine. Attached is my logs.
[xLights_dbgrpt-11787-20200203T195916.zip](https://github.com/smeighan/xLights/files/4150904/xLights_dbgrpt-11787-20200203T195916.zip)

**Comment by matt-torrie** [comment]
to add onto @extremeskillz there is also a crash that happens when you attempt to switch to any layout

**Comment by leighfiddes** [comment]
Another issue: Select a model on the House Preview with the mouse and then right-click on the model. The model will be rotated about 58 degrees anti-clockwise and scaled up by about 2x. This doesn't happen with the "normal" appimages.

**Comment by leighfiddes** [comment]
My mistake: This issue occurs on all 2020.x appimages. I will raise a separate issue for this.

**Comment by reenx** [comment]
I have been researching the crash when adding a new model and discovered that it goes away when using only one cpu. (From the README.linux: taskset -c 0 xLights). 

I am guessing that in between the creation of the model and the finalizing of the model an update is triggered which will trigger the assert in LayoutPanel::OnSelectionChanged because the model is invalid. 
I have no good solution yet. But at least xLights is workable for me again by using only one core.

**Comment by cjd** [comment]
Closing off old linux issues - reopen if still occurring
