### ISSUE TITLE
8bit on effect 

### ISSUE THREAD

**Issue by notfet** [smeighan/xLights#1939]
I would like to request a 8 bit checkbox when using the on effect that will let you choose 1-255 for each of the sliders if checked. When setting moves for servos, I use the DMX effect to position them and get the number for position then set the effect by placing a on effect with those values but in order to do so I wrote a python code to convert them to the 1-100 that you can choose. I do loose resolution this way but it’s nominal just figured it would be easier if the numbers were the same. I know you can have better resolution with the servo effect but it’s channels/model are limited so I prefer the on effect for servo movement.

**Comment by AzGilrock** [comment]
Probably won't happen since that was exactly what I did to the On effect in 2014 and another dev reversed it.

There is no channel limit when using the servo effect so not sure what you mean.  It's meant to be used with a DMX model which can have up to 24 servos in one model?  Do you need more than that in one model?  There are a couple 8bit issues I fixed a couple weeks ago but no new release has happened.

**Comment by notfet** [comment]
I have the capability of using 32 on that controller I built but only using 22 so I don’t need that increased. The servo effect I will have to take pictures of later today the window doesn’t go down more than 14 or so. And that effect tends to get finicky sometimes so I prefer the on effect. Will troubleshoot more after work

**Comment by AzGilrock** [comment]
Right but you don't need to stuff the entire controller onto a single model but I can easily make the number 32 instead of 24 I just never thought anyone would build a model with that many servos.  The reason the "window doesn't go down more" is because of the Node names.  If you go into the model and fix the node names it will display more than what you see.  You'll find that half the names have a minus sign in front which is the method I use to prevent a node from showing in the list so a 16 bit servo can only show up once instead of twice.  In the code updated 2 weeks ago I've already got it fixed where it will update the node names for you when you switch to 8 bit servos.  The problem with the release you are using is the names are being created for 16 bit servos.  Like I said there were a couple 8 bit issues I had to fix because I had only used 16 bit servo controllers.

**Comment by notfet** [comment]
Gil, you said that you made the change and a dev reversed that, did anyone give a reason why? Maybe the checkbox could be hidden in the settings so the average person only chooses it if they are using servos. For now I can close this thread and just use the default on effect. I know I could use value curves to get a 1-255 setting but it hides the value that way and with 80 servos by the time I finish, I was trying to make it easier

**Comment by AzGilrock** [comment]
I originally had 3 sliders with textboxes (red/green/blue) in the On effect that went from 0 to 255.  I think it also had a color swatch you could click to select the color.  I believe the issue was I wasn't using the "official" color swatches from the 6 colors (which is 8 now) to choose the color.

**Comment by notfet** [comment]
Maybe the devs won’t mind one simple checkbox that says it’s for servos only. please please please lol.
