### ISSUE TITLE
Importing timing marks into a sequence in progress doesn't show the timing marks.

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#195]
Wanting a timing mark at every beat to an in progress sequence, I ran the beat finder plugin in Audacity and exported the timing marks. Imported those marks into the sequence and they did not show. This holds true for adding 100/50/25 marks too until you save and re-open the sequence.   This did not work for the imported marks.  

As you can see the marks do show up when creating a new sequence but not for an existing sequence.  Marks named Conte-4 show on the new sequence but not on the existing sequence.

![image](https://cloud.githubusercontent.com/assets/10568498/7078633/bce0285a-decf-11e4-8e90-25adc58ba9e7.png)

**Comment by stevegiron** [comment]
![image](https://cloud.githubusercontent.com/assets/10568498/7081095/893fef36-def1-11e4-8467-4e8dcbca24ae.png)

**Comment by AzGilrock** [comment]
Yeah thanks for catching that.  I actually broke that functionality when I checked in the Superstar import stuff.  I changed the call that adds a layer to return a pointer instead of having to add the layer and then call another function to get the pointer.  It turned out the pre-existing code was adding two layers and then asking for layer 0 which was working but when I changed it to operate on the layer returned from the call it was the 2nd layer which we don't display so it caused that bug.  Not that anyone cared about the details...lol

**Comment by stevegiron** [comment]
This is just all good practice for the white sheet clean start of xLights 5.x!

**Comment by AzGilrock** [comment]
You mean where we let you model your house in 3D? :)

**Comment by stevegiron** [comment]
Test reply via webmail to Github.
