### ISSUE TITLE
Blue Handles Hidden within String Lines

### ISSUE THREAD

**Issue by jimswinder** [smeighan/xLights#1966]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Blue Handles are within end Pixels of String Line Element

**To Reproduce**
Create a String Line and make the pixel size 20

**Expected behavior**
Was expecting Blue Handle to be outside of String Line Element

**Screenshots**
See Attached jpeg

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version: 2020.9

**Additional context**
N/A

**Attachments**
-Screenshot attached showing blue dot in center of end pixel
![Handle 1](https://user-images.githubusercontent.com/13740582/76376528-b9b73780-6305-11ea-9dc0-6972a0028d4a.jpg)

**Comment by keithsw1111** [comment]
Did you increase your handle size. This is expected behaviour.

Sent from my iPhone

On 11 Mar 2020, at 1:31 pm, jimswinder <notifications@github.com> wrote:

﻿

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

Describe the bug
Blue Handles are within end Pixels of String Line Element

To Reproduce
Steps to reproduce the behavior:
Create a String Line and make the pixel size 10

Expected behavior
Was expecting Blue Handle to be outside of Sting Line Element

Screenshots
See Attached jpeg

Versions (please complete the following information):

  *   OS: Windows 10
  *   xLights version: 2020.9

Additional context
N/A

Attachments
-Screenshot attached showing blue dot in center of end pixel
[Handle 1]<https://user-images.githubusercontent.com/13740582/76376528-b9b73780-6305-11ea-9dc0-6972a0028d4a.jpg>

**Comment by jimswinder** [comment]
no...didn't know you could do that...but I see it under Preferences now...thanks Keith!

________________________________

**Comment by jimswinder** [comment]
Actually, in the picture I attached to to the bug report, the handles are set at extra large...just FYI...

________________________________

**Comment by AzGilrock** [comment]
So just make the pixel size 2...move it around...then put it back.  It's not normal to have 20 and how far away would we need to put the handles.  Do we allow users to make the pixels size 200 and then put the handles out that far?

**Comment by jimswinder** [comment]
Just a question...how come there aren't four handles, like around a wreath? Don't those expand as you make the wreath bigger and are always outside the actual wreath?

I was asking because originally I did not see the handle within the pixel because I was looking for the four handles like on other elements...no biggie..problem solved.

Thanks guys...

________________________________

**Comment by AzGilrock** [comment]
Just start using the 3D I slaved to create and you wouldn't have this problem.
![image](https://user-images.githubusercontent.com/2024669/76582524-b5b92000-6493-11ea-877c-b3e5db338eb8.png)

**Comment by jimswinder** [comment]
I'll try that...

________________________________
