### ISSUE TITLE
could not process model group due to models not being found

### ISSUE THREAD

**Issue by FarleyFamilyLightsNC** [smeighan/xLights#1979]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
IN UPDATE .10 AS .11 WHEN I OPEN XLIGHTS I GET A POP UP MESSAGE " could not process model group due to models not being found" IT IS ON THE ChromaBulb 46″ Hanging THAT WAS DOWNLOADED IN XLIGHTS... IF I GO BACK TO .09 IT STOPS AND I DONT GET THIS POP UP ON LOADING INTO XLIGHTS

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
open xlights .10 and .11

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**
![xlights issue](https://user-images.githubusercontent.com/62513970/77254944-8e541700-6c3a-11ea-93fb-eea5a19d1386.png)

**Versions (please complete the following information):**
 - OS: Windows 10,
 - xLights version  .10 and .11

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
We need a copy of your layout

Sent from my iPhone

On 23 Mar 2020, at 3:43 am, FarleyFamilyLightsNC <notifications@github.com> wrote:

﻿

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

Describe the bug
A clear and concise description of what the bug is.
IN UPDATE .10 AS .11 WHEN I OPEN XLIGHTS I GET A POP UP MESSAGE " could not process model group due to models not being found" IT IS ON THE ChromaBulb 46″ Hanging THAT WAS DOWNLOADED IN XLIGHTS... IF I GO BACK TO .09 IT STOPS AND I DONT GET THIS POP UP ON LOADING INTO XLIGHTS

To Reproduce
Steps to reproduce the behavior:
(and/or link to a short video showing the problem with audio track describing what you are doing)

  1.  Go to '...'
  2.  Click on '....'
  3.  Scroll down to '....'
  4.  See error
open xlights .10 and .11

Expected behavior
A clear and concise description of what you expected to happen and why.

Screenshots
If applicable, add screenshots to help explain your problem.
[xlights issue]<https://user-images.githubusercontent.com/62513970/77254944-8e541700-6c3a-11ea-93fb-eea5a19d1386.png>

Versions (please complete the following information):

  *   OS: [e.g. Windows 10, Mac 10.14.5, etc...]
  *   xLights version [e.g. 2019.37]

Additional context
Add any other context about the problem here.

Attachments

  *   If associated with a crash please attach/link to a dropbox containing the crash log that was produced
  *   If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
  *   If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by FarleyFamilyLightsNC** [comment]
OK SORRY I just packed a seq as a zip that will show laout tab 
[Dueling Jingle Bells2020.zip](https://github.com/smeighan/xLights/files/4366373/Dueling.Jingle.Bells2020.zip)

**Comment by keithsw1111** [comment]
I think i have this fixed.
