### ISSUE TITLE
Superstring String Type - visualizes RGB color mixing if setup as Red-Green-Blue

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#2090]
**Describe the bug**
When adjusting string properties on a model, if you setup three colors and select red, green, and blue, xLights will visualize all colors as if the model is typical RGB, not a multi-string twist.
I tested this on single line and tree models.

**To Reproduce**
See packaged show folder. I setup the single line model with colors other than red, green, and blue, which immediately fixes the problem. The tree is setup as red, green, and blue.

**Expected behavior**
Sub-divide the number of lights by the number of colors from the string properties menu and only visualize colors listed in string properties. If I designate colour 1 as red and then it is activated in a sequence, only illuminate 1/3 of lights and visualize them red. If 2+ colors are activated simultaneously, illuminate 2/3rds the lights, showing both colors (i.e. Red, Green, Off, Red Green, Off, etc).

**Screenshots**
![Annotation 2020-06-11 142823](https://user-images.githubusercontent.com/18503894/84426123-b4150a80-abf0-11ea-9e1a-eefae272f294.png)
![Annotation 2020-06-11 142823_2](https://user-images.githubusercontent.com/18503894/84426098-a95a7580-abf0-11ea-8815-eac163bbb7d2.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights 2020.23

Attachments:
[Superstring_Testing.zip](https://github.com/smeighan/xLights/files/4766649/Superstring_Testing.zip)

**Comment by keithsw1111** [comment]
This is intended behaviour.

Sent from my iPhone

On 12 Jun 2020, at 4:39 am, jholmes09 <notifications@github.com> wrote:

﻿

Describe the bug
When adjusting string properties on a model, if you setup three colors and select red, green, and blue, xLights will visualize all colors as if the model is typical RGB, not a multi-string twist.
I tested this on single line and tree models.

To Reproduce
See packaged show folder. I setup the single line model with colors other than red, green, and blue, which immediately fixes the problem. The tree is setup as red, green, and blue.

Expected behavior
Sub-divide the number of lights by the number of colors from the string properties menu and only visualize colors listed in string properties. If 1/3 of colors are activated, only illuminate 1/3 of lights. If 2+ colors are activated simultaneously, illuminate 2/3 of lights with accurate colors.

Screenshots
[Annotation 2020-06-11 142823]<https://user-images.githubusercontent.com/18503894/84426123-b4150a80-abf0-11ea-9e1a-eefae272f294.png>
[Annotation 2020-06-11 142823_2]<https://user-images.githubusercontent.com/18503894/84426098-a95a7580-abf0-11ea-8815-eac163bbb7d2.png>

Versions (please complete the following information):

  *   OS: Windows 10
  *   xLights 2020.23

Attachments:
Superstring_Testing.zip<https://github.com/smeighan/xLights/files/4766649/Superstring_Testing.zip>

**Comment by jholmes09** [comment]
Oh. Ok. I understand. For others who might find this thread later, my current alternative is to create a bunch of single-color models and match their channels to the corresponding "programming" model.
