### ISSUE TITLE
Playing Picture Effect Causes Crash

### ISSUE THREAD

**Issue by jdm7999** [smeighan/xLights#2091]
[xLights_dbgrpt-9604-20200611T152753.zip](https://github.com/smeighan/xLights/files/4766913/xLights_dbgrpt-9604-20200611T152753.zip)

**Describe the bug**
The sequence is brand new and I drop a picture effect onto the timeline. Browse to the appropriate file and select it. When I double click on the effect on the timeline to play the effect, xLights crashes. Both 2020.23 and 2020.14 (I was running .14 previously so my first troubleshooting step was to update).

**To Reproduce**
1. Add picture effect to timeline.
2. Point to correct picture file.
3. Double click picture effect on timeline to play the sequence during the effect (may have to shift-double click, depending on xLights settings).
4. Crash.

**Expected behavior**
The program should just play the selected effect timing.

**Versions (please complete the following information):**
 - OS: W7 Pro
 - xLights version: both 2020.14 and 2020.23

**Comment by keithsw1111** [comment]
Update your video card drivers. This crash is almost certainly related to that.

Sent from my iPhone

On 12 Jun 2020, at 5:44 am, James <notifications@github.com> wrote:

﻿

xLights_dbgrpt-9604-20200611T152753.zip<https://github.com/smeighan/xLights/files/4766913/xLights_dbgrpt-9604-20200611T152753.zip>

Describe the bug
The sequence is brand new and I drop a picture effect onto the timeline. Browse to the appropriate file and select it. When I double click on the effect on the timeline to play the effect, xLights crashes. Both 2020.23 and 2020.14 (I was running .14 previously so my first troubleshooting step was to update).

To Reproduce
Steps to reproduce the behavior:

  1.  Add picture effect to timeline.
  2.  Point to correct picture file.
  3.  Double click picture effect on timeline to play the sequence during the effect (may have to shift-double click, depending on xLights settings).
  4.  Crash.

Expected behavior
The program should just play the selected effect timing.

Versions (please complete the following information):

  *   OS: W7 Pro
  *   xLights version: both 2020.14 and 2020.23

**Comment by keithsw1111** [comment]
Update your video drivers. This crash is almost certainly related to that.

Sent from my iPhone

On 12 Jun 2020, at 5:44 am, James <notifications@github.com> wrote:

﻿

xLights_dbgrpt-9604-20200611T152753.zip<https://github.com/smeighan/xLights/files/4766913/xLights_dbgrpt-9604-20200611T152753.zip>

Describe the bug
The sequence is brand new and I drop a picture effect onto the timeline. Browse to the appropriate file and select it. When I double click on the effect on the timeline to play the effect, xLights crashes. Both 2020.23 and 2020.14 (I was running .14 previously so my first troubleshooting step was to update).

To Reproduce
Steps to reproduce the behavior:

  1.  Add picture effect to timeline.
  2.  Point to correct picture file.
  3.  Double click picture effect on timeline to play the sequence during the effect (may have to shift-double click, depending on xLights settings).
  4.  Crash.

Expected behavior
The program should just play the selected effect timing.

Versions (please complete the following information):

  *   OS: W7 Pro
  *   xLights version: both 2020.14 and 2020.23

**Comment by jdm7999** [comment]
Thanks!
