### ISSUE TITLE
Indicator When Collapsed Submodels Have Effects But Main Model Does Not in Sequence Tab

### ISSUE THREAD

**Issue by jjblodgett** [smeighan/xLights#2099]
When I put effects on submodels (as child of parent model), there is no indicator that lets me know effects are present. So if the parent is closed (by default when opening) or to save space when editing other models, I can't visually see the effects when scrolling around. There is also no indicator that I can tell that even alerts you to the fact that submodels are present on a given model.

Here is a collapsed parent with submodels that have effects.

![empty area at parent](https://user-images.githubusercontent.com/6646643/84677179-39473a80-aee3-11ea-8a29-bdd51b70a61a.jpg)

And here is the expanded view of that same effect.

![expanded area](https://user-images.githubusercontent.com/6646643/84677185-3c422b00-aee3-11ea-8997-f26f4f980d27.jpg)

Having an indicator of some sort would be a big help so we can quickly and easily spot the places where effects may be hidden. Here are a few thoughts on something that could help. The length of the markers in the parent cell would need to match the start/end points of any child objects with effects.

1) Ideally, there is a "submodel label / row" just below the model that shows that submodels are present. Then, when submodels have effects, an indicator (color, label, etc) could be added to that single row telling people that something is there but hidden. This would function kind of like the "add layer above / below" on a given element. It would essentially be a layer below the lowest parent model layer.
2) Background color change in the parent model cell(s) if lines aren’t easy to implement.
3) Dotted (or some other) line at the bottom (or top?) of the parent model.

I think it there was some concern that this may not be useful for everyone, it may be handy to have this as an option to enable / disable in the settings so people could turn it off if desired and/or change the visual indicator color, etc.

**Comment by AzGilrock** [comment]
Probably the 3rd or 4th request for this.  I usually close them as duplicates of #566

**Comment by jjblodgett** [comment]
Fair enough. So I guess that means it's harder to do or not likely to happen since that's 4 years old? :)

What about the "additional row" suggestion I had here to indicate submodels in general that may allow for a place to indicate that info. And/or the option to put into the settings somewhere. Should I add comments back to the original request then?

**Comment by AzGilrock** [comment]
Mainly I'm just showing the old one so if some one implements this they will know to close the old one.  I have no idea if someone wants to jump on this.  It takes a develop wanting the feature of wanting to do the work because they believe in the idea.  I think personally I never implemented it not because its not a decent idea but because I thought it would make the GUI a lot slower.  Every time an effect is drawn it would need to do a search to see if that model was part of other groups.  There really isn't a link that ties models up to the groups that hold them.  The groups know which models they contain but when you draw an effect on a model it doesn't have a link back to all the groups it belongs to so a full search would need to occur for every effect or linked lists would need to be established and maintained.

**Comment by jjblodgett** [comment]
Ah. Makes sense. So that comment was more for others and not necessarily me. I am a software developer myself (web-based, DB, etc) but don't work in C++. But your explanation makes perfect sense to me and I can see where that could be an issue. I haven't checked but if this repo contains the actual code, I might DL to look around a bit in my "spare" time. Thanks! :)
