### ISSUE TITLE
Add an option to use git for show versioning.

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#2120]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a new backup option for users that have git installed that'll automatically do the appropriate git add/commit and possibly a push if remotes are enabled.   Maybe only for non-binary files.  I know it can be done manually by the end user but just like manually creating backups, it's often overlooked.

Restores would be 100% the user responsibility if needed.

**Describe alternatives you've considered**

**Additional context**

**Comment by keithsw1111** [comment]
Even development tools dont use git in this way. Automatically committing anything seems unwise. Then you add the fact that very very few people use git to manage their shows (and in fact git is generally not a great fit for managing shows because of the way files are updated). This is not a comment out of ignorance ... I use git to manage my show and i just dont think this has any significant real world value for the community. The only plus side to git is the ability to restore back to a point in time ... and this is really no better than a good backup strategy which is much easier for general users to understand and even the backups we have have critics who believe that should be left to the operating system to manage.
