### ISSUE TITLE
DMX moving head

### ISSUE THREAD

**Issue by greerfamilylights** [smeighan/xLights#2144]
I am not sure if its a bug or me. When I go to pan my heads to the right they go to that point fine.  When I try to turn them to the left for a sweep effect, they make a full 360 to go to that point. In an actual dmx setup they will sweep back without a full spin. If I click the movements individually it works perfect. When I play the sequence that is when it makes the full turn instead of a back and forth sweep

**Comment by AzGilrock** [comment]
You are commenting on a 2 year old issue and I don't think this issue and yours are the same problem even though it sounds like the viewed motion is similar.  The original issue sounds like parameters were not configured to match reality.  If user did not configure proper start position and slew rate it would cause exactly what was described.

Your saying something changed that caused your issue so that couldn't have been OP's issue.  You need to open up your own issue and provide details like what release number changed the behavior and maybe some video of the differences your talking about.

**Comment by AzGilrock** [comment]
Model setup parameters can adjust all this...no change needed
