### ISSUE TITLE
App goes to background when creating new sequence

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#215]
This is easy to repeat.
Create a new musical sequence, pick the audio file.
Set 50ms timing, close
Add model, pick one click the X in the upper right corner of the sequence elements window.
The window will close and Nutcracker will go the background and the most recent Windows application will come to the foreground.

If unable to repeat, I will upload a video capture of this.

**Comment by AzGilrock** [comment]
No need for a video.  This has been mentioned before and I see it all the time.  Nothing to do with creating a new sequence.  It's the closing of the sequence elements window and where the focus lands.  I don't know if we can change that behavior or not. It's either Windows making the decision or it's the AuiManager code from wxWidgets.  That seems to be the only side window that does it so it may have to do with the creation order.  Not sure if we can overide the close method on that window to reroute the final focus.

If you don't want it to happen then use the icon on the toolbar to Hide that window instead of closing it.
