### ISSUE TITLE
Feature Request:  Add "ok" and "cancel" buttons to the visualize window

### ISSUE THREAD

**Issue by sslupsky** [smeighan/xLights#2270]
When using the visualize feature, it is possible to move models around.  It would be beneficial if the operation could be cancelled and the model configuration that existed prior to moving the models was restored.

**Comment by keithsw1111** [comment]
Because of the way the visualiser has to work behind the scenes the concept of ok and cancel just dont make sense. It is really just reflecting (and changing) the underlying model attributes. As such there is nothing to cancel back to. This does not make it impossible but it would be very complex to do.

**Comment by sslupsky** [comment]
Ahh.  Does "undo" work on the changes made with the visualizer?

**Comment by keithsw1111** [comment]
No. For very similar reasons.
