### ISSUE TITLE
Batch Render not saving layout changes.

### ISSUE THREAD

**Issue by neowolfwitch** [smeighan/xLights#2287]
I modified some elements in my layout and renamed a few of them since they were moved.
If i Batch Render- I'm prompted to Delete, Map, or Rename an element with it's new one. I rename it but it isn't actually saved at all.

Subsequently- every time I run Batch Render, or if I open a sequence to edit it, I'm prompted again Delete, re-Map, or rename the layout elements that changed.

This is on Mac v. 2020.42.2

![Screen Shot 2020-10-12 at 4 23 27 PM](https://user-images.githubusercontent.com/68392802/95791570-47e20a80-0ca7-11eb-8edf-a4d00f4d6519.png)

**Comment by patdelaney** [comment]
I think I ran into a similar situation, and if it is the same this is not a
bug it is by design. The batch render will not "save" the mapping for the
next time. But the solution is simple, you need to open each sequence
manually, you will be prompted in the same way, but when opening manually
it will save the changes for the next time and then you can use the Batch
render.

If needed I could probably go back and find the message that I got from the
developers about this, but the explanation made sense.

**Comment by neowolfwitch** [comment]
Unless I am missing something- the only reason to even do a Batch Render is to re-render for layout/prop changes. There is no point in even doing one if the changes aren't actually saved.

**Comment by keithsw1111** [comment]
Not true ... it is there to pick up channel changes ... not deletion/renaming of props. If you do that you need to open and save each sequence in turn ... making these changes in the middle of batch render is very likely to cause bad things to happen for lots of people.
