### ISSUE TITLE
Unable to import seq (LSP) files 4.0.32 and 4.0.33

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#232]
I attempted to convert an seq file (exported from LSP) and it failed with an error message :
ERROR: no channels defined
Finished converting all files

I used the Convert tab , Chose files - (select the .seq file), selected the audio file after that , output 
format: xlights Seq or Falcon Pi player (makes no difference)

I have also tried adding the whole house model to the sequencer tab before doing the above process.

The same file / seq (an others ) converted with no errors  using version 3.6.15.

Also tried on 4.0.33

Posted this on the xlights forum a few days ago.

**Comment by gerry4** [comment]
Hi,
Can I please enquire as to why this is a trivial bug ? At this point , without knowing what the cause is or what can be done to correct my process or work around this , I am unable to import ANY of my LSP sequences into xLIGHTS with this release.
Regards

**Comment by AzGilrock** [comment]
I couldn't find the post about this on the forum.  I thought I saw one from you about LMS imports assuming you go by gerry on the forum.  Steve's just trying to help us tag the issues because its been hard to keep up with all of them.  I wouldn't worry about the exact tag that he put on it.  But it did sound like you have a workaround.  You said you can convert using version 3.6.15.  So convert with the old version and then pull in the converted data using the new version.  You really only need to convert once per sequence so it shouldn't be a big burden.  I've never done an LSP conversion so I don't know whats involved.  I didn't think anyone had touched that LSP conversion code.  If you can get the files somewhere that I can download I'll give it a try.

**Comment by stevegiron** [comment]
Trivial=App not crashing and you can still sequence, has a workaround, misspellings, affects small number of users.

**Comment by gerry4** [comment]
Thank you Gil,
 
I had posted on the 19th of May ' Error in importing seq files - 4.00.32' , but no one replied.
 
Given that we are now on 4.00.35 and  I know (a bit) more than I knew two weeks ago , let me try it again with the latest version and also attempt to convert via 3.x if it does not work.
 
If it does not work , then I will post my setup and the import file to drop box.
 
All my existing sequences (8) are LSP , so am keen to bring them  in and then continue with new models in xlights to these sequences , plus new sequences.
 
The one that I got to work at Sydney (thanks to a LOR / xlights user) was the  import of a LOR  LMS singing face sequence (you have to double click 2-3 times to actually get the pop up list of LMS channels when using the import effects) , but  now that is the seq that keeps crashing after a  save.
 
Thank you for responding.
 
regards


Gerard
 
Date: Wed, 27 May 2015 14:00:48 -0700

**Comment by gerry4** [comment]
Hello Gil,
 
I just tried with the latest version and got the same error message.
 
I have attached the screen print of the error message, the input file (seq and MP3) and my setup.
 
The process I followed was :
Create a new sequence.
Go to the sequencer tab and add all the models
Save the (empty sequence with the models)
Click convert and select the seq file as input (Lynx conductor type)
Click on start converting
 
https://www.dropbox.com/s/c6peys98x4tqpnu/LSP%20Conductor%20file%20input.zip?dl=0 
 
I have not as yet tried the same via 3.6
 
I will also post this on the issue
 
regards


Gerard
 
Date: Wed, 27 May 2015 14:00:48 -0700

**Comment by AzGilrock** [comment]
Thanks for the files.  Took about 10 minutes but I think I fixed it.  I got the file to convert and then I saw data playing in the Preview.  So after you get the fix I'll checkin here's how to make this work.
1)  Open xLights...but don't create or open any sequences.
2)  Goto the Convert tab and choose your .seq file and .fseq for output format then hit Start Conversion.  Select your media file when prompted.
3)  The conversion will create an FSEQ file.
4)  To get xLights to use the file I copied the prefix of the name of the FSEQ file and I renamed your XML file because it needs to match the FSEQ for it to pull in that converted data.
5)  Then you can open the XML sequence file and it should have your data.
6)  You may want to switch to importing the conductor file as a Data Layer under the Sequence Settings dialog.

So the details of the fix is quite simple.  We initialize a sequence data object with a number of channels and due to the way we switched to keeping separate objects instead of one object the whole program uses the number of channels was being set to zero.  So I modified it to use the number of channels you define on the Setup tab so you will only be able to import up to the number of channels you define in Setup.

**Comment by gerry4** [comment]
Thank you  , thank you Gil !!!
 
Will try it this evening when I get home this evening (am in Australia)
 
Has really brightened up my day as between this issue and the crashes on the other sequences , I was a bit depressed :)
 
Using what is defined on the setup is great ! I have carefully mapped them from what I had in LSP and also created dummy assignments in xlights for anything unused in LSP (and mapped them to universes 71 onwards) , so that all the channels are contiguous and accounted for.
 
I will also try the data layer - I saw a video  on this (plus other videos on import/convert), but there are  now different ways, so understanding the best way (and the latest way) is tricky.
 
Many thanks for your help !
  
 
Regards

Gerard
 
Date: Wed, 27 May 2015 20:40:49 -0700

**Comment by AzGilrock** [comment]
Well I hope you didn't go home thinking you could try it.  It's not going to work till you get the next release that includes the checkin that fixes it.

**Comment by gerry4** [comment]
Hi Gil,
 
Actually I did , :) , - and I went home and tried it, got the same message , then read your email again. But:
- am happy that if is being fixed.
- I also read what you said about the data layer , so watched your latest video again , tried that and that worked !
 
So , I opened xlights , did not create a seq , went to convert , specified the input seq and output as fseq and pressed convert . It came up with the error message.
 
Then I went into the sequence settings  as you suggested and got to the data layer and did the convert from there and it converted the sequence ie I could see it play under the preview ! So I am not sure what the difference (ie user outcome/benefits) between the two methods is for someone importing LSP (conductor) files. Is one better than the other ? I will now progress to adding new models to the sequences that I did not have last year  and continue. And if that works , I will look at deleting some of the effects that I recently did in LSP on some sequences (eg the mega tree) and after the convert/import , do them in xlights instead.  Regards 

Gerard
 
Date: Thu, 28 May 2015 06:48:03 -0700

**Comment by AzGilrock** [comment]
Cool that's good info.  I see why it works for the Data Layers and not on the Convert tab.  For the Data Layers I copied the code from the Convert tab but the one change I made was I pass in the sequence data object for the layer instead of it being a global hard coded object.  The problem for the Convert tab is we aren't maintaining that global sequence data object like we used to so it ends up not having the number of channels defined.
