### ISSUE TITLE
Twinkle number of lights gap

### ISSUE THREAD

**Issue by SetMonkey13** [smeighan/xLights#2331]
**Describe the bug**
There is a gap with the twinkle effect where no lights light up.  This happens when the Number of lights is set to 34-50.

**To Reproduce**
I applied it to a model for both my gutters.
Setting the Number of lights to 34-50
Changing any of the other settings make no changes.

**Expected behavior**
The entire model has the twinkling effect.

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2020.46

[Wizards In Winter.zip](https://github.com/smeighan/xLights/files/5514574/Wizards.In.Winter.zip)

**Comment by keithsw1111** [comment]
We need a packaged sequence. I cant do anything with the file you attached.

**Comment by SetMonkey13** [comment]
Oops, sorry.  Hopefully this is correct.
[Wizards In Winter.zip](https://github.com/smeighan/xLights/files/5514655/Wizards.In.Winter.zip)

**Comment by keithsw1111** [comment]
So is this a bug ... I dont know ... its debatable. It is fundamentally the design of the algorithm. If you drop twinkle on a matrix you will see what i mean ... for some values there is a distinct pattern to which bulbs twinkle. The problem is if i change it right now it will change the appearance of everyones. For now at least the answer seems to be that you choose the settings that work for your model in your situation. You just happen to have chosen some ranges that dont look good. 

Maybe in the new year we could look at the algorithm ... and specifically the line:

                if (i % step == 1 || step == 1) {

which is what creates the banding pattern.

But if you change it you can bet someone somewhere will complain because they relied on the effects of this algorithm.

**Comment by AzGilrock** [comment]
Yep I looked at this years ago.  Its not a random effect the algorithm calculates exactly where its going to light up lights and some lights will never light up.  I've got sequences where I tweaked the value to give a good spread and people can't really tell its not random.  If you change the effect it can mess up the light density and look we have all achieved with our fine tuning.  There are other things that are more random like adding sparkles.

**Comment by AzGilrock** [comment]
Looking at older issues I found this same request at #1124.  I agree but haven't found a fix yet.  Sparkles or strobes are too quick we need a way to have a smooth fade in and out like Twinkle does but be more random.  Probably will need a new checkbox so that old behavior can be preserved.

**Comment by AzGilrock** [comment]
I fixed the Twinkle effect so it now will cycle through all pixels randomly.  Old algorithm can still be selected if desired.
