### ISSUE TITLE
Controller not showing in xScheduler 47

### ISSUE THREAD

**Issue by brandon0412** [smeighan/xLights#2336]
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
I am able to play all sequences through xLights application. When I open xScheduler, with the dame show folder selected, no contoller is shown.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
I see no way to add controller in xScheduler

**Versions (please complete the following information):**
 - OS: [Windows 10]
 - xLights version [2020.47]

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
You dont add controllers in xSchedule ... you point to the xLights show folder and xSchedule uses the same xlights_networks.xml file. If you dont have "Minimise runtime UI updates for performance" selected then the controllers will be shown in the ping panel. But if you have it selected then they wont appear because they are part of the minimised UI updates. You can still see them using the Web UI.

**Comment by brandon0412** [comment]
Thanks

**Comment by keithsw1111** [comment]
Does that mean I can close this ... or you are off testing it? You could jump into zoom and they will set you right,

**Comment by brandon0412** [comment]
Yes. Thank you
