### ISSUE TITLE
4.0.34 Speed  - stuck in low gear ?

### ISSUE THREAD

**Issue by klyneshouse** [smeighan/xLights#240]
Seems 4.0.34 speed is very slow (~1 sec) , adjusting speed slider has no effect.
Spiral and Bars both on preview display and in actual output to pixels.
Meteors and most others appear ok.

**Comment by stevegiron** [comment]
Some effect do not respond to the speed slider as they are new. Which effect are you seeing not respond to the speed slider?

**Comment by AzGilrock** [comment]
I checked Bars and the speed slider works.  You can't have "Fit to Time" checked because that causes it to override the speed and fit the rotation to the duration of the effect.  If "Fit to Time" is not checked and you still don't see it changing then you need to hit the Update button.  If I'm right please hit the Close button for the issue.

**Comment by AzGilrock** [comment]
Also the defaults were changed to check the "Fit to Time" box because that works best for most effects so that's why you may have noticed a change.

**Comment by klyneshouse** [comment]
You are exactly correct - sorry I have never noticed that.
