### ISSUE TITLE
Candy Cane Height Issue

### ISSUE THREAD

**Issue by DavidAVD** [smeighan/xLights#2433]
Version 2020.56 on Windows 10 64 -bit with a 4K monitor set to 150% scaling.

When placing a Candy Canes model, the Size / Location > Height property is 1 and the model appears as a dot.

As soon as I grab the model and resize it, the height property jumps to 50,000 or so, but shows as one cane.

When the base of the cane is stretched sideways, the onscreen model shoots up and extends way off screen.

Setting the height property back to 1 restores t back to something usable.

**Comment by AzGilrock** [comment]
When you place it are you clicking and dragging to establish the initial size?  Left click and pull to the right and you should see 3 canes by default.  If you just click and release with no drag you create a tiny model which will give you those huge height numbers when you pull the handle up.

**Comment by DavidAVD** [comment]
Ahhh... you are right. Click and drag works correctly.

Still seems like a bug, but at least that's an easy work around.

**Comment by AzGilrock** [comment]
Everything is still working the way it should the only thing we could do is force a minimum model size but not sure what that number would be.

**Comment by DavidAVD** [comment]
Understood. Just trying to help make things friendly for n00bs.

The circle model isn't affected the same way so not sure if you can take anything from that.

**Comment by AzGilrock** [comment]
Probably should also specify if you're in 2D or 3D mode because I always test 3D and never think to try 2D unless it's mentioned.  The Circle also created just a dot when I clicked with no drag and it doesn't have a height handle it has a rotate handle so it wouldn't have the same issue.  Most of those objects I just had to work with the math that was already in place when I created the 3D capabilities.  I remember the 3 point models with the height handles being a pain in the butt.  I believe the height is proportional to the width so if you just click the width is almost zero but we probably tweak it internally to prevent divide by zeros so the height divided by a tiny number creates a huge number.  Then you drag it wider and it multiplies by scaling change from the new width.  Luckily we have those numeric parameter fields where you can fix things if they go haywire.

**Comment by DavidAVD** [comment]
Sorry, I'm in 2D mode. Now that I know about the drop and drag method, it's not a killer issue.

Maybe a default height of 1 would get it into the useful range for 99% of users?

That seems to be small enough for any screen / layout, but large enough to still grab the handles easily.

**Comment by AzGilrock** [comment]
The Candy Cane does default to a height of 1.  All models based on a 3 point location have this problem.  Try it with Arches, Candy Cane, and Icicles.  They all do this.  If I can make the width handle take priority when it overlaps the height handle that would fix it.

**Comment by AzGilrock** [comment]
Yep that idea seems to work.  When I detect overlapping handles I favor the handle that resizes width instead of the height handle.
