### ISSUE TITLE
Reopening Custom filtered waveform dialog window

### ISSUE THREAD

**Issue by JensMKofoed** [smeighan/xLights#2512]
First time you select the custom filtered waveform a popup dialog windows appears to select the low and high notes for the filter.
If you would like to change this, you would have to select another filter and then select the custom filter again.

it could be nice if the dialog window will popup, just by clicking the custom filter once again.

kind regards
Jens

**Comment by keithsw1111** [comment]
The only way this could change is to remove the check mark against the selected filter because we dont actually see any event unless the radio checkmark moves ... which it does not do when you select custom again. I think having the checkmark is more useful than having to flick to raw and back to custom.
