### ISSUE TITLE
[Xlights 2021.05] Reverse and Adjustment grayed out

### ISSUE THREAD

**Issue by jstorms** [smeighan/xLights#2536]
Reverse and Adjustment grayed out

Running Xlights 2021.05 on MS-Windows 10
Repro attached.
[2021_MUS_Fireflies.zip](https://github.com/smeighan/xLights/files/6051827/2021_MUS_Fireflies.zip)

Steps:
I have two "ON" effects on Group "_HOUSE ALL" between 20 and 22.5 seconds.
Goto "Layer Blending" -> "In Transition" -> and try to check "Reverse", it is grayed out and will not check.
Also, the "Adjustment" slider is grayed out.
Tried rendering section and full sequence without change.
This was reproduced by multiple others in the Zoom room including someone on 2021.04.
Seen regardless of type of transition, also seen on out transition.
Once after using cursor keys to move effect up and down the "Reverse" checkbox and "Adjustment" became ungrayed, but was not able to reproduce to get the steps down.

**Comment by KMojek** [comment]
Okay, I can reproduce this in .05 both using the attached zipped file and my own 2021 layout. I've actually been working in the transitions code for the past few days on a different machine; I'm surprised I didn't hit it there.

**Comment by KMojek** [comment]
I suspect this may have been fixed by Dan's change here: https://github.com/smeighan/xLights/commit/d4a3be48380e7329245b318b1d42bee93c9067f3

In .05, I observe this:
* add a fade transition, which does not support reverse or adjustment
* change that to a wipe transition; should enable reverse and adjustment but it does not
* click off of the effect to somewhere with no effect
* click back onto the effect; reverse and adjustment controls are now enabled

So a workaround for now may be to just click onto a blank area and then back onto the effect. I'm still investigating though.

**Comment by KMojek** [comment]
This looks fixed for .06 by the commit referenced above. Building at the commit before that one, I'm able to repro with the steps above. The problem goes away building at that commit; closing this out.
