### ISSUE TITLE
Unable to change colors on effect and delete effect intermittently

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#255]
When selecting an existing effect and trying to change the colors, it's about 50/50 if the colors will change on the fly or even with an F5 update. If the colors don't change then the effect will definitely not be able to be deleted with the delete key or the right click delete option.

Video here http://www.stevesimages.com/xl4/xl4-colors.mp4

**Comment by AzGilrock** [comment]
Does that video have audio?  If so I got something to fix on my pc.  Anyways if you click on the effect and the cell highlights then you didn't select the effect you selected the cell.  You can only delete effects that are highlighted pink showing that they are selected.  Just because they are in the bounds of a cell doesn't mean they are selected because depending on where you click it can highlight the cell or the effect.  The hot point is supposed to be the middle 14 pixels of the effect.  If you are clicking there and it's not selecting I need to figure out how to reproduce it.  If you are outside of 7 pixels from the center of the effect it will select the cell and not the effect unless you were near the edge in which case it selects that half of the effect.

**Comment by stevegiron** [comment]
No audio on today's videos.(I'm at work)  Understood about needing to find the hot points.

**Comment by AzGilrock** [comment]
Actually the way I'm fixing the cell selection seems to be fixing the effect selection.  Hopefully I can get this finished tonight.

**Comment by stevegiron** [comment]
Haven't experience this is a while. Closing issue.
