### ISSUE TITLE
Export/Import of Effect Preset does not handle required resources

### ISSUE THREAD

**Issue by Old-Salt** [smeighan/xLights#2591]
**Describe the bug**
Exported effect presets do not include required resources.
The links for resources within an Imported effect preset point to the original file location of those resources.

**To Reproduce**
1. Export an effect preset which includes effects such as images or shaders, and possibly others
2. Import the preset to a sequence in a different show directory
3. Note the resources are not copied to the new show directory
4. Note references point to original file location.

**Expected behavior**
An exported effect preset should contain any required resources such as images and shaders
When importing an effect preset:
 - required subdirectories should be created if not already present in the new show directory
 - required resources should be placed into these directories
 - links to the resources within the effects should be updated reflecting their new locations

**Screenshots**
![Start](https://user-images.githubusercontent.com/44735832/113760893-32491d00-96ed-11eb-9f67-18a8b918d37a.jpg)
Screenshot of directory structure, right pane showing only grinch.expreset and xLights Effect Preset - none present

Post import:
![Preset Imported](https://user-images.githubusercontent.com/44735832/113761043-5efd3480-96ed-11eb-879d-80689549076b.jpg)
Screenshot of Effect Preset window showing imported preset

![Image Location](https://user-images.githubusercontent.com/44735832/113761235-9b309500-96ed-11eb-8ce1-df9f17deeba5.jpg)
Screenshot of xLights, image location

![Shader Location](https://user-images.githubusercontent.com/44735832/113761145-7e945d00-96ed-11eb-8e1a-97fc9c10b5f6.jpg)
Screenshot of xLights, shader location

**Versions (please complete the following information):**
 - OS: Windows 7
 - xLights version 2021.11

**Additional context**
Exported effect presets are used to copy effects to show directories other than the original.
Exported effect presets are often shared between xLights users - example the Google drive.

**Attachments**
[test.zip](https://github.com/smeighan/xLights/files/6266829/test.zip)
Preset, images and shaders directories have been added to zip generated by 'Package Sequence.'

**Comment by keithsw1111** [comment]
The only way we could do this would be to encode the content into the xpreset file. For some file types that would not be impossible to do ... but what happens when someone creates a preset from a video ... at that point it would get stupid.

Alternatively an xpresent could save into a zip file containing the xml and all the other files zipped up. That would be less crazy but still big. I would be just as inclined to prevent presets from being created by some content types (or limit it based on content size) and then package the smaller content in the xml base 64 encoded. That would work for shaders and maybe images. But anything big would still not work.
