### ISSUE TITLE
Sub-model display image does not reflect active pixels correctly for window frame

### ISSUE THREAD

**Issue by Slambonker** [smeighan/xLights#2684]
**Describe the bug**
Sub-model display image does not reflect active pixels correctly for window frame
**To Reproduce**
1. Create a window frame model 10x40
2. set the starting location to top left and direction to clockwise
2. Go to sub-model and add a node definition of 10-50

**Expected behavior**
only the vertical line should be highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/86269321/122837104-de86c100-d336-11eb-804c-9090e39798e2.png)

**Versions (please complete the following information):**
 - OS: Win10
 - xLights version 2021.19 64bit

**Additional context**

**Attachments**

**Comment by computergeek1507** [comment]
It looks right to me. I think your window frame definition does not match what you intend. When you set the top number of lights to 10, it is actually 12 nodes across. This is because it includes 1 node on each side from the uprights. Also you would want to start at Node 11 not 10 for the submodel. The nodes are ones based index so index "10" is still in the first 10. Index 1-10 are first 10 nodes.


![image](https://user-images.githubusercontent.com/2293065/122971068-9d090c80-d35c-11eb-9142-b0af1748bf1c.png)

**Comment by Slambonker** [comment]
Ok thanks Scott
