### ISSUE TITLE
3D model not rendering in Layout tab

### ISSUE THREAD

**Issue by wh2005** [smeighan/xLights#2700]
After upgrading to 2021.20 (via .18 and .19) from 2020.56, the layout tab no longer renders the 3D image.  It did render correctly in 2020.56, but not in 2021.18/19/20.

![image](https://user-images.githubusercontent.com/1165462/124684119-51d61a00-de83-11eb-94cd-dd0780585a79.png)

Checking the mesh only, shows the underlying 3D object mesh

![image](https://user-images.githubusercontent.com/1165462/124684177-6a463480-de83-11eb-85b0-08432ba6fad6.png)

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/6773508/xLightsProblem.zip)

3D object files
[retreats2.zip](https://github.com/smeighan/xLights/files/6773512/retreats2.zip)

**Comment by keithsw1111** [comment]
Can you create an empty sequence. Save it. Then package it up ... that just gives us the files in better shape than the method you have used.

**Comment by keithsw1111** [comment]
Relevant log entries

2021-07-06 17:36:43,725 17440 log_base [DEBUG] Loading mesh model 'Mesh-2' file 'C:\Users\willi\OneDrive\Documents\xLights\retreats2\retreats2.obj'.
2021-07-06 17:36:43,728 17440 log_base [DEBUG]     Loaded.
2021-07-06 17:36:43,728 17440 log_base [DEBUG] Added in grey texture because no-name texture did not exist

**Comment by keithsw1111** [comment]
This is user error. The obj file says the material file will be named: 3cbfe538-c7d3-4a8a-b9e0-6477c3dd819a.mtl but yours is named retreats2.mtl.

I have enhanced the logging to log this warning.
