### ISSUE TITLE
Effect presets keep getting wiped from xml

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#274]
I am using the same xlights_rgbeffects.xml file from 2014/XL-V3

All presets have been preserved until the implementation of presets in V4.  If an error / crash occurs with XL4, the presets section of the xml file get cleared out but all else stays as is.

This is all that remains for presets after a crash.
![image](https://cloud.githubusercontent.com/assets/10568498/8223605/048772fe-152f-11e5-9407-0c9de5fdf7ce.png)

**Comment by AzGilrock** [comment]
After inspecting the code I don't see any way that settings could be lost because the file is saved after every preset modification.  The only thing I could guess is that maybe if it crashed while it was trying to save the file.  What kind of operation are you doing to cause the crash because I induced a crash on purpose and I didn't lose my presets.

**Comment by stevegiron** [comment]
The crashes are very few and far between for me now. Thanks. If it happens again, I'll include the log files.

**Comment by AzGilrock** [comment]
Actually I think I discovered the problem.  I was working on making it where you can create any groups at any level you want and found that if you drag an effect it deletes every effect below where the drag started so that's probably the bug you ran into.  I'm also going to delete the Add to Favorites button.  I figure if you want a Favorites group then you can create one but I'm not making it mandatory.

**Comment by stevegiron** [comment]
I approve. Please proceed.

**Comment by AzGilrock** [comment]
I checked in changes that may have fixed this so please retest and close if it seems fixed.

**Comment by stevegiron** [comment]
Issue resolved, thanks.
