### ISSUE TITLE
Twinkle not working on custom AC models

### ISSUE THREAD

**Issue by Randomaker** [smeighan/xLights#2753]
The twinkle effect on the AC toolbar isn't working with custom AC models. Nothing shows up on node level.
[bug test.zip](https://github.com/smeighan/xLights/files/7000513/bug.test.zip)

**Comment by computergeek1507** [comment]
New render style has the issues, old render style works

**Comment by keithsw1111** [comment]
I actually think the problem is with the custom model. It creates a buffer which is the size of the model rather than a 1x1 buffer ... consequently in any given time interval for a large custom model it is reasonable possible that no cell will be triggered.

I am making a change which at one level is speculative and may break some things but overall I think it may be the right way to deal with single channel custom model render buffers.

I have tried several other effects and they seem to work as i would expect.
