### ISSUE TITLE
Auto Size Universe Count / DDP Channels when not using Full Xlights Control 

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#2804]
When you have a large show, using auto layout and full xlights control isnt always easy, if you have 100 different models, it takes less time to do the start/end channels than to let xlights do it for you and then trying to drag and drop on the ports.   The problem is when you have multiple controllers - you have to manually tell it how many DDP channel and how many universes are needed for each controller.  When you have a show with 20+ controllers, it takes quite a bit of time.

Add an option to auto size DDP channels / E131 universes  - maybe even make to give a warning if there are overlapping channels as this function wouldn't work correct if there were errors.

**Comment by computergeek1507** [comment]
Auto Size only works because you set which model are on each controller and xLights sizes it accordingly. If you just chain your models start channels, xLights doesn't know which controller the model needs to be on. The controller setting the visualizer sets can also be set in the layout tab, which has bulk edit options to make it faster for multiple models.
