### ISSUE TITLE
Presets not pasting correctly

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#281]
This video demonstrates the problem of pasting a preset into a previously converted sequence file.

https://www.youtube.com/watch?v=Xpilm1vUe9E

The primary sequence file used for the paste failure is located here:

https://dl.dropboxusercontent.com/u/28041968/Nutcracker%20Testing/My%20test%20sequences.zip

**Comment by AzGilrock** [comment]
Two things going on here.  One is your sequence was converted weeks ago back when we had a conversion bug that messed up the end time for the last effect.  Do you see that white line that goes all the way across your row that is not supposed to be there.  It is an effect that has a bad end time and is causing it to draw backwards across your entire grid which blocks all paste attempts because it finds an effect there blocking it.  Also when a preset contains more than one effect it is going to paste with the exact same time durations as the original effects you selected when you created the preset.  It does not try to fit the effects inside of any timing marks.  That's just how it's gonna work.
