### ISSUE TITLE
Preset transition times enhancement suggestion

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#2815]
After using the color dropper and value curve dropper over the past 2 seasons, they have been incredibly useful.   I've been thinking about a similar convenient way to add in/out transition times quickly to an effect.  

Perhaps some programmable buttons that would fill the in/out transitions can be something that could be implemented.  Click the specified timing and the pre-selected effect will have the transition applied without having to manually type the timing into the keyboard.

Maybe a dropdown menu with a list of numbers to be selected could be added.  Once a selection is made it would auto fill the transition time's field? 

Just a few thoughts.  Thank you for looking.

Clyde

![image](https://user-images.githubusercontent.com/12719816/134528699-7e695e2f-0fea-4f33-acd6-764c43181f63.png)

**Comment by KMojek** [comment]
I like this idea... typing in a transition duration seems clunky. My first thought would be to replace the text-input widgets with a combo-box where the chosen value can be editable. But the UI is kind-of tied to the .xsq content... in-transition durations are represented as `T_TEXTCTRL_Fadein` settings and out-transition durations are `T_TEXTCTRL_Fadeout` settings. So if the text controls were replaced, we'd need new settings (`T_CHOICE_Fadein` and `T_CHOICE_Fadeout`?) and prefer those over the 'old' settings if present. Or... leave the UI basically as-is but add something new to control what's in the text control; either a dropdown menu or some buttons as mocked out in the image above. There is unused space there so that seems feasible.

**Comment by AzGilrock** [comment]
We've had a color dropper for 2 years?  I just found it last week...lol

**Comment by computergeek1507** [comment]
> We've had a color dropper for 2 years? I just found it last week...lol

It's because it's spelled wrong

**Comment by AzGilrock** [comment]
> > We've had a color dropper for 2 years? I just found it last week...lol
> 
> It's because it's spelled wrong

Yeah at least I didn't have to lookup who added it...lol

**Comment by keithsw1111** [comment]
I agree the current approach is clunky but i dont like Clyde's proposal either. I dont see why those times are any better than random numbers as we are working with music here not clocks. The editable choice may work as a way to access recently used or values already used within a sequence. Still not perfect though.

**Comment by Clyde-L** [comment]
What about adding a dropdown selection like the color pallet has?  Add a SAVE button and xLights holds a folder with the values.  The dropdown can display a few choices and you can scroll through the rest of the list if there is a rather long one.  Click on the selection and it fills in the value?



![image](https://user-images.githubusercontent.com/12719816/155815519-c98f368c-57b3-40d3-b3f3-40c3d1f040b7.png)
