### ISSUE TITLE
not saving universe number to f16v2 DMX outputs

### ISSUE THREAD

**Issue by ha-bpratt** [smeighan/xLights#2868]
when uploading configuration to f16v2, it is not saving the universe number for the DMX output selected.

Saves the universes correctly for the normal ports, but not the DMX serial output

**Comment by keithsw1111** [comment]
I actually think this is a problem with the v2. likely you are testing this by hitting the refresh on the browser and the changes are not there. try instead hitting the serial ports link ... the upload is likely there. the problem seems to be the refresh of the browser page does not reload but resends the last data updated.

**Comment by keithsw1111** [comment]
Did you even try what I said?
