### ISSUE TITLE
Crashing When Layering Picture with a Picture

### ISSUE THREAD

**Issue by C0WB0Y-Ducky** [smeighan/xLights#2919]
I can not attach a sequence due to it crashing before I can create the Sequence. I create 2 layers on the matrix I am working on, layer 2 adding a face, layer 3 adding a picture. Once I do this it crashes immediately 
[xLights_dbgrpt-1660-20211109T203417.zip](https://github.com/smeighan/xLights/files/7509195/xLights_dbgrpt-1660-20211109T203417.zip)

**Comment by keithsw1111** [comment]
@dkulp I can definitely get it to crash when i add a picture effect on a matrix ... it seems related to the metal changes.

BindBuffer in DrawGLUtils32.cpp is failing because there are no buffers to bind to in the xlColorCanvas render.

I think it relates to the gl canvases used in the picture effect assistant (which most users likely have turned off) - i dont see it with morph which also uses a glcanvas and they look pretty similar to me.

![image](https://user-images.githubusercontent.com/10283944/141055424-cb887e06-a4eb-4ab0-8a93-bc4f96e87cd7.png)

**Comment by keithsw1111** [comment]
Found it ... Just needed to add 

    virtual bool UsesVertexAccumulator() override {
        return true;
    }

to the header for xlColorCanvas as the program was not defined that it needed.
