### ISSUE TITLE
"Randomly" Lighting Up First Channel on Various Models During Playback

### ISSUE THREAD

**Issue by jimbucks227** [smeighan/xLights#2987]
[RenderingIssue.zip](https://github.com/smeighan/xLights/files/7656938/RenderingIssue.zip)

I'm not sure how best to articulate this because it was extremely hard to diagnose and repeat.  At various times, in various sequences, on various models, all seemingly random, the first pixel of various models is being turned on as red.  The pixel remains red until another effect occurs and effectively wipes it out.  It always happens at the same time in the same sequences to the same pixels.  Removing or changing the offending effects in the sequences removes the issue.  Models light up fine with xSchedule Test.  

I've attached an example.  In the attached sequence, the circles effect starting at 29.575 and ending at 40.9 is lighting up channel 10565 when output to lights or played through xSchedule even though this channel is not part of the group on which this effect is rendered.  Changing the effect from circles to bars eliminates the error.  Deleting the effect eliminates the error.  Putting the effect back in causes the error to happen.  It is not visible in the House Preview, only on the connected lights.  

Let me know if there's any additional information or debugging I can provide.  I'm using various LOR Pixie16 controllers.  99.5% of the sequences works just fine.  

![IMG_2928](https://user-images.githubusercontent.com/95592556/144768648-cfaf28b7-795a-4612-8e5e-11cafb28234d.jpg)

**Comment by jimbucks227** [comment]
A few pictures
![IMG_2927](https://user-images.githubusercontent.com/95592556/144768613-956d2d0d-5b95-4fdd-af65-07259ca991cc.jpg)
![IMG_2928](https://user-images.githubusercontent.com/95592556/144768616-40725c6c-ee6a-4813-b95e-fd98c649ddfd.jpg)

.

**Comment by keithsw1111** [comment]
If it does not happen in the preview then you have a configuration error in your controllers or your show player. Zoom room deals with dozens of these every day so that may be your best bet for assistance.

**Comment by jimbucks227** [comment]
Hi Keith,

Thanks for the quick response and suggestion.  Is there someone in particular you recommend I connect with, particularly since I'm working with LOR hardware?  I've been in the Zoom Room several times over the past few weeks and I've also posted in the forums on Facebook and so far no one knows what might be causing the issue.  I've probably spent 40 hours debugging this and best I can figure is that it's software related.  I've gone through the configuration of my controllers in detail and everything looks correct.  My network cables are all brand new from Lowes.  I'm running the appropriate number of pixels per channel according to LOR specification and the pixel are from LOR.  If it was hardware related, would it be more random?  The issue happens at the same time, in the same sequences, on the same pixels, when playing through xLights (not xSchedule) and can be fixed by changing the effects in the sequence.  That seems to imply software.  I tried downgrading to a previous version of xLights from earlier this year and the issue actually got worse and lit more than just the first pixel on a number of strings.  Any idea what I might be doing wrong or any idea of what else I can try to debug?

Thanks,
Jim

**Comment by dkulp** [comment]
Likely too many channels on the LOR networks.    Does it still happen if you put a single Pixie16 on a network?   With the LOR protocol, different effects can definitely have an effect on what is sent and with the limited bandwidth of the USB network things, it's likely not getting all the data out before the next block needs to be sent causing issues.    LOR doesn't document the protocol so it was reversed engineered enough to get lights working, but without the full specs and such, there are definitely flags and such that we don't know what do and may allow LOR to handle more chananels.   You could also try dropping the sequence from 25ms to 50ms.   That would give the LOR output more time to actually output.   

If you have a Raspberry Pi, you could try using FPP.  The "LOR Optimized" protocol in FPP is a different implementation/code and might handle it differently, but I'm really not sure.   Again, completely reverse engineered so definite gaps.

That said, the best options are to ditch the Pixies entirely and get real lights/controllers.   Definitely too late this year.  I'd also recommend a PixieLink instead of the USB adapters, but those seem to be out of stock as well.

**Comment by jimbucks227** [comment]
Hi Daniel,

I really appreciate your reply.  I hadn't considered this.  I did try reducing the frame rate on the existing network setup without success but I didn't try isolating the Pixies on their own networks so I'll give that a shot (and potentially reduce the frame rate again).  To your point, it sounds like I'll have to replace my equipment at some point in the future.  In the interim, the PixieLink might be a good way to salvage what I can out of the LOR equipment.  

Thanks,
Jim

**Comment by jimbucks227** [comment]
Hi Daniel,

Just wanted to let you know that I did isolate the Pixies onto their own networks and the issue still occurs, always affecting the same pixel at the same time in the same sequence.  For what it's worth, I'm almost 100% certain I have the Pixies configured correctly and setup in xLights correctly.  

Thanks,
Jim
