### ISSUE TITLE
If Batch render finds something at odds, it should save the updated info, vs only saving a new fseq

### ISSUE THREAD

**Issue by tmblue** [smeighan/xLights#3017]
**Is your feature request related to a problem? Please describe.**
Maybe. I decided to batch render my entire folder and many of my sequences popped up warnings about a missing model and would I like to delete/move to another model/rename etc. I chose to rename to a new prop. Fine it renders and saves a new fseq file but my .xsq file is still wrong. 

So I did this 2 days ago doing it again today and having to baby sit this, since those changes were not saved.

**Describe the solution you'd like**
I believe if using batch render and the system finds an issue, missing prop, etc. and you give it a change, a new prop name, say move those affects to something else, it should save it in the xsq file as well as creating the new fseq.

**Describe alternatives you've considered**
I could open each sequence on my own and have it tell me what's wrong, change it, render and save it. But Batch render seems like such a better place, if it's finding the error condition already.

**Additional context**
Not sure if I'm being an idiot or not. But just seems like a good feature, self healing that should happen during a batch render.  OR do we need another tool that will open up each xsq and see if anything is at odds?

**Comment by TripleJ3EB** [comment]
+1

**Comment by derwin12** [comment]
From the command line you can run a check sequence on each sequence - its not the best option, but it is helpful in tracking down issues prior to a batch render. No fancy front end though - you need to code a .bat file or some fancy python script to call it.
xlights -cs <somesequence.xsq>  (i believe that is the syntax)

**Comment by keithsw1111** [comment]
Making permanent changes during batch render is fundamentally a bad idea.

**Comment by tmblue** [comment]
Explain why....

**Comment by keithsw1111** [comment]
I have each and every time this has come up. Saving changes during batch render is a bad idea because the user is in a poor position to make an informed decision about the right course of action. They are also limited in the actions they can reasonably take. If they take the wrong option (and there are always wrong options) their sequences are damaged ... potentially beyond repair. Just because in the one scenario you have come across you know what you want to do does not make this the right answer for all users.
