### ISSUE TITLE
4.1.11 Crash on exit wiped everything out

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#302]
Jut downloaded the newest version 4.1.11 opened a sequence made changes saved then closed the program it generated a debug report and wiped the rgb effects file clean lost all models. try to find the debug report and it is not there. Opened the program a second time made no changes or saves and exited with no issues. the third time I opened it repeating the first and had the same results but did find a Dbug report who shall I email it to.

**Comment by stevegiron** [comment]
Post the first 10 lines of the debug report here.

**Comment by RichardRennII** [comment]
0x005fac95              EffectLayer::HitTestEffect(int, int&, int&)

Crashed thread id: 1288

Thread: C5C
    <idle>

Thread: D0
    <idle>

Thread: F24
    <idle>

Thread: CBC
    <idle>

Thread: 37C
    <idle>

Thread: 105C
    <idle>

Thread: 930
    <idle>

Thread: 11B8
    <idle>

Thread: D60
    <idle>

Thread: C80
    <idle>

**Comment by AzGilrock** [comment]
I don't think this is related to this specific version.  We didn't touch anything that changes how the rgbeffects file is saved.  If it encounters a failure when trying to write the file then yes you end up with no models.  That seems to be the way the xml writer fails because first we write out the structure of the xml and then we fill in the details so when it crashes on write you end up with the skeleton structure.  The only thing I can think of is to add some type of verification to perform after the write but it the program crashes that won't help.

**Comment by RichardRennII** [comment]
After restarting the computer and trying this the last couple of days the issue has not been back. might be a good idea to restart the computer first after downloading a new release before trying just a thought.

**Comment by stevegiron** [comment]
Hi Richard, are we good to close this one now?

**Comment by RichardRennII** [comment]
Yes we are
