### ISSUE TITLE
Since Keith shutdown my "bug/feature/idea" Let's try this. bulk check for xsg files

### ISSUE THREAD

**Issue by tmblue** [smeighan/xLights#3021]
**Is your feature request related to a problem? Please describe.**
When we do a bulk render, and there is an error. We can change it on the fly. But it only fixes the fseq, not the xsg. So you see a warning, you move a prop, it saves the fseq, leaving the xsq broken, incomplete, a version behind, (however you want to state it). So if you move some other stuff around and do another batch render, guess what, you have to baby sit the process and again modify the xsq for whatever it's complaining about.

**Describe the solution you'd like**
I'd like a way to batch fix my xsq files, move a prop, swap a prop etc, vs having to manually open 50+ sequences, trying to decide which ones are impacted and which are not.

So I'd have a button that was batch load xsq files, or batch check .xsq files or something . I'd be able to click that and select show directory or others (same as batch render), it would go through each xsq file and let me know if there is an issue and give me options to fix it.  I'd then like to be able to save that response, so it doesn't ask the next 10-12 times. if it's the same warning, use the previous fix/alteration/change.

**Describe alternatives you've considered**
for script, using the cli and opening up each xsq file.

**Additional context**
I have not lost my mind, others seem to think it would be a good idea. But we all could be lost...............

**Comment by cathelest** [comment]
I agree as if you were not familiar with xlights you would no realise that it doesnt save during batch render, as you would expect it to, 

Im not too sure of what issues it would create however as generally the ones i see are due to renamed or missing models or groups etc, and changing/renaming or remapping them shouldnt effect the layout so dont beleive it will cause issues with the later sequences in the batch queue,

Perhaps a setting to save during batch render or a seperate batch render and save function,

**Comment by derwin12** [comment]
JonD or Scott? just added an early version of scripting -- I havent seen the docs on how to use it though. Waiting on that. Tools->Run Scripts

**Comment by dkulp** [comment]
The plan (when we get time to implement) is Batch render will not prompt if there are any issues loading the sequence and it will also not render it.  At the end of the batch render, it will provide a list of sequences that were unable to be loaded.
