### ISSUE TITLE
2022.02 Crashing

### ISSUE THREAD

**Issue by HonScottHMcCoy** [smeighan/xLights#3077]
Version 2022.02 (64bit) crashes when attempting to switch to Layout tab. Happens every time. Others reporting same issue in Zoom Room.

**Comment by computergeek1507** [comment]
Can you package logs and attach the zip file

**Comment by HonScottHMcCoy** [comment]
[xLightsProblem_2022-01-15-001.zip](https://github.com/smeighan/xLights/files/7876231/xLightsProblem_2022-01-15-001.zip)

**Comment by Padre653** [comment]
> Version 2022.02 (64bit) crashes when attempting to switch to Layout tab. Happens every time. Others reporting same issue in Zoom Room.

Looks like 2022.02 doesn't like spaces in the material file name (3D). For example "My House Material", xLights will look for "My" then "House" then "Material" but not " My House Material"

**Comment by dkulp** [comment]
According to the tiny_obj_loader folks and the OBJ/MTL spec, the materials file cannot have spaces in the file name.  See:  
https://github.com/tinyobjloader/tinyobjloader/issues/49
https://github.com/tinyobjloader/tinyobjloader/issues/46

**Comment by HonScottHMcCoy** [comment]
So I have to change a filename? I was using the 2022.1 just fine. After the upgrade to .02, this happens. So something changed in xLights, correct?

**Comment by dkulp** [comment]
We upgraded to a newer version of tinyobjloader.  The new version apparently adheres to the specification more strictly.

**Comment by HonScottHMcCoy** [comment]
Okay. Then how do I fix this issue? I manually changed the filename to not have spaces. However, xLights still crashes so I can't replace or remove the 3D files.

**Comment by AzGilrock** [comment]
Open the OBJ file in Notepad and make the same name changes.  The material files are listed in the OBJ file.

**Comment by sslupsky** [comment]
This issue has been fixed in the tinyobjloader project and merged here:  https://github.com/tinyobjloader/tinyobjloader/pull/285

I appears the version selected for xLights is a version more than 4 years old.  I recommend upgrading to v2.0.  It is still flagged release candidate but it contains several important fixes since the previous "official release" 1.0.6.

Note, the new lib will still require xLights users to manually fix their OBJ files since any existing OBJ file would likely not have the escaped filenames.  I recommend noting this as a breaking change in the xLights release notes so people are made aware.

**Comment by dkulp** [comment]
FYI:   2022.02 is using the latest v2.0 RC.   That is one of the major changes in 2022.02 that has caused some issues.    That commit that you point at allows escaped whitespace, but many of the obj files don't have the whitespace escaped.
