### ISSUE TITLE
2022.02 - 3D textures incompletely display in layout (expected behavior with 2022.01)

### ISSUE THREAD

**Issue by mcenerykwm** [smeighan/xLights#3094]
**Describe the bug**
3D layout image displays almost all surfaces as color:gray instead of expected surface textures (bricks, grass. etc)
Background
-3D files originally had space in file name and now with spaces removed
-this overcame the crash on opening >layout

Two approaches to update 3D files:
-1-manual editing of .mtl and .obj files to remove file name spaces
-2-Sketch-up opening original 3D files and resaving without space in file names
-then change .obj name in xLights 3D>mesh>objFile   

Outcome:
-both approaches show layout without many surfaces correctly displayed (as in versions back to 7/2019)

**To Reproduce**
-open xLights 2022.02 > click on layout > observe issue

**Expected behavior**
3D layout view should be same in 2022.01 and 2022.02 

**Screenshots**
Layout in 2022.01
![2022 01_layoutPreview](https://user-images.githubusercontent.com/52703646/150058830-5a9bbec5-3211-489d-b06e-db1830c51506.png)

Layout in 2022.02
![2022 02_layoutPreview](https://user-images.githubusercontent.com/52703646/150058752-c02aeee1-6b71-460c-83b0-2c3581d499df.png)

Packaged test sequence
[justTesting_3D textures do not display.zip](https://github.com/smeighan/xLights/files/7893861/justTesting_3D.textures.do.not.display.zip)
Zip file of 3D files including textures

3D display files
[KevinMcEnery.zip](https://github.com/smeighan/xLights/files/7893866/KevinMcEnery.zip)

**Versions (please complete the following information):**
OS - Windows 10 Home and Windows 10 Pro
xLights - 2022.02

**Comment by AzGilrock** [comment]
This is most likely due to how your faces are setup in SketchUp and how you are exporting.  There was another issue here where we talked about this.  In SketchUp there is a front and back side to every face but you can't really tell which side you are seeing unless you remove the material.  If you remove the material the front side is white and the back side is blue.  Many times when you draw you end up with the back side facing out like maybe the roof looks blue before you add the material.  That causes the material to be attached to the back side of the face.  You can right-click a face in SketchUp and tell it to flip.  Experiment with one just one face and re-export and see if it changes.  Also when you export are you telling it to keep both sides of the face?  We recommend you only export one side of the face because its a lot less rendering but it also means all your faces need to be oriented with front face pointing out.  In version 2022.02 if you exported both faces what can happen is the inside face draws last and causes it to look grey since material was missing.  Version 2022.03 I believe Dan fixed it so that it will always draw the outside face last so if you are exporting both faces it should show up in the new version but we recommend you fix the faces and only export one side.

**Comment by mcenerykwm** [comment]
Gil.
Appreciate the update.  The SketchUp files were created by another user so not aware of export settings.  I've forwarded your note regarding one-side faces.

I'll await the release of 2022.03 and reach out to confirm that the rendered image returns to prior state. 
THANKS for all your efforts in xLights enhancements  -- especially 3D features
Kevin

**Comment by Docbrew** [comment]
I upgraded from 2022.01 where everything looked fine.  I upgraded to 2022.03 and I have this issue now.

**Comment by Docbrew** [comment]
I was able to resolve this last night with some help from Dan Kulp.  Seems the .mtl file can not have any spaces in the name that includes inside the file.  I replaced the spaces in the name with _ and my house is back.

**Comment by Frowndon** [comment]
Super, that's done the trick.
