### ISSUE TITLE
Value Curve seems to only send half the value

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3099]
Attached is a test sequence.
Created two 5s shockwave effects, the first outward followed by one inward.
Below those effects is one 10s effect that is using value curves for the radius' and widths.
The one using value curves only gets to half the size of the individual effects. 
If I double the "square" end values, the result matches that of the 2 effects done separately.

[ValueCurveHalfValue.zip](https://github.com/smeighan/xLights/files/7919652/ValueCurveHalfValue.zip)

**Comment by AzGilrock** [comment]
I think its working as expected.  What happens is you begin with a start radius of 1 and end radius of 10 but it will only reach that distance at the end of the effect so 50% of the way through the effect its at 5 and then you flip the value with the square value curve.  Now the effect thinks it coming back the other direction and it starting 50% of the way through.

**Comment by derwin12** [comment]
Did you look at the sequence - why would the one full length effect not equal the 2 little ones. It really doesnt make sense. The vc one is set to be 10 at the mid-point using the square vc.

**Comment by fone626** [comment]
As you know the shockwave works by transitioning from Radius1 to Radius2 spread over the length of the effect.
So your settings would have set radius1 to 1 initially and radius2 to 10 so that effect would have set the destination radius to 10.  It's exactly as if you hadn't used a value curve at all and set radius1 to 1 and Radius2 to 10, so the end result is that half way though the effect it would have only reached a radius of 5, and that's when the value curve setting swaps to have the destination value equal one so it starts counting down from where it left off.
I wish someone would add an alternative mode to the shockwave effect so you could completely control the Radius and Width with a single value curve each.  Simply adding a checkbox to switch modes and then have only the first settings control things directly would do the trick.  That would make it so much more logical to deal with.  I'm guessing the 2 value settings must be hold overs from before value curves were a thing because they don't make much sense in a world with value curves.

**Comment by AzGilrock** [comment]
Of course I looked at the sequence I wasted a half hour of my time before figuring out nothing was wrong.  The way value curves work is the effect calculates as if the current settings it pulls from the curve are the same throughout the effect.  So you expected it to ramp up to 10 halfway through but thats not how it works.  It was attempting to ramp up to 10 for the full duration so it only reached halfway before the curve changes things up.

And for a history lesson I created the Shockwave to match the effect in SuperStar allowing us to import SuperStar sequences.  Its much easier to not use a value curve so I would say if anything that its easy to set a Shockwave to do what you want without screwing with the curves.  Its one of the few effects where the curve wasn't really needed.
