### ISSUE TITLE
Pressing F1 in layout model properties causes crash

### ISSUE THREAD

**Issue by DavidAVD** [smeighan/xLights#3100]
Pressing F1 in layout model properties causes crash

**Describe the bug**
1. Open xLights
2. Go to layouts tab
3. Select any model
4. Position cursor on one of the property names (left pane)
5. Press F1
6. Cursor changes to wait for a second or two
7. xLights closes without any warning or message

**Expected behavior**
Either nothing and some sort of help screen

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.3 (but earlier ones do the same)

**Comment by derwin12** [comment]
What is your F1 set to? I dont think there is anything configed for that key.  Help->Key Bindings.

**Comment by computergeek1507** [comment]
> What is your F1 set to? I dont think there is anything configed for that key. Help->Key Bindings.

It in theory, opens the about this tab dialog.

**Comment by DavidAVD** [comment]
I've never looked at or touched the keybindings, but checked and F1 doesn't appear in it.

I mentioned this bug in ACL chat a while ago and someone else tried F1 and found the same issue as me.

**Comment by keithsw1111** [comment]
This looks like a call loop in wxWidgets ... it goes around and around until the stack is exhausted then fails. Not sure yet if we caused it ... or its a bug in wxWidgets

**Comment by DavidAVD** [comment]
I know not to press F1 now, so not really a show stopping problem. Thanks for looking into it.

**Comment by xamidi** [comment]
I just came across that issue independently, developing my own app. I found this thread using Google.
Here is a solution I found: On Windows, pressing the F1 key fires the wxEVT_HELP event, automatically calling wxWindow::OnHelp(). Usually, it does nothing, but in my case, there was a panel inside of my own implementation of a wxBookCtrlBase, and when that panel was containing a text input control and received an F1 key press, it would crash. By simply redirecting the wxEVT_HELP event from the panel to my own empty method, the bug was fixed.

**Comment by xamidi** [comment]
I just came across that issue independently, developing my own app. I found this thread using Google.
Here is a solution I found: On Windows, pressing the F1 key fires the wxEVT_HELP event, automatically calling wxWindow::OnHelp(). Usually, it does nothing, but in my case, there was a panel inside of my own implementation of a wxBookCtrlBase, and when that panel was containing a text input control and received an F1 key press, it would crash (notably, it required two presses to crash). By simply redirecting the wxEVT_HELP event from the panel to my own empty method, the bug was fixed.
