### ISSUE TITLE
Very minor inconsistency - You cant X close the sequence settings window

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3158]
This appears to be the only window where the X isnt enabled to close the window.

File->Sequence Settings.

I suppose there is no rollback, can the X be enabled or removed?

(I know get a job Daryl ..)

**Comment by AzGilrock** [comment]
Its been so long its hard to remember why some things are the way they are.  I think I disabled it on purpose but not 100% sure why.  It could be because we wanted clear feedback on what the user wanted when the dialog disappears which is also why the "close" button was renamed to "Don't create sequence".

If someone does activate that "x" then you need to make sure to handle the return code cause it will probably return wxClose instead of wxCancel which is what triggers us to not create the sequence.

**Comment by computergeek1507** [comment]
It's probably changing the data directly when editing and not waiting until ok is pressed. I ran into this when I was copied artist name and was going to fix it

**Comment by derwin12** [comment]
Interesting point Gil .. I forgot that it is the same dialog you get when you start a new sequence. I wasnt thinking about that aspect.

**Comment by AzGilrock** [comment]
Normally what happens is we just activate the button then wait for the next bug report that lets us know why it was coded that way. :)
