### ISSUE TITLE
Debug every time i import data from xlights sequence

### ISSUE THREAD

**Issue by aalsterskersthuisje** [smeighan/xLights#321]
Hello,
I'm having an issue with importing an xlight sequence. I've allready tryed starting from zero. Created a new musical sequence and add my models. Then when i go to "import" i choose my sequence i've made in the same xlights version and when i click ok, NC crashed and gives me a debug report.
I have the 3 files from the debug report. If needed i can send them. Hope you can help me out.
Gunther

**Comment by stevegiron** [comment]
You can attach the zip file to a post on the Nutcracker 4.0 bugs forum. Post back here with the link to that post.

**Comment by AzGilrock** [comment]
So you select "Import" from the top menu, then you select "Import Effects", and then you change the filetype to "xLights Sequence (*.xml)"?  If so then I already duplicated that crash and I've got it not crashing but I'm not sure it's fully functional because you do realize using this method you are going to have to map every single node from the imported sequence to the current sequence?  I didn't feel like doing that to test it out.

**Comment by aalsterskersthuisje** [comment]
Thank you AzGilrock. Didn't know i had to map every single node. I've been looking at some video's on the xlights page and found another way to add my pixel channels together with my ac channels.

Will post the zip file right away Stevegiron. Thanks

**Comment by aalsterskersthuisje** [comment]
or maybe not right away, it says my activation mail has been send but i don't receive it. Maybe it will come with some delay

**Comment by stevegiron** [comment]
Hi, is this still an open issue for you? If not can you please close the issue. Thanks.
