### ISSUE TITLE
House Preview window randomly stops working

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#334]
Here's a video of this issue: http://www.stevesimages.com/xl4/no-layout.mp4

As an update to this video, he installed NC on a different computer and after importing a LOR sequence, the house preview stopped working. I'll get that file and link to it later.

**Comment by stevegiron** [comment]
Apparently a work around is to delete the Perspectives tagged area from the rgbeffects.xml file.

**Comment by AzGilrock** [comment]
More info for whoever tries to fix this.  The issue is caused usually when a user has 2 monitors and is displaying the House Preview on the 2nd monitor and then switches to 1 monitor or copies their show directory to a computer with 1 monitor.  The Perspective settings maintain the window offset causing it to draw off screen for a monitor that's not there.  So this can probably happen with any of the tear away panels.  Need a way to detect the situation and display the panels on the main monitor.

**Comment by stevegiron** [comment]
No longer an issue.
