### ISSUE TITLE
Opening FSEQ Directly Doesn't Generate XSQ

### ISSUE THREAD

**Issue by MrPaulAR** [smeighan/xLights#3360]
**Describe the bug**
This is quite the one off but I'm trying to edit a FSEQ (just on/off effects) that are applied to a Tesla so that I can add additional effects to what the original author created.  I do not have the original xsq file, just the fseq & audio.

I've attached a zip that contains the show folder, fseq, and audio.

The behavior that I'm seeing is as follows.
* Opening the fseq (File > Open) works as expected
* Immediately adding audio (File > Sequence Settings) deletes all channel level effects
* After opening trying to generate a XSQ (File > Save As) does not include the channel level effects
* If I convert a single row/model to effects then these are included in the XSQ (Right click on model > convert to effect)
* If I click render on a newly opened FSEQ the channel level effects are removed.

**Expected behavior**
* Clicking render should not remove channel level effects
* Adding music should not delete channel level effects
* Saving XSQ should include the channel level effects

**Versions (please complete the following information):**
 - OS: Win10 & Win11
 - xLights version 2022.14

[tesla modified layout.zip](https://github.com/smeighan/xLights/files/9237534/tesla.modified.layout.zip)
[super-mario-brothers.zip](https://github.com/smeighan/xLights/files/9237536/super-mario-brothers.zip)

**Comment by AzGilrock** [comment]
The problem is when you open an FSEQ file you do not have any effects.  You keep saying "channel level effects" are being deleted but that's not effects that's just data.  When you did the "convert to effects" option it created effects from the data.

There are other ways to deal with this but they are more advanced.  You can create a blank sequence then bring in the FSEQ file as a data layer and then you would not lose that data when you render.

Also I cannot remember if we still have the two modes Canvas and Erase mode.  If set to Canvas mode that data would not be erased.  I can't remember without being at my home PC whether that setting is a sequence wide or a data layer setting.

**Comment by MrPaulAR** [comment]
I'm just saying "channel level effects" as it's just channel data and not an effect.  Trying to differentiate the two.

Thanks for the info on the data layer as that seemed to fix the issues.  I'll close this later once I get some more time to actually work through this.

Maybe a feature request vs a bug but if one opens a FSEQ should it treat that as a data layer by default?

**Comment by AzGilrock** [comment]
Funny thing is I was thinking the whole data layer feature really wasn't needed anymore.

I'm not sure if the current logic is the same but we used to allow you to open the FSEQ and then we'd search for a matching XML (now XSQ).  If we don't find one then I'd say the best option would be to give an option to convert all the data to actual effects instead of the data layer option.

**Comment by MrPaulAR** [comment]
Works as expected.  Would be nice for a feature to convert all of the effects from the FSEQ file to on effects but the data layer meets my needs.
