### ISSUE TITLE
Updating pictures path results in multiple warnings

### ISSUE THREAD

**Issue by JamesMoore2090** [smeighan/xLights#3377]
After remapping a sequence and manually updating a pictures path I get 3 error screens telling me it can't find the original image. 

To reproduce the issue:
Create new sequence
Map sequence with picture effect to tree model
select picture effect
click browse

Warning will appear one after another. Here is a [video](https://youtu.be/XRUGjqrDYEA) of the issue.

xlights version 2022.15
Mac OS 12.5
MacBook Pro (2017)

**Comment by derwin12** [comment]
Couple of things .. you only updated one image .. perhaps you meant to bulk edit all the picture paths.
Click the first image, ctrl+a to select all effects, right click on the path and change the path for all images.

Other things you might have missed .. since you extracted the original sequence, it is best to open that sequence in their show folder (using temporary show folder), render and save. That will rename all the paths to your directory structure.

Even better way - new as of late last year? - keep the file ZIPPed. Just import from the ZIP file, it will fix all the images for you on the import step. No need to go back and fix up paths at all.

**Comment by JamesMoore2090** [comment]
I only did one image to demonstrate the issue. 

Thank you for the advice, I will take that forward.

**Comment by computergeek1507** [comment]
I have run into this and it is very annoying, the event is refiring everytime you click on or off the text box, I want to remove it but Keith added it and I don't want to step on his toes.
