### ISSUE TITLE
Request: file extensions

### ISSUE THREAD

**Issue by SteveGase** [smeighan/xLights#341]
The use of xml file extensions does not impart their purpose.  

Maybe config xml files can be changed to *.ncfg
And maybe nutcracker sequence files can be named *.nc

(the contents are still xml files... but the filenames are better defined)

**Comment by stevegiron** [comment]
I think this is just a preference. Right now the file name imparts the purpose. The extension imparts the file format.  To change the extension would require code changes in MANY places.

**Comment by keithsw1111** [comment]
While I recognise this is a disruptive change the file extension indicates the files type not its underlying format. Microsofts .docx format is actually a zip file (try it ... rename it to a .zip file and look inside). The docx extension associates it with word and allows you to easily locate your word documents. Having sequence files with a unique extension would allow the open dialogs to filter out other files and just show those that are likely to actually be sequence files.

**Comment by AzGilrock** [comment]
The only advantage I see is right now when you try to open a sequence you also see the xlights_rgbeffects.xml, xlights_networks.xml, and xlights_keybindings.xml because they have the same extension.  I tend to prefer 3 character extensions myself.  Maybe something like xl4 then if we ever get to xl10 we gotta think up something new and cool.

**Comment by AzGilrock** [comment]
Sequences were changed to .xsq
