### ISSUE TITLE
Off Effect Ignored in Group

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#3493]
**Describe the bug**
I have two groups "All_SeaMammals" and "All_SeaLions."
All the props in "All_SeaLions" are also in the "All_SeaMammals" group.

In the attached sequence, at 2:24.250 I have a Bars effect on "All_SeaMammals"
Below, at the same time mark, I have an OFF effect on "All_SeaLions."
When playing the sequence, the off effect appears to be ignored.
I tried flipping the group order incase I was confused on render order but it still did not work.

**To Reproduce**
See 2:24.250 in the attached sequence

**Expected behavior**
Group with OFF effect should override the currently playing effect for just the lights in that group

**Versions (please complete the following information):**
Windows 11 - xLights 2022.20
[GroupsBug_JeffHolmes.zip](https://github.com/smeighan/xLights/files/9843492/GroupsBug_JeffHolmes.zip)

**Comment by derwin12** [comment]
Found that setting the props to RGB->W instead of advanced works around the error.. perhaps this helps the developers.
![image](https://user-images.githubusercontent.com/4643499/197353854-f6ee76d2-c474-4820-9034-3cf491a068fe.png)
![image](https://user-images.githubusercontent.com/4643499/197353859-3709ac1c-0a06-4dd5-a688-4afa217321b3.png)

**Comment by jholmes09** [comment]
> Found that setting the props to RGB->W instead of advanced works around the problem.. perhaps this helps the developers. ![image](https://user-images.githubusercontent.com/4643499/197353854-f6ee76d2-c474-4820-9034-3cf491a068fe.png) ![image](https://user-images.githubusercontent.com/4643499/197353859-3709ac1c-0a06-4dd5-a688-4afa217321b3.png)

Oh that is interesting! Good find! Unfortunately RGBW Advanced Mode is a requirement since I am using full RGBW color mixing.

**Comment by thekev** [comment]
This change appears to cause "shadow model" method of separate RGB and W models (with overlapping channels) to conflict. If I plop an ON effect on the white channel, the RGB are zeroed. The result is the same if the white channel is above the RGB or below in the sequencer. For the last 4 years or so I have been able to address the W independently.

**Comment by keithsw1111** [comment]
@thKev I need a sample sequence with just an example of the thing you think should work to determine if this is in fact a bug or expected behaviour due to fixing the previous bug (which was a bug).

**Comment by thekev** [comment]
@keithsw1111 a simple demo: [gh-3493.zip](https://github.com/smeighan/xLights/files/10108980/gh-3493.zip)

Display elements are in the order they have worked for me in the past. The "soffit submodels" group is typical for musical sequencing and contains "RGB only" models. The "white channel" single-line overlapping model is typically used in animation-only sequences, for ambient light in postshow, etc. Prior to this change, they have been acting as independent elements. Since this change the lower model overrides the preceding model's channels. 

I might dare say this wasn't a bug - why should "white only" blank the RGB channels and "RGB only" blank the white channels? If there is a way I can adapt to this change, I haven't found it. I do not grok the more recent "advanced" option that was added since I started using RGBW.

**Comment by thekev** [comment]
@keithsw1111 had a chance to look at that yet?

**Comment by AzGilrock** [comment]
@keithsw1111 I looked at this and I'm not sure I agree with some of the changes that were done.  When the string property for "RGBW Color Handling" is set to "RGB Only" it should be zeroing out the White channel.  If someone needs to do an Off in that scenario then they need to have both an "RGB Only" and a "White Only" model that overlays like "theKev" is doing.  Also when set to "White Only" it should not be zeroing out the color channels.

**Comment by thekev** [comment]
@keithsw1111 dusting this off... I'm on 2023.13 mac and it's still doing this unwanted behavior.

Primary model:
String Type: RGBW Nodes
RGBW Color Handling: RGB Only
Effect: On (White)

Overlapping model:
String Type: RGBW Nodes
RGBW Color Handling: White Only
Effect: On (White)

RGB model blanks the White Only model's On effect. It is above the White Only in the sequencer. This can be seen in the preview. I cannot find a workaround.
