### ISSUE TITLE
2022.21 does not open

### ISSUE THREAD

**Issue by swoolf1341** [smeighan/xLights#3506]
Just downloaded and installed 2022.21, after loading the splash screen appears but xlights does not open. Rolled back to 2022.20 and everything works fine.

**Comment by computergeek1507** [comment]
Please fill out the issue template, without more information we have no idea what the issue could be.

**Comment by swoolf1341** [comment]
Where is the issue template?

**Comment by bcarriveau** [comment]
Its everything you would have had to delete when opening an issue lol.

NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**
Add any other context about the problem here.

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by swoolf1341** [comment]
Describe the bug -  Downloaded 2022.21 when notified through xlights there was a new version. Closed 2022.20 and installed 2022.21. After clicking on the desktop shortcut, the splash screen appeared (indicating 2022.21), then disappeared. xlights 2022.21 did not open.

Restarted computer, and tried again, still did not work.

Reinstalled 2022.21 with same results.

Reinstalled 2022.20, xlights opened and works as advertised.


Versions (please complete the following information):

OS:  Windows 10
xLights version2022.21

**Comment by AzGilrock** [comment]
So in the version that's working do a Package Log Files and attach that zip file here.  We need your layout since its not crashing on ours.

**Comment by swoolf1341** [comment]
zip file attached.
2022.21 first started at 15:29:07, crashed numerous times (after splash screen was visible)
2022.22 reloaded and ran at 15:37:18
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/9892942/xLightsProblem.zip)

**Comment by ebuechner** [comment]
I`m having the same problem.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/9893743/xLightsProblem.zip)

**Comment by derwin12** [comment]
Suggest trying the latest nightly build .. some updates were done for some critical .21 bugs.

**Comment by AzGilrock** [comment]
Both of these are crashing because of my PolyLine work.  Good news is I believe I fixed the problem yesterday.  I spent all day yesterday reworking PolyLine.  The reason your layouts are crashing is because you used "Lights/Node" set to 3.  The ability to set that greater than 1 has been broken since 2019.1 and that's what I was working on fixing yesterday.  The unfortunate thing was my initial work that went into 2022.20 caused that setting to crash instead of just not working correctly.  I didn't know they were releasing yesterday I was hoping for one more day but I thought it was only a problem when icicle drops were used.  Anyways that's the long version.  You could probably just edit the xlights_rgbeffects.xml file and set Parm3=1 for all PolyLine models and xLights should work or wait for another release.

**Comment by ebuechner** [comment]
Thanks Gil. I put in a bug report on that quite a while ago #3015 it'll be nice to see that fixed.

**Comment by computergeek1507** [comment]
I triggered a new nightly with Gils latest fix. Can you please try it out and report back. Thanks.

https://github.com/smeighan/xLights/suites/9027869611/artifacts/416648210

**Comment by ebuechner** [comment]
That works and it doesn't crash but what it does do is add channels that don't exist to the models creating all kinds of overlap.

**Comment by AzGilrock** [comment]
Ok I hadn't really paid attention to the channels let me look at that

**Comment by AzGilrock** [comment]
I think I have this fixed.  Was kinda a pain to tell because for some reason the end channel in the model list does not update when you change #Nodes or Lights/Node even though it looks like it should fire an even to tell them to recalculate.

**Comment by AzGilrock** [comment]
I haven't pushed the change yet wanted to look into that refresh issue

**Comment by AzGilrock** [comment]
Well I pushed the changes.  I think the refresh issue has been there quite awhile.  We used to do too much recalculating all the time so it got throttled back so sometimes the channels you see in the model list are not up to date.  Like I saw channel counts that seemed wrong then I drew an Arch and it fixed itself.

**Comment by AzGilrock** [comment]
By the way do you really have 3 lights per node?  @ebuechner 
Is this for a Ribbon Strip?
You could just set Lights/Node back to 1 and it will fix the channel count until this fix gets into a build.

**Comment by ebuechner** [comment]
Yes, strips.

**Comment by swoolf1341** [comment]
> Both of these are crashing because of my PolyLine work. Good news is I believe I fixed the problem yesterday. I spent all day yesterday reworking PolyLine. The reason your layouts are crashing is because you used "Lights/Node" set to 3. The ability to set that greater than 1 has been broken since 2019.1 and that's what I was working on fixing yesterday. The unfortunate thing was my initial work that went into 2022.21 caused that setting to crash instead of just not working correctly. I didn't know they were releasing yesterday I was hoping for one more day but I thought it was only a problem when icicle drops were used. Anyways that's the long version. You could probably just edit the xlights_rgbeffects.xml file and set Parm3=1 for all PolyLine models and xLights should work or wait for another release.

Changed all poly lines lights/node setting to "1" and 2022.21 opened correctly. For now, will revert back to .20 to fix polyline settings for Christmas layout. Thank you.

**Comment by ebuechner** [comment]
I'm testing in the latest nightly build and this issue seems to be resolved and this should clear this issue as well as #3015.
