### ISSUE TITLE
Window frame model

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#351]
When creating a window frame model and you have 150 pixels across the top 50 down each side it will only allow for 100 pixels across the bottom

**Comment by AzGilrock** [comment]
Actually the limit for the bottom is independent and has nothing to do with the other 2 fields.  It appears the model dialog is reusing those spin controls so that control just happened to be the number of strands per string which had a limit of 100.  Currently the top has a limit of 1000 and the sides have a limit of 65535.  So what do we think the largest window frame should be?
