### ISSUE TITLE
Color Wash effect Enhancement

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#3517]
Can the Color Wash be updated to do a Reverse Vertical and Reverse Horizontal Fade?  I know I can do this manually with 2 layers, but there are buffer limitations with roto-zoom using those 2 layers.  Just curious?

Thank you!

Clyde

![image](https://user-images.githubusercontent.com/12719816/199091381-6c76bd31-b5e2-406d-918c-2d04131def38.png)

**Comment by KMojek** [comment]
I haven't looked at the Color Wash effect rendering until now but it seems like forward (i.e. existing behavior) and reverse would be mutually exclusive? So maybe the UI should be a little different to reflect that. Or could possibly simplify by having a single reverse setting? Not sure if it'd be useful to have a 'forward' vertical and a 'reverse' horizontal for example.

**Comment by KMojek** [comment]
Thinking about it some more, adding a single new 'reverse' setting would be less disruptive. Things in sequence files are somewhat tied to UI controls... i.e. there will be things like `E_CHECKBOX_ColorWash_HFade` settings in sequence files. So if we update the UI so that's maybe a radio box instead of a checkbox, it will be a whole lot of 😬

**Comment by KMojek** [comment]
Closing this out; I'm not 100% sure if what was implemented was exactly what Clyde was expecting. If not, I can adjust it later.
