### ISSUE TITLE
LOR Pixcon16 MK II - Configuration Error

### ISSUE THREAD

**Issue by xlightsardunan** [smeighan/xLights#3527]
Hi,

PixCon16 MK II
FW 2.0.13
When uploading the config file, the unit locks out any pixels over 170.

Error confirmed
Using PixCon config utility
Factory reset PixCon
Reloaded Firmware
Re-configured
Set 340 pixels
Tested - positive
In xLights "refound" the PixCon
UpLoaded configuration
Tested - only 170 pixels on
Back in PixCon Config utility - will not allow mroe than 170 pixels.

This error has arrived sometime in v2022.  I did not have this problem in my 2021 show.
I have 9 PixCom16's in my show.  All of them have the same problem.

My email is xlights@ardunan.com

**Comment by keithsw1111** [comment]
Likely because it is in the expanded mode?

Sent from my iPhone

On 7 Nov 2022, at 6:19 am, xlightsardunan ***@***.***> wrote:

﻿

Hi,

PixCon16 MK II
FW 2.0.13
When uploading the config file, the unit locks out any pixels over 170.

Error confirmed
Using PixCon config utility
Factory reset PixCon
Reloaded Firmware
Re-configured
Set 340 pixels
Tested - positive
In xLights "refound" the PixCon
UpLoaded configuration
Tested - only 170 pixels on
Back in PixCon Config utility - will not allow mroe than 170 pixels.

This error has arrived sometime in v2022. I did not have this problem in my 2021 show.
I have 9 PixCom16's in my show. All of them have the same problem.

My email is ***@***.******@***.***>

**Comment by xlightsardunan** [comment]
Fixed the error now.

I flashed each unit.
Reconfigured into the network
Deleted the unit from xLights
Discovered in XLights
reset universe
Saved
Upload config to the unit
Unit is retaining its configuration.

somewhere between 2021.40 and 2022.19 something got broke and then fixed in the LOR PixCon16 upload push.
