### ISSUE TITLE
Background Image on layout not showing house image

### ISSUE THREAD

**Issue by JimmieNC** [smeighan/xLights#3533]
![xlights](https://user-images.githubusercontent.com/43420564/200390983-f2c10553-e874-4302-a326-d59b1c660aa7.png)

**Comment by derwin12** [comment]
This is almost always a open gl issue - update your windows driver for your machine. xLights was updated in the beginning of the year to a new library requiring updated drivers. Check your mfg website for a driver.

**Comment by Sparky2211** [comment]
Ironically, I've been having this same exact issues since one of the recent xLights updates. I'm been playing around with a ton of different things and I haven't been able to figure out what the heck is going on. If you end up figuring it out, I'd love to hear what your solution was. I agree that it probably has something to do with OpenGL as mentioned by @derwin12, but I don't see any evidence of that so far.

![image](https://user-images.githubusercontent.com/117866028/200946905-8a0440a7-3dfc-4cd0-a946-76bf7854c05f.png)

**Comment by JimmieNC** [comment]
Sparky
I did an update to my drivers and it took care of the issue, pretty sure it was the open GL driver.

**Comment by Sparky2211** [comment]
@JimmieNC, I'm glad to hear that cleared up your issue!
