### ISSUE TITLE
Candy Cane Render Issue from ZoomRoom .. Two vs Three Canes

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3534]
Using the default candy cane model - one with 2 canes, the other with 3 canes. The 3 canes renders a spiral correctly. The 2 cane model renders almost all solid color. Checked with 1 and 4 and they worked correctly.
Nothing fancy about the spiral - just the default values.

![image](https://user-images.githubusercontent.com/4643499/200396536-f3f09b72-4063-4ca8-9873-32a93120079a.png)
![image](https://user-images.githubusercontent.com/4643499/200396515-a1c5135e-79ed-4f87-a7b0-8a58fab2faea.png)
[CaneBug.zip](https://github.com/smeighan/xLights/files/9954795/CaneBug.zip)

**Comment by AzGilrock** [comment]
I'm just looking at XML from work but your double candy cane looks like a Custom Model wherease the triple candy cane is actually using the Candy Cane Model.  Those create completely different render buffers.

**Comment by derwin12** [comment]
Nope .. both the basic candy cane models .. one set to 2 the other set to 3.

**Comment by AzGilrock** [comment]
Yeah that was the problem looking from work.  There was a custom model right below it that confused me.  This is a weird one.

**Comment by AzGilrock** [comment]
I can get it to do some weird stuff on the triple cane as well if I adjust settings.  Marquee works fine on the model.  Gotta imagine this is because you are trying to draw a spiral on a buffer that is only 2 pixels wide.  Probably a bad effect for that model.

**Comment by keithsw1111** [comment]
Try setting thickness to zero ... that helps with the 2 cane model ... but breaks still with 1 cane. Changing anything here at this time of year would be very problematic as it would almost certainly negatively impact existing sequences. I tried a few edge case fixes but none really worked to my satisfaction. The root cause here is the spiral model uses the model width as the key driving factor which works well on single lines which are always wide. Not so well on canes using default buffers.

**Comment by AzGilrock** [comment]
There is a pretty simple workaround.  Just grab a couple corners on the right and oversize the render buffer in the buffer settings panel.

**Comment by derwin12** [comment]
Not worth the fix ..
