### ISSUE TITLE
2022:22 sequencing panel grayed out

### ISSUE THREAD

**Issue by chrisreynolds01** [smeighan/xLights#3550]
After installing 2022:22 my sequencing panel went gray. I can run an old sequence but it doesnt show up in the "black sequencing" area. 

I have tried to download on external drive with still no improvements.
![thumbnail](https://user-images.githubusercontent.com/118003927/201374413-b92488c5-d2ce-41c6-a87e-c73c8bc02b1b.jpg)

Thank you,

Chris

[NOTE:](url) IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment]
Try updating your video drivers.

Sent from my iPhone

On 11 Nov 2022, at 9:43 am, chrisreynolds01 ***@***.***> wrote:

﻿

After installing 2022:22 my sequencing panel went gray. I can run an old sequence but it doesnt show up in the "black sequencing" area.

I have tried to download on external drive with still no improvements.
[thumbnail]<https://user-images.githubusercontent.com/118003927/201374413-b92488c5-d2ce-41c6-a87e-c73c8bc02b1b.jpg>

Thank you,

Chris

NOTE:<url> IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:
(and/or link to a short video showing the problem with audio track describing what you are doing)

  1.  Go to '...'
  2.  Click on '....'
  3.  Scroll down to '....'
  4.  See error

Expected behavior
A clear and concise description of what you expected to happen and why.

Screenshots
If applicable, add screenshots to help explain your problem.

Versions (please complete the following information):

  *   OS: [e.g. Windows 10, Mac 10.14.5, etc...]
  *   xLights version [e.g. 2019.37]

Additional context
Add any other context about the problem here.

Attachments

  *   If associated with a crash please attach/link to a dropbox containing the crash log that was produced
  *   If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
  *   If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by chrisreynolds01** [comment]
You are the man! That fixed the problem. I was about to give up this year!! Thank you for all you do for this hobby. Chris ReynoldsOn Nov 11, 2022, at 9:45 AM, Keith Westley ***@***.***> wrote:﻿
Try updating your video drivers.



Sent from my iPhone



On 11 Nov 2022, at 9:43 am, chrisreynolds01 ***@***.***> wrote:



﻿



After installing 2022:22 my sequencing panel went gray. I can run an old sequence but it doesnt show up in the "black sequencing" area.



I have tried to download on external drive with still no improvements.

[thumbnail]<https://user-images.githubusercontent.com/118003927/201374413-b92488c5-d2ce-41c6-a87e-c73c8bc02b1b.jpg>



Thank you,



Chris



NOTE:<url> IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.



Describe the bug

A clear and concise description of what the bug is.



To Reproduce

Steps to reproduce the behavior:

(and/or link to a short video showing the problem with audio track describing what you are doing)



  1.  Go to '...'

  2.  Click on '....'

  3.  Scroll down to '....'

  4.  See error



Expected behavior

A clear and concise description of what you expected to happen and why.



Screenshots

If applicable, add screenshots to help explain your problem.



Versions (please complete the following information):



  *   OS: [e.g. Windows 10, Mac 10.14.5, etc...]

  *   xLights version [e.g. 2019.37]



Additional context

Add any other context about the problem here.



Attachments



  *   If associated with a crash please attach/link to a dropbox containing the crash log that was produced

  *   If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file

  *   If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file



If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
