### ISSUE TITLE
frequent crashes on linux

### ISSUE THREAD

**Issue by reenx** [smeighan/xLights#356]
Hi,
I started with xLights a few months ago on Fedora and compiled xLights myself.
It all went very well, and i wanted to upgrade to the latest greatest. After updating and rebuilding I could not work with xLights for more than a few minutes before it crashed. Just clicking on an effect or dragging it would crash xLights. 

After investigating I traced it back to commit 02921f31c85f8475727f68f1016be4643ba8f780 on august 15th
(A change in handling of MemoryDC's)
I reverted this change and all crashes were gone. I have not looked at the code before and I also do not know what the commit was about (Or intended to fix), but for me this commit makes xLights unusable for me.

**Comment by cjd** [comment]
Which release did you test with?
I committed some changes about 4 days ago as https://github.com/smeighan/xLights/commit/4bf691d6624dd4098d496eefb4f4e974e1b777a4 which moves a lot of the rendertext stuff from the background thread to the gui thread to hopefully fix this sort of problem.
The fix was released in 4.2.7 about 8hrs ago :)

**Comment by reenx** [comment]
I used git bisect to determine the exact commit that caused the problem.
The crash occurs within minutes if I drag effects around on the sequence
tab.

And I did see your commit. It did improve things, but I still had a crash.
I saw you skipped the unshare method if it is a linux build. Maybe the
unshare method is the cause of crashes on linux? It was changed in the
commit that causes my problems.

My last test was on the commit just before the release commit. Still
crashes.
I merged this into my own branch. (only change is that reverted commit) and
I could work for at least 2 hours without a crash.

I tried a debug build once but xLights crashes so fast it won't even write
a debug report. I forgot the error message, I can check for you tonight. Or
if you want me to do some research on this, I can build on my system. I am
just not familiar with the code of xLights. Maybe there are some extra
compile flags to get more debug output?

**Comment by cjd** [comment]
The core problem is that wxwidgets behaves differently on linux compared to windows in how it handles background/gui thread access.  I'm still working on a proper fix/workaround for that.
I can't really just revert that problem commit as it is needed for windows
There are a bunch of other crashes in the debug build at the moment caused by some differences in string formatting (windows is more permissive with types - ie: it allows %d even though it is being passed a long int)  I've only just recently joined the dev team with the aim of getting things working on linux so there is still more work needed :wink:

**Comment by cjd** [comment]
(note: the fix so far just stops xlights from crashing - the text effect is broken)

**Comment by reenx** [comment]
I understand that reverting the commit is not a solution. But it might
point in the right direction.

**Comment by cjd** [comment]
I've just committed some more changes as https://github.com/smeighan/xLights/commit/b6113d06b8dc4190c5fb7bd88c2c68061b98a903 and https://github.com/smeighan/xLights/commit/b6c8c6b8451c1aa9c1aaeea3984d5045f74c242e
These fix up the text effect and how stopped the crashes I was seeing.
Let me know if these changes fix up your crashes

**Comment by dkulp** [comment]
Those changes will now cause random crashing on the Mac where the text rendering is done on the background thread.   We cannot call wxGraphicsContext::Create(*image); on a background thread as that internally creates a new MemoryDC for the image which then uses the shared Pens and Brushes that then get their ref count messed up causing crashes.    We'll need to make these changes specific to Linux.

**Comment by cjd** [comment]
:( - I was only able to test on linux and windows so wasn't aware it would mess up things on mac.
I'll see what I can do

**Comment by cjd** [comment]
I've reverted the fix until I can find another way

**Comment by cjd** [comment]
Okay - simpler/smaller fix now committed as https://github.com/smeighan/xLights/commit/adc52987f222b1ec8661e933f3ba071f2c00cdf1
The only changes are made within #ifdef LINUX bits so it shouldn't affect mac/windows at all

**Comment by reenx** [comment]
I tested with release 4.2.9, both the normal and the debug build still
crash. With the debug build I do not get a crash report.
The only message I get on the console is:

xLights: Fatal IO error 11 (Resource temporarily unavailable) on X server
:0.

What I do to reproduce the crash is:
- start xLights
- open a sequence
- drag some effects around on the sequence tab. Within halve a minute
xLights crashes. Usually on the moment I click on a handle or on the
central square of an effect.

**Comment by cjd** [comment]
I can't reproduce that anymore - Can you attach your xlights_rgbeffects.xml and xlights_networks.xml files along with a problem sequence so I can try and reproduce?
What distro you building/running?

**Comment by reenx** [comment]
I uploaded the files here: https://gist.github.com/reenx/a668561cbaf30a771a69

My system is a fedora 22 system.
I compiled wxWidgets myself according to the instructions in the readme. I used version 3.0.1

There are some issues I need to fix with this sequence,  I am not sure if they contribute espessially since these problems were there already before the crashes.

My todo's in the sequence: 
-I get a complaint about too much data when the mp3 is read.
-I have a gap in the address range. About 4 adresses have no light assigned to them. I left them in from an old setup.

**Comment by cjd** [comment]
Thanks for the files.
I grabbed them and loaded up xlights using them but was unable to cause a crash.
I tried loading your sequence, then adding/removing/resizing various random effects - but no crashes even after 5 mins :(

Regarding the sequence - I can't say for sure about the mp3 (since not included) but I wouldn't expect that to cause a crash.  You may want to re-encode it to clean the file up - but no rush.
The gap in the address range should be fine - That is not un-common and should work fine as well
There is were another bunch of fixes over the last week to the sequencer table handling - maybe one of those fixed this issue up.
Note: the original issue this bug was logged for should be fixed up - you look to be hitting a new issue now :(

**Comment by reenx** [comment]
I googled the error message today and found a possible rootcause of my crashes. It has to do with a multicore system. I found someone with the same error message (but different application) and that it could be caused by how Xwindows uses sockets to communicate and that this can go wrong on a multicore system. 
I did a small test and by limiting xLights to only one core, I could drag and drop and play with the sequences without a single crash!

To limit xlight to core 0 I used the command:'taskset -c 0 bin/xLights'

I'll see what I can find out more.

**Comment by cjd** [comment]
Where did you find that info? I'll have a look as well to see if I can find anything

**Comment by reenx** [comment]
Just to let you know. I had a succesfull christmas display. And no more crashes. I think I messed up the libraries during compiling. So I used different libraries during compiling and running. I used version 4.2.24 for the christmas display and no crashes during fine tuning or during showtime. So this issue is resolved as far as I am concerned.
