### ISSUE TITLE
Singing Faces Not Working

### ISSUE THREAD

**Issue by JoeSchulze** [smeighan/xLights#3568]
Singing face on GE Hattitude and singing bulbs do not generate proper face animation (only random pixel(s) will highlight). Faces in prop layout all seem to be correctly defined. All worked ok when generated on 2022.20 but stopped working with 2022.22(skipped the 21 update). Tried backtracking versions to 2022.21 then again back to 2022.20 with no luck. Also tried reloading models with no luck. Almost like something is locked(messed up) in one of the core xlights reference files. Sequence that used singing faces generated in 2022.20 still works but nothing new will work. Troubleshooted extensively with Gary Hatt (Hattitude creator)and David Spalding from zoom room. 

[SingingFacesIssue.zip](https://github.com/smeighan/xLights/files/10018236/SingingFacesIssue.zip)

**Comment by merryoncherry** [comment]
I investigated this because I have 4 of the props on the house and if they didn't work I would be very sad.

I will say that "Check Sequence" is your friend... and you should advise Gary Hatt and David Spalding of the same.  (And thank them for a prop I enjoy immensely).  You can see from the log that you have roto-zoom set on the singing face effect (zoom of .8) that is causing your problem.  If I clear that off, it is fixed.

![CheckSequence](https://user-images.githubusercontent.com/102841136/202175280-688957f1-ee97-4a52-bc37-d4f34be12d24.png)

**Comment by JoeSchulze** [comment]
Thanks very much for discovering that. Would have never expected a change in that setting. Lesson learned I suppose to "check sequence". It was so simple of a sequence just assumed all was ok. Very strange I did not (at least intentionally) even play with that setting ever. Working now after setting zoom back to 1 per your suggestion.
