### ISSUE TITLE
2022.23 - Missing poly line model in preview

### ISSUE THREAD

**Issue by githubpassera** [smeighan/xLights#3574]
Windows 11
Poly line model is OK in 2022.22 but missing in preview 2022.23

**Comment by ebuechner** [comment]
I think this goes back to the lights per node. I downloaded 23 and had the same issue and then when I changed the lights per node number it turned my whole layout into a scrambled mess and made my RGB effect file completely unusable. I thought this issue was taken care of because I downloaded one of the nightly builds and everything was working as it should.

**Comment by AzGilrock** [comment]
Well someone needs to actually provide a layout with the problem cause they are working fine for me in 2022.23.

**Comment by AzGilrock** [comment]
Nothing has changed in the PolyLine since 9 days ago so unless the build process messed something up.  Windows did go to a new Visual Studio version and I'm running on the Mac.

**Comment by githubpassera** [comment]
> Well someone needs to actually provide a layout with the problem cause they are working fine for me in 2022.23.

Can I email my showfolder xml-files?

**Comment by ebuechner** [comment]
[Grinch.zip](https://github.com/smeighan/xLights/files/10044504/Grinch.zip)

**Comment by keithsw1111** [comment]
I pulled the window release as there is something odd in the release build and rebuilding all did not fix it.

Sent from my iPhone

On 18 Nov 2022, at 2:51 pm, Gil Jones ***@***.***> wrote:

﻿

Nothing has changed in the PolyLine since 9 days ago so unless the build process messed something up. Windows did go to a new Visual Studio version and I'm running on the Mac.

**Comment by computergeek1507** [comment]
can you try this build of 2022.23 and see if it works. https://drive.google.com/file/d/1dILmTIlyx-6C9hLrpT1aKH9WYhPuiDGZ/view?usp=sharing

**Comment by jefft0825** [comment]
That worked!!!  Submodels export now with the model in groups and it doesn't change the size. 

Thank you!!

**Comment by ebuechner** [comment]
I've downloaded this version and so far everything seems to be stable.

**Comment by AzGilrock** [comment]
I'd hold off it sounds like there are issues with the release build.

**Comment by AzGilrock** [comment]
Sorry the screen I was looking at didn't have the last 4 messages

**Comment by githubpassera** [comment]
> can you try this build of 2022.23 and see if it works. https://drive.google.com/file/d/1dILmTIlyx-6C9hLrpT1aKH9WYhPuiDGZ/view?usp=sharing

Poly line model back.
The original .23 installation got a lot of Norton data protector warnings on ex. png files and the protection had to be temporarily disabled to continue. (This has happens on few earlier releases as well.)
.23 from link above passed without any Norton issue.

**Comment by keithsw1111** [comment]
I reposted 23 with a new compile of wxWidgets and the issues i was seeing with it seem to be resolved.
