### ISSUE TITLE
Latest Release - xLights64_2022_23.exe - 404 Not Found

### ISSUE THREAD

**Issue by digitydogs** [smeighan/xLights#3575]
Just wanted to let you know the latest release didn't actually post to the main page and presents a 404 page, also the forum is down.

**Comment by derwin12** [comment]
I *think* it was deemed buggy and removed.

**Comment by digitydogs** [comment]
Ahh my xlights instance told me there was an update available and when i tried to get it nothing and no info in release notes etc to indicate there was an issue. Hopefully they get it resolved soon and post another build, i need one of the bug fixes.

**Comment by scottbob09** [comment]
SAME.  Windows build failed on this version

**Comment by Sadrok18** [comment]
issue downloading latest version

**Comment by scottbob09** [comment]
File is now on the repository.  Just installed on Win

**Comment by digitydogs** [comment]
Very odd, now the website lists 2022.23 as retracted and only offers you 22, but scottbob09 is correct and 2022.23 is now on the repo.

**Comment by scottbob09** [comment]
There is some funny business with this release.  Very laggy.  I think

**Comment by freman** [comment]
As someone who got this release... can confirm, buggy.

I have Chinese characters in all my time scales, if I try to change the bitrate for video export it won't take because it auto inserts Chinese characters and fails to validate, if I open the sequence preferences dialog it is unclose able, the done button never enables and the dialog close button doesn't work.

**Comment by bcarriveau** [comment]
Go to the releases here and grab the new .23 in the assets. Its fixed.

**Comment by keithsw1111** [comment]
I have reposted 23 which should fix this but you will need to restore the file from a backup.
