### ISSUE TITLE
Dropping effects not working as expected

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#359]
Dropping effects on new sequence has random results. 

See
http://www.stevesimages.com/xl4/427-effects.mp4

**Comment by AzGilrock** [comment]
Yeah I can reproduce this.  As you know Dan did some major under the hood changes this release.  I tried to test and fix all the selection issues.  Looks like the one thing I missed testing was a single cell selection.  Multi-cell selections are working fine for that operation.

WANTED:  More beta testers that can build the code and use it before we release.

**Comment by stevegiron** [comment]
Just got Logan Moore set up to compile and test.

**Comment by kppankratz** [comment]
I'd love to help you test out the code before you release it to the masses.  I will have to work with Dan to get it set up on my Mac.

**Comment by AzGilrock** [comment]
The bonus is you get to use the new stuff before everyone else. :)
Yeah regarding this issue I think it's the second or third time the single cell selection has bit me.  I always forget the single cell selection goes through a completely different set of logic mainly because it has to do partial cell detection in case there is an effect partially intruding into the cell we allow you to select the remaining space.

**Comment by AzGilrock** [comment]
All that caused by one missing "!".
