### ISSUE TITLE
Crash during save in 4.2.9 

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#365]
Link to the debug report
https://www.dropbox.com/sh/eh47h87kckl0eva/AABhVywDazeT9_1X8gPpTsKha?dl=0

Crashed during save.

**Comment by dkulp** [comment]
"Could not find model or group named Snowman line".    

That's the root cause, but it definitely shouldn't be crashing. It's trying to render something against a model that doesn't exist.   (case sensitive.   It's "Snowman Line" in the model list)    At one point, when loading a sequence if a model didn't exist, we asked what to do with it (delete/rename).   Need to check what happened with that code.

**Comment by Clyde-L** [comment]
Dan I did select the "delete" option... I need to find where in my models I'm still holding onto that specific snowman line.  Working on that now.  Thanks for looking.

**Comment by Clyde-L** [comment]
Dan here is the debug screen shot while working with Gil.  This may help with finding the issue?

![screenshot 2015-09-11 12 54 49](https://cloud.githubusercontent.com/assets/12719816/9820825/7a41fabc-5884-11e5-9cfb-11c502971656.png)

**Comment by AzGilrock** [comment]
Yeah for some reason that strand layer object (slayer) is coming back as a null pointer.

**Comment by stevegiron** [comment]
Just working out my own crash with a different setup folder. If you don't have enough channels in your setup configuration. xlights will let you sequence to models, but saving will crash. Lesson learned!

**Comment by dkulp** [comment]
The "Snowman line" is in the "entire display" group.   But not causing this.   We aren't checking for invalid names in the groups.  Probably should.

Strange.   Any chance you can dig into the "mainBuffer" object to see the number of nodes?   The crash is in the "Windows Down" model.     There SHOULD be 9 nodes in that model according to the setup.   Thus, the three lines:

int node = it->first;
int strand = node / mainBuffer->GetNodeCount();
int inode = node % mainBuffer->GetNodeCount();

should be resulting in node=7, strand=0, and inode=7.   For some reason, it's getting strand=1 which implies the main buffer is wrong somehow.   No idea how that would happen.

**Comment by AzGilrock** [comment]
I'm working in Teamviewer with him now.  It's sounding like he used to have 9 nodes in that model and he deleted one node to move that channel to its own model.  So I'm wondering if the sequence still has data at the node level for node 9 which doesn't exist anymore.

**Comment by dkulp** [comment]
Yes.  That would do it.   I'll trap that and ignore effects on nodes that don't exist.  Certainly better than crashing.

**Comment by dkulp** [comment]
Actually, wasn't able to reproduce any crash even with reduced counts.  However, I did push some changes that I think will fix this.   Can you two give it a try?

**Comment by AzGilrock** [comment]
We didn't pull the changes yet but I did just have him redo the Import Effects because I thought there was a bug.  The sequence he was showing me had a lot of duplicate effects on top of each other at the node level.  The redo saved first try so I asked if he might have Imported twice and he said it's possible.  The sequence XML file is now about 8,000 lines shorter (42K vs 50K) and for some reason the fseq file is 50MB whereas the old one was 100MB so not sure why that file size would change.

**Comment by Clyde-L** [comment]
It would seem I may have imported data 2 times.   This second test file I created is now half the size of The XML file is now half the size of the original.  (from 100,792 KB down to 50,390 KB).  I believe I have irradiated the "Snowman line" issue.  I also added back in the 2 missing channels from the "Downstairs Windows" model. 

With this current test file, I have not had a crash while completing a save.  So this looks okay for now.  Huge thank you to Gil for all his help (3 hours) on the Teamviewer session today!  Also, thank you Dan for looking into all this.

**Comment by AzGilrock** [comment]
So I haven't seen a "Crashes on Save in 4.2.10" from Clyde so can we close all your issues with the word "crash" in the title? :)

**Comment by Clyde-L** [comment]
Yes, I have not crashed in a little while.

**Comment by stevegiron** [comment]
Per Clyde, this has been resolved.
