### ISSUE TITLE
Question: Channel count in generated fseq files

### ISSUE THREAD

**Issue by TheRealKasumi** [smeighan/xLights#3690]
Hihi,

I hava a question about the generated fseq files from xLights. But maybe let me give some context first. I am the founder of a small community project which allows to control a few WS2811/WS2812 strips for a car ambient light. One of its features is to upload an fseq file to the controller and play the animation on the LED strips. This is already implemented since some time and was working fine so far. However during a larger refactoring I noticed something that is confusing me a little now. So I would hope that someone could help me out here on the theoretical side.

First of all I should probably mentaion that this question is only related to fseq v1. Other versions are currently not supported by the project. So I configured xLights accordingly under preferences.

Looking at this [table](https://github.com/Cryptkeeper/fseq-file-format#structure) for the fseq header, I would understand that the `Channel Count` is... well the number of channels. So from what I saw in the past, the channel count is 3 for each WS2811/WS2812 LED. This makes sense I guess since each LED has 3 channels (r, g, b). For 2 LEDs, I assume it should be 6 then right?

So far everything was working quite well, following this logic. However today I noticed that when I create a single LED and generate the fseq file using xLights, I get a channel count of 4. At first I thought this would be a bug in my implementation so I rechecked in a hex editor. It is indeed 4. So I tried creating 2 LEDs. Channel count is 8 then. So I created 70 LEDs (length of my test LED strip). Looking at the channel count again and found 212. Created 72 LEDs, looking at the channel count and get 216.

216 / 3 = 72 LEDs -> cool
212 / 3 =70.666... LEDs -> wtf?

So since my logic doesnt to be correct I am curios what the channel count actually is. I mean 212 for 70 LEDs doesnt really make sense to me. No matter if I assume 3 or 4 channels per LED, it doesnt match. I would be really happy if someone could help me out here so that I can understand this number.

Best reagards,
Josi

**Comment by dkulp** [comment]
The channel count is always rounded up to the nearest multiple of four.  This is so that the individual frames can be memory mapped in and be properly aligned on a 32bit boundary on the Raspberry Pi/Beaglebone Blacks to help with playback.   With v2 files, this is not important anymore (compression means the channels aren't in continuous blocks or aligned anyway), but this was part of the design for running those files on the much slower/old Raspberry Pi 1 and 2 devices that were the main players back then.

FYI:  this is not really a github issue thing.   It should have been asked in the FPP forum at  https://falconchristmas.com/forum/index.php
