### ISSUE TITLE
Hinkspix - upload not setting Inputs correctly

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3692]
Can others verify HP Pro 2023.01 and 109 CPU
It is pushing an input of Universe 17,18,19

We tested first with 2 universes and it created 17 & 18. xLights needed 1 & 2 so we corrected it on Hinkx.
Then added another prop causing a universe 3 to be created. 
Uploading Outputs (preferences set to Linked) it creasted(?) a 3rd universe but as shown below it created universe 19.

![image](https://user-images.githubusercontent.com/4643499/213838246-57b46a78-de49-49cb-8c7b-6613c2156c88.png)
![image](https://user-images.githubusercontent.com/4643499/213839059-17a4e346-ba8d-44c2-9308-648474bb21bf.png)

**Comment by merryoncherry** [comment]
I noticed this.

You really need to upgrade the firmware on the HinksPix, for this reason and others.  I have noticed that the over-the-air update will fix it now, or you can download the FW from http://joehinkle.com/firmware/ and expand the zip file to SD and put the SD card in the HinksPix and it'll take care of it.

There are a lot of good reasons to upgrade to the latest HinksPix firmware... sort of my personal release notes:
    Firmware pre 113, new #929 boards: Smart receivers do not get configured. This is a showstopper if you have smart receivers.
    Firmware pre 114, new #929 and old #925 boards: Upload of the input mapping from some newer versions of xLights does not work. This is a showstopper.
    Firmware pre 117, new #929 boards: DMX signal timing is incorrect, and does not work with all DMX devices. This can be a showstopper if you have any DMX pars or the like.
    Firmware pre 117, all boards: DMX channels are off by one in DDP mode. This may not matter, as few use DDP.

**Comment by derwin12** [comment]
Wasn't 109 the supported version..short memory on my part I suppose. :)

**Comment by merryoncherry** [comment]
I'm just telling you my experience and how I managed to get my show to go.  This was a big adventure for me over the last few months.  If Scott can adjust his changes so that xLights keeps compatibility with 109, fine, but as of 114 the firmware has better performance and later versions have some other essential fixes for me so I'll be using 117 or 118.

**Comment by computergeek1507** [comment]
I have 118 on my controller, I don't know if I can find the old firmware to test.

**Comment by merryoncherry** [comment]
I think I finally upgraded my last old board the other day so don't have 109 either.  I do have 110 here in a zip file if you want it; it probably exhibits the issue also.  We could possibly get 109 from Joe.  Or revert to emergency FW on a board.  Or something.

But honestly, it's best if everyone upgrades FW.  The issue is that I don't know how you get the message out.  Rather than everyone getting confusing, unpleasant surprises.

**Comment by derwin12** [comment]
Okay that is fine .. I just forgot what the most recent versions were .. so
i was going on 109 being the later one last season .. I am sure that is the
issue here.

**Comment by computergeek1507** [comment]
> I think I finally upgraded my last old board the other day so don't have 109 either.  I do have 110 here in a zip file if you want it; it probably exhibits the issue also.  We could possibly get 109 from Joe.  Or revert to emergency FW on a board.  Or something.
> 
> But honestly, it's best if everyone upgrades FW.  The issue is that I don't know how you get the message out.  Rather than everyone getting confusing, unpleasant surprises.

I'll take your 110 zip for testing

**Comment by merryoncherry** [comment]
FW 110:
https://drive.google.com/file/d/1yJH2OG3OV3axjOXOgnLbIfJ5Pb4aV77l/view?usp=share_link
That is for the #925 or #929 board.

Sorry for the delay - long day.
