### ISSUE TITLE
Enh or fix black bar when palette rep is reached with spirals 

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#370]
Can the black bar be removed when the palette rep is reached and the palette repeats on the model?

![image](https://cloud.githubusercontent.com/assets/10568498/9974600/9e29fb64-5e4c-11e5-88b5-bcf88542d9b2.png)

**Comment by AzGilrock** [comment]
I looked at the render code for this and I'm not sure there's a concrete way to fix this.  It's all based on the math of how many slices fit within the size of the model and sometimes there is leftover.  But depending on the settings sometimes you have black bars in between the colors on purpose so it just makes the black gap slightly bigger in one spot.  Its just not clear to me what the logic would be to always know the best thing to do.  Imagine if you had just 2 spirals with big black gaps you surely wouldn't want a little sliver showing up just because one black gap was slightly bigger than the other.  Also it needs to be a change that doesn't affect existing sequences.
