### ISSUE TITLE
Enable flag on the Setup screen 

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#375]
1. Could you please explain how the 'Enable flag' on the setup screen is to be used (and what benefit it  has if unticked).
With no seq opened  , I went to the setup tab , selected a line and clicked  Change. The 'Enable' attribute was not displayed. But (accidentally) double clicking on the row  changed it from enabled Yes to No.  And double clicking changed it back to Yes. Clicked on the Output to Lights icon . Similarly Double clicking changed it either way. is this how it is supposed to work ?  

2. What does the One output attribute do and how is it to be set ? It does not seem to be enabled ie I cant tick it (tried selecting a row defined as multicast and clicking on Change)

**Comment by stevegiron** [comment]
Choosing one output will create one line item instead of X when adding E1.31 universes.  Here you can see 12 universes on a single line instead of 12 lines. It helps clean up the setup screen for weary eyeballs.
![image](https://cloud.githubusercontent.com/assets/10568498/10169252/1a9d959e-6685-11e5-9705-f84a4bcc4192.png)

**Comment by dkulp** [comment]
It also means that if you need to change the IP address, you change it once and not 12 times.

The "Enable" turns on/off that output when "Output to lights" is turned on.  If it's not enabled, not output occurs.   For example, if you have a controller not plugged in (testing a different controller) disabling that output would not attempt to send anything to that specific controller.   Trying to send data to a controller that is not there can cause weird delays (arp lookups and such) which can cause problems when trying to see if a controller that IS hooked up is working correctly.

**Comment by stevegiron** [comment]
For Enabled, imagine if you had your megatree and your mega-globe connected and you wanted to test. It's after hours, your megatree is outside and the globe is inside. You can test the entire sequence and by with no output to the megatree universes, it will not light up. From the comfort of your chair you can disable the output instead of having to put on the snow boots and go outside to unplug that controller, you can do it from your desk.

**Comment by gerry4** [comment]
Thanks, So the one output is only to be used when adding new setup entries .. (have understood and will document that).
Understood the benefit of the enable flag , but still don't see how it is to be set or unset (other than by double clicking on the definition line ). If i select a definition line on the setup tab and click Change , should it not allow me to change that value ?

**Comment by dkulp** [comment]
At this point, just double clicking.

**Comment by gerry4** [comment]
Thanks Dan
