### ISSUE TITLE
2023.05 Issues with models in layout

### ISSUE THREAD

**Issue by Teehouse** [smeighan/xLights#3766]

**Comment by Teehouse** [comment]
Random models will disappear when I rotate my layout in 3d. As I rotate it they will reappear the disappear again. I switched to 2d and a few of my models do not appear.

**Comment by AzGilrock** [comment]
Same issue reported 35 minutes earlier #3765

**Comment by Bugga36** [comment]
Same issue as reported above excpt I was in 2D mode.  Onlt two of 15 props showed in the layout.

**Comment by computergeek1507** [comment]
It Will be fixed in the next release

**Comment by kzaas** [comment]
Just to add something new to this issue after upgraded to 2023.05 all but one model disappeared from my preview. I use a 2D preview so I was pulling my hair out trying to figure out what was going on. I could click where the model should be and it would select it in the models list so I knew it was there, I just could see it. Then I selected 3D mode and my models showed up. Obviously since I didn't build the preview in 3D I couldn't use it in that mode also as Teehouse pointed out, as I rotated the display various models would disappear and reappear. So I went back to 2D and they all disappeared again. As computergeek1507 said hopefully this will be fixed in the next release.

**Comment by AzGilrock** [comment]
kzaas you're wrong about one point.  There is nothing about clicking the 3D button that would change a single thing when it comes to sequencing.  The rendering doesn't even know if you have that option selected and everything still renders as if its 2D for all of us unless you specifically select a camera preview in the Buffer options.

**Comment by Bugga36** [comment]
As you can see, the lyrics input screen pops up and I can input (type or paste) with no problem.

 

BUT, there is nothing to click on to transfer the text into the program.

It is simply a blank piece of paper.

 

I have used this tool many times before but something changed.

 

Thanks for looking into this!

 

Herb Campbell

**Comment by keithsw1111** [comment]
I think you have commented on the wrong issue and there is no image. To attach images you cannot use an email response.
