### ISSUE TITLE
Please add controller support for Hanson P28D Hat in 2 and 4 port DPI Pixels Modes

### ISSUE THREAD

**Issue by gergmchairy** [smeighan/xLights#3774]
In FPP v6.3 the Hanson Electronics HAT for Raspberry Pi has 3 output variants:

"rPi-28D"with 2 WS281x Outputs and 1 x WS280x Output.
"rPi-28D-DPIPixels" with 2 x WS2811 Outputs.
"rPi-28D-DPIPixels-4" with 4 x WS2811 Outputs.

Please could the Controller driver for the HAT be updated in xLights to match the options available in FPP.

Thanks

Greg

**Comment by anubis-code** [comment]
+1 on this please

**Comment by keithsw1111** [comment]
There is not a lot of information in this so I took a cut at it ... if it is wrong it is because this requests is missing information. I would prefer in future that such requests come as a pull request updating the xcontroller file as we have no access to these controllers or knowledge of the controller capabilities.
