### ISSUE TITLE
Clicking on "Sequence Settings" always triggers render and flags sequence as unsaved

### ISSUE THREAD

**Issue by smtpboy** [smeighan/xLights#3898]
**Describe the bug**
Entering in to and then exiting the "Sequence Settings" menu will force a render, even if no settings are changed.  This also causes the sequence to think it needs to be saved, again even if nothing has changed.  When you simply want to look at a setting this is unnecessary and incurs a big time/cpu penalty.  Happens with all sequences.

**To Reproduce**
- Open a Sequence
- Go to "File... Sequence Settings"
- Change nothing
- Click done
- Sequence will now automatically render and switch to an unsaved state, even if nothing has been changed.

**Expected behavior**
Render and/or Save should only be necessary if a setting has changed in this menu, and should never happen on it's own.

**Screenshots**
N/A

**Versions (please complete the following information):**
 - OS: MacOS X 13.4.1 (c) Ventura on Intel iMac as well as Windows 10 64
 - xLights version [2023.11] both Mac and Windows

**Comment by AzGilrock** [comment]
Yeah someone else reported this a few weeks ago and I looked at the Sequence Settings dialog code and there were cases when it should cause a re-render so I dismissed it.  I see the problem now.  We call AbortRender before showing the dialog and if a render was aborted it kicks off a new render when the dialog exits.  Problem is our AbortRender function is returning true when there wasn't any rendering in progress.  I need to check with @dkulp on this one cause that function is used in a ton of places.

**Comment by AzGilrock** [comment]
It was this commit that caused this behavior change: https://github.com/smeighan/xLights/commit/77f3c7235281772eee3c0b507e9dc5b856d70d0e

That change was to stop a crash that happened when dragging effect edges.  It seems like instead of returning whether a render was actually aborted it now returns true if the render queue is empty which is always true if no rendering was occurring.  I think it needs to change so that if abortCount = 0 it returns false.

Probably needs to be:
return (abortCount != 0) && renderProgressInfo.empty();
