### ISSUE TITLE
FPP Connect causing crashes (2nd time thru?) V7 and 2023.11

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3899]
From zoom on a mac (but seen before on windows). Couple of notes .. it was using proxy, it would usually show an error with 503 and resetflag.

After a restart it would work .. ie the fpp connect dialog shows up. Could just close it or upload, but the next time in it would crash.

Attached in one package logs but I expect there were numerous dumps uploaded to the appstore.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/12268364/xLightsProblem.zip)

jpappas113 at hotmail dot com

**Comment by derwin12** [comment]
Similar problem on windows..
![image](https://github.com/smeighan/xLights/assets/4643499/d54155a1-1c78-4032-b1ea-7da8749f5bac)

**Comment by dartunder** [comment]
I believe the second issue in Windows (this was my PC in the image above) is due to a non-standard network configuration, so this should likely be ignored, but this may be related to my other issue in that I can't specify a proxy address to upload outputs and FPP configuration but yet specify a different device as the device from which to send data.  

I think it would be cleaner to have both a proxy setting and a separate setting to specify which master or remote (FPP) device will be sending the controller its data.

**Comment by patdelaney** [comment]
I saw this error recently as well on Windows

Pat

**Comment by derwin12** [comment]
Assume this is no longer an issue .. if we can duplicate in newer releases, we can open another ticket.
