### ISSUE TITLE
Effects Applied to Groups, but as if the were individuals.

### ISSUE THREAD

**Issue by damon-atkins** [smeighan/xLights#392]
It appears from my testing that xlights does not support applying an effect to a group, which would be the same as if you copy and pasted the same settings to all elements in the group.

i.e. instead of creating a large vertial matrix.  Just apply the effect to each item.

Lets say you have a lots of mini-trees.
You want each one to say hello at the same time.   So they should all be displaying H, then e, then l etc,  at the same time, vs what seems to happen now you will get "Hello" spread across the mini-trees (sort of H on one, e on the next etc).

Cheers.

Groups within Groups support would be nice, especial if you support the above.

**Comment by stevegiron** [comment]
A group definition today is the combined X/Y coordinates of the members of the group to create a new soft-model. The grouped model (called a model group) then has the new dimensions of the combined elements. 

You'd like a method to play a single effect on more than one model at a time. Today that is done via cut/paste only.

**Comment by AzGilrock** [comment]
Long ago I could tell people would want this because a lot of users have made the mistake of thinking that's how the groups were going to work.  So I've put thought into it before.  The only way I can imagine this could be done is if its a global setting for the model group such that all effects on the model group work one way or the other.  Otherwise there would be no way to let the rendering routines know when to treat an effect one way or another.  So you would need to create two model groups with the same sub-models if you wanted to use both methods.

**Comment by keithsw1111** [comment]
You could either create a new concept ... ie not call it groups but say something like collections ... only challenge here is that neither name really hints at the difference in behaviour.

Also when it comes to rendering you would not want to pass in a flag to the rendering routine ... because it would require every rendering routine to change ... but also it is not necessary. When operating in the new state you would just call each rendering routine once per model in the collection rather than once for the overall group.

**Comment by stevegiron** [comment]
Hey Gil, think of how you may be able to implement a "Clone Group"
You'd pick members and a master of the group.
During render time, the effects on the master would get cloned to the members.

Until then, the Copy and Paste works too.

**Comment by damon-atkins** [comment]
I agree if you want both types of grouping you would need to create it twice.
Matrix Grouping vs Collection Grouping. Maybe use some sort of icon to show the difference.
Or maybe always create both and then a tick option to who which is display on the time line i.e.  show  just one or both.   For Matrix Group (with out reading the code) I can understand that the code would currently create a spacial matrix  for a group and then pass the information on to each effect.   Vs Collection Group which would "for each object apply effect settings to each individual matrix within the group (?including merging if an object already has an effect applied?)" 

With Collection Grouping, I would  place only groups on the time line and then expand the groups to if I want different effects on each item with in.  With Matrix Group I would not let it be expanded (or it no longer requires the ability  to be expand a Matrix Group if Collection Groups exist).

Thanks for thinking about this.

**Comment by AzGilrock** [comment]
You wouldn't need to pass a flag to all the effect render routines.  The flag would be inspected higher than that when looking at the model class object.  You really don't need to create a second special object the rendering code would just look at the model class and say hey this is a collection and spawn render threads for every model within the group instead of a single thread for the conglomerate object.  There's starting to be too much low level thought put into this here.  Once a developer dives in to implement sometimes all these ideas fall apart and it becomes clear how to do it.

**Comment by dkulp** [comment]
I was actually thinking that when we spawn a thread for a model as we currently do, we check the "groups" for groups that it belongs to and we grab the EffectLayer objects from the "group" and add them to the layers that the model renders.   That's "easy".  And all the blending would just work correctly.    All the code for iterating over the layers is there.

The problem it has is what happens when the model is part of multiple groups along with the current "matrix" model and we cannot really render them that way.

**Comment by AzGilrock** [comment]
Dan was wondering if this request was possible with the new buffer types code?

**Comment by dkulp** [comment]
Nope.  Although that could be an interesting new buffer type:  "Overlay Models"  where each model is overlaid on top of each other.  Hmm...    Basically, mutiple nodes would point to the same spot in the buffer.   Interesting idea.

**Comment by dkulp** [comment]
An "overlay" mode would work perfectly if the models are the exact same size.  (like 8 identical pixel minitrees or smiilar).   If they aren't identical, the question would be what to do about it.  Example, to pixels lines, one 50 pixels, one 40.   When we render, we would render 50, but for the line of 40, do we just use the first 40, the middle 40, or do we compress it (skip every 5th) to map the 50 down to 40.   I guess that could be 3 separate overlay modes.    Actually, another option is to render at 40 and expand to 50.

**Comment by AzGilrock** [comment]
Thinking about it more it seems like it would be better to be an option that was separate from the buffer types because otherwise you wouldn't be able to use the buffer types to alter an effect and have it apply it that way to multiple models in a group.

**Comment by dkulp** [comment]
Gil... you're absolutely correct.   I think the Buffer Style thing I added needs to be split.   There is the "how is the buffer created" setting and then a "transform" that should be applicable after that.   For example, right now, you cannot rotate a "Single Line" buffer, but there really isn't any reason why you should be able to do that.

**Comment by damon-atkins** [comment]
The idea is the same effect is recalculated for each object in the group. i.e. just loop through them and apply the sames settings.  So you might have a group called Trees, which might include small and big trees.  They would all be doing the same effect and looking the same, except for the size. Each loop of the effect for finish at the same time. i.e. they would look all in sync.  Thanks

**Comment by damon-atkins** [comment]
Has this been implemented by any chase in this years updates?

**Comment by AzGilrock** [comment]
This is implemented now.

**Comment by damon-atkins** [comment]
We were talking about this at the Mini the other day.  Thanks heaps and fantastic timing.
