### ISSUE TITLE
Twinkly import ignores the Z axis

### ISSUE THREAD

**Issue by degracode** [smeighan/xLights#3967]
Looking at the Twinkly custom import code:
https://github.com/smeighan/xLights/blame/dcfcf3a6610bd5928a4fde02a5c432c740c24fca/xLights/CustomModelDialog.cpp#L3239

I can see that it sets the Depth to 1, and then goes to calculate a good Height & Width size, leaving Depth at 1 and thus only producing a 2D Twinkly layout.

Is there a particular reason for not also calculating a good Depth dimension too? 

I'm happy to contribute a fix for this, but wanted to check if this had been attempted/aborted already.

**Comment by AzGilrock** [comment]
You would need to create a Custom model that has depth to do that.  I've got a new model that I was planning to provide a Twinkly import option for but it will be awhile before I add it due to other stuff I'm working on.  My model is basically like a PolyLine except every pixel becomes an editable point in 3D.  I'm calling it MultiPoint.  Only thing I'm worried about is performance.  I have a way to convert existing models to the MultiPoint model and when I converted a big megatree it wasn't very responsive when trying to edit points.

**Comment by degracode** [comment]
Is there a particular perf worry that you have with it? My day job is in C++ performance - perhaps I can help? Is there a fork/branch/PR with MultiPoint in it?

**Comment by keithsw1111** [comment]
The only reason i did not implement 3D was I dont think my unit at the time supported it ... or if it didnt i didnt notice it.

Supporting 3D would not be a difficult add with access to the right sample data.

**Comment by degracode** [comment]
Is there a way I can package up some sample data for you to experiment with?

The Twinkly app has two mapping modes - Easy and Advanced. The Easy mode produces 2D data, the Advanced mode produces 3D. Perhaps your device might support 3D mapping, but you had previously used Easy mode?

**Comment by keithsw1111** [comment]
I would need a sample response payload from the twinkly device. I dont have time right now to try to set it all up myself but if you get me the payload I am sure I could knock up the 3D custom model.

**Comment by degracode** [comment]
This is the json response from a /layout/full request for a quick arrangement
https://pastebin.com/QSWxJLeG
![image](https://github.com/smeighan/xLights/assets/7349637/4a67c8eb-df89-4106-8d1e-229b41846bc1)

**Comment by degracode** [comment]
Thanks @keithsw1111 for the quick turn around - I've just given it a go, and it looks great!
