### ISSUE TITLE
.13 and Pi 2 running 7.1 - unable to upload config

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#3979]
From Zoom.
 We tried "inactive" the serial and the alphapix, tried various things. View log only seems to show GET never a PUT or POST.
He can push sequences.
The PI seems to think it has a cape? - it shows Pixelnet/DMX on the outputs page.

2023-09-20 15:28:04,284 14776 log_base [INFO] FPPConnect GET http://10.0.0.155/api/channel/output/universeOutputs  - Return: RC: 200
2023-09-20 15:28:06,437 14776 log_base [INFO] FPPConnect GET http://10.0.0.155/api/system/fppd/restart?quick=1  - Return: RC: 200
2023-09-20 15:28:08,638 14776 log_base [INFO] FPPConnect GET http://10.0.0.155/api/system/info  - Return: RC: 200

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/12676895/xLightsProblem.zip)

Flat network, tried force local IP as check sequence shows multiple interfaces.

Nothing obvious in the calls to /info and /universeOutputs  (this returned something like channels 1-7)??

**Comment by computergeek1507** [comment]
Definitely need more information. Are you using FPP Connect, and/or is it setup as a controller? Are you setting Upd Outputs?

**Comment by derwin12** [comment]
fpp connect. udp set to all. fpp was not in controller list, but was later added as fpp player only. alphapix and genius set to active along with ctb16? lor thing on serial.

**Comment by Twiggy140** [comment]
Hey, all. So far I've tested a couple of things since getting home. I've upgraded to .14, with no change. Also took the SD card out, and booted it into a Pi4. No problems booting, the icon in the upper right changed to read Pi4, on the web page. Same issue trying to push the config from xLights. Next step is to get my other controllers powered up for the season, and try it with the field devices able to be reached from xLights. Let me know if you think of anything else you would like to know. Thanks!

**Comment by Twiggy140** [comment]
After getting my Genius and Alpha pix online, I attempted an upload, no success. Disabled the LOR stuff to be safe. Moved all my props around, performed controller output upload to both the alpha and Genius. Both worked fine, controllers updated and work in test mode as expected. I used FPP 6 last year, and may just see about reverting back to that image, to see if we can narrow down what is actually at fault. Still unclear if this is an FPP/xLights/networking issue, to me at least. Thanks!

**Comment by Twiggy140** [comment]
Tried 7.0, and 6.3. Both have the same results. I'm thinking I will try to roll back my version of xLights. This is the pi I used to run last years show, at V6.x FPP. I'll report back my findings.

**Comment by derwin12** [comment]
Create a small animation sequence - nothing in it. save it. then package sequence and upload that here. (similar to what you did in zoom but package sequence and not package logs)

**Comment by Twiggy140** [comment]
Hey, there. I believe I've narrowed down the issue to a change made in version 2023.13. I went back to 2022.20, and it worked like a charm. Worked my way up and found that 2023.12 works perfectly with FPP 6.3. As soon as I move back to 2023.13, the issue presents itself again. For now, I just won't move past .12. Would you still like me to make a small animation sequence and package it for you? Tomorrow I will get the Pi back to FPP 7.1 and verify everything still works. Thanks again for all of your help today!

**Comment by derwin12** [comment]
I think it would help them duplicate the issue.

**Comment by Twiggy140** [comment]
So, I spent a lot of time playing around today, and can no longer recreate the issue. I upgraded my pi from last night running 6.3 to 6.3.2. Then to 7.0, and finally to 7.1 using the automatic update on FPP. Each time checking with version 2023.12 for functionality. I was able to upload my config on all versions. I then decided to upgrade xLights to 2023.13 to have things "break again." Oddly enough, when I put .14 back on my machine, I am now able to push my configuration from xLights to FPP on a Pi2. I'm stumped as to the reason, but considering the resolution, it may have been a bad install of .13/14 on my machine, and uninstalling/reinstalling worked. I've packaged the test sequence and posted as requested. Though, it appears that I won't be able to run anymore tests, since I can't recreate the issue now. I've tried downgrading the FPP with a flash from the image used originally as well as downgrading xLights, with no luck reproducing. Please let me know if I can be of any other help. Sorry to drag you on a seemingly wild goose chase for a bit! [](url)
[Test.zip](https://github.com/smeighan/xLights/files/12689216/Test.zip)

**Comment by derwin12** [comment]
No longer an issue with update...
