### ISSUE TITLE
(semi-)standard submodel names

### ISSUE THREAD

**Issue by djulien** [smeighan/xLights#4033]
**Is your feature request related to a problem? Please describe.**
(This is more of an xLights 2024 suggestion, not necessarily for 2023).  The built-in xLights models will display the various effects in a predictable way, but custom models often look a little strange with some of the effects.  A common work-around is to create submodels, put those submodels into a group in a specific order, then apply the effect to the group using "single line" render (so the submodels are used in a specific order).

**Describe the solution you'd like**
The need for an extra group and using the single line render order could be avoided if xLights recognized "standardized" submodel names.   For example, maybe something like _row0, _row1, ..., _column0, _column 1, ... or (particularly for round spinner-like props) ring0, ring1, ..., spok0, spoke1, ...

**Describe alternatives you've considered**
(the submodels, group, and render order work-around described above)

**Additional context**
For round/spinner-like custom models, I suppose an alternative would be to add a "Keep Phi and Theta" choice in the Buffer Style drop-down in the Submodel panel, and implement some type of polar coordinate grid in addition/instead of the rectangular grid that's already there.

**Comment by computergeek1507** [comment]
You can make a Submodel for legs, set it to a vertical buffer, set each Submodel row to each leg and it will spin like the spinner model if you use the single line effect. Similarly you can do this for the rings just without the vertical buffer option. The real problem is the lack of understanding of Submodel/Subbuffer layout by the people who make the custom models and the "professional" sequencers. They found that groups work and did it instead.

**Comment by djulien** [comment]
Okay, I'll use the "correct" way.

Hopefully the sequence vendors will switch in future.
