### ISSUE TITLE
Dont allow a shadow modelled model to be placed on the visualizer

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4072]
If a model has been pointed to by "shadow model for", then don't allow it to be placed on the visualizer. Trying to avoid folks shadow modelling a prop and then trying to place the original model on to the visualizer (as well).

**Comment by dartunder** [comment]
I believe there are odd cases where you can use a shadow model explicitly in order to duplicate a model's outputs on a secondary port.  

While not normal, I don't think we should prevent this, but I see adding a warning to the visualizer and checking the sequence.  

Also, we can set the "shadow model for" setting but there is no warning ( in check sequence or elsewhere ) that the pointed-to prop does not have the start channel set correctly ( or even set at all )

**Comment by dartunder** [comment]
@derwin12 

I put in a PR that displays a model in light grey if it has a shadow model.
It also displays a warning if the original prop is played on a port.  This is allowed, but just a warning.

https://github.com/smeighan/xLights/pull/4078

**Comment by dartunder** [comment]
@derwin12 Please close this.
completed via https://github.com/smeighan/xLights/pull/4078
