### ISSUE TITLE
.18 Crash on render of what appears to be liquid effect

### ISSUE THREAD

**Issue by derwin12** [smeighan/xLights#4073]
From Zoom (Scott & Keith are aware)
Same effect on different groups -- remove from the 2 in the crash log and it renders. Add back a copy from another model and it crashes.
N-BottomRoof
N-TopRoof

Note MINI-Bulbs-ALL gets stuck on the liquid but would eventually finish.

https://www.dropbox.com/scl/fi/tmqzwdbgnqg4sq1s4hiot/carrie-underwood-john-legend-halleluja.zip?rlkey=gcdeyz6ryp09uzc1eull2qho0&dl=0

Logs were submitted -- likely from the 21st and 22nd from "Keith Rush"

![image](https://github.com/smeighan/xLights/assets/4643499/5a33f3fa-35ba-4668-be16-338fea069a81)

**Comment by derwin12** [comment]
Here is the crash log from my attempt at rendering..
[xLights_dbgrpt-3348-20231022T134425.zip](https://github.com/smeighan/xLights/files/13064092/xLights_dbgrpt-3348-20231022T134425.zip)

**Comment by robfallone** [comment]
I'm able to reproduce a crash on my system within the referenced LiquidEffect. Not sure yet if its is the "same" crash. It seems to be running out of memory. I have not gotten to the bottom of it yet but still looking.

**Comment by keithsw1111** [comment]
I have reproduced the crash but it is deep in the allocator within Box2d ... I am not sure it is even fixable by us ... but i am still looking.

**Comment by robfallone** [comment]
After recompiling Box2D locally so that I can debug it, i get the following call stack which shows that we are overflowing signed 32-bit. That is **a** problem but not **the** problem. I'm suspecting some kind of infinite loop, memory leak or both. I'm still digging trying to identify why there is a request for such a large buffer to begin with.
![image](https://github.com/smeighan/xLights/assets/29558143/5d45ca01-68c3-4ba1-9424-ff0e3edeead9)
