### ISSUE TITLE
Layout Screen Locking models

### ISSUE THREAD

**Issue by Blickensderfer** [smeighan/xLights#4100]
In previous builds in the preview screen you could select all your models and right click and lock.  It didn't matter if some of the models were already locked or not, It would lock the models that were not locked.   I noticed in 2023.19 that when I try to lock by selecting everything that the "lock" option is grayed out and not selectable.  Will this feature be returned.  It's easier to lock when you have a very dense layout and trying to get the props locked.

Thanks,
Dan

**Comment by Blickensderfer** [comment]
![image](https://github.com/smeighan/xLights/assets/20225988/03ec3168-3f7d-4958-862c-b562447db7c7)

**Comment by dartunder** [comment]
FYI: 
The behavior when right-clicking on the models in the table vs the preview is different.
The behavior in the table is more logical.  It allows lock if any model is not locked.  The behavior of right-clicking a model in the preview window depends on the closed status of the first selected model.

**Comment by AzGilrock** [comment]
It looks like it was always enabling the Lock option based on the selected effect because that is coming from the "Single Model" options.  The recent change is that it will not enable the Lock option if the selected model is from the Base layout.  I'd be hesitant to try to make the menu too smart because some folks have a huge number of models so it would have to loop through all of them just to try to figure out whether to grey out an option.  Seems like a quick work-around would be just select the Unlock then right-click and select Lock.

**Comment by dartunder** [comment]
Yes, but the behavior is different if you do the same from the table on the left.

**Comment by AzGilrock** [comment]
Well I'll log that under things that don't bother me much...lol
