### ISSUE TITLE
split 's' hotkey broken, functions as new timing 't' hotkey

### ISSUE THREAD

**Issue by PhilHilton** [smeighan/xLights#412]
4.0.1 release notes:
"-enh (Gil) Add ability to split timing marks #88"
"Some new features: Click in the waveform and the type "s", the current timing mark will be split in half. This complements the "t" command that creates timing marks."

1.2 Manual seems to back this up. Though one says click the timing mark (makes sense), and the other says click the waveform (makes less sense).

In both cases, I find the 's' key only creates a new timing mark at the time clicked in the waveform, and does nothing when a timing alone is highlighted. It seems to have the same functionality as the t key.

Currently using 4.2.18

**Comment by AzGilrock** [comment]
It's working as expected.  The problem is you think a timing mark is the vertical line and it's not.  A timing mark is the horizontal line between two vertical lines because a timing mark is a duration with a start and an end.  So if you have 2 timing marks with the first one from 1 sec to 2 sec's and another starting at 2 sec's to 3 seconds you will see 3 vertical line but you do not have 3 timing marks you have 2.  You place and split timings by clicking in the waveform to select the position where you want to place or split the mark.  So when you select in the wavefrom between 1 second and 2 sec's and hit "s" it splits it into 2 timing marks one from 1.0 second to 1.5 seconds and another from 1.5 seconds to 2.0 seconds assuming you clicked the 1.5 second mark in the waveform.  So you're seeing the one new vertical line and thinking it inserted a timing mark but it actually split the existing one into 2.

**Comment by PhilHilton** [comment]
Thanks Gil.  I did understand timings to be a range/duration rather than a single point in time. I believe that my confusion stems from, what I consider, duplicated behavior. To clarify - Is there any difference between t and s other than s can not create a timing mark where another does not already exist? Because t seems to split existing timings the same way that s does, which would make s redundant, and is what lead me to believe the intent of s must therefore be to subdivide equally, as t appears to be able to "split" already.

**Comment by AzGilrock** [comment]
Split was initially added to create a gap in the middle of an existing timing.  So if you drag out a range in the waveform that's within a timing mark and hit "s" it will create a gap in the middle of that timing.  It didn't make sense for "s" to do nothing if it was a single point in time instead of a range selection so I made the code execute a "t" operation if you hit "s" and there's not a range selection.  So "s" was actually meant for range selections in the waveform.

**Comment by PhilHilton** [comment]
Ah there it is. The gap. Never considered a need for such a thing. Thanks. All is clear now. My apologies for taking up your time.

**Comment by AzGilrock** [comment]
And as I think back I believe what happened is initially if you hit "t" in the middle of a timing mark it gave an error which became annoying so I made it so that hitting "t" without a range selected causes a split operation.
