### ISSUE TITLE
Sequence Element Mismatch in Bulk Render not saving correction to sequence

### ISSUE THREAD

**Issue by OnlineDynamic** [smeighan/xLights#4182]
**Describe the bug**
If you run a batch render and a sequence hits an issue related to a model mismatch you get a dialog called "Sequence Element Mismatch" which allows you to fix the issue by mapping to a different model, deleting the reference or rename the element.  The batch render then continues but the changes made don't seem to get saved so you hit exactly the same issue on next batch render

**To Reproduce**
Create a sequence with a few effects on a few models. Save. Then change the name of one of the elements in the layout whilst you have a different sequence open.  Then run batch render.  The origin sequence will error as described above.  You manually correct in the pop up dialog. but if you run batch render you will hit same issue

**Expected behavior**
Corrections made during the batch render to be enduring

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2023.20

**Comment by keithsw1111** [comment]
This is not a bug. But intentional. Saving a change permanently at a time when you are really not in the best position to make that judgement would be a big mistake.

On 2 Dec 2023, at 11:31 am, OnlineDynamic ***@***.***> wrote:

﻿

Describe the bug
If you run a batch render and a sequence hits an issue related to a model mismatch you get a dialog called "Sequence Element Mismatch" which allows you to fix the issue by mapping to a different model or deleting the reference. The batch render then continues but the changes made don't seem to get saved so you hit exactly the same issue on next batch render

To Reproduce
Steps to reproduce the behavior:
Create a sequence with a few effects on a few models. Save. Then change the name of one of the elements in the layout whilst you have a different sequence open. Then run batch render. The origin sequence will error as described above. You manual correct in the pop up dialog. but if you run batch render you will hit same issue

Expected behavior
Corrections made during the batch render to be enduring

Screenshots
If applicable, add screenshots to help explain your problem.

Versions (please complete the following information):

  *   OS: Windows 11
  *   xLights version 2023.20

**Comment by dkulp** [comment]
We should have batch render skip (and then report) any sequences that could not be loaded "cleanly".

**Comment by keithsw1111** [comment]
Changes to sequences will not be made during bulk render. It is not appropriate. This is final.

What I have done is add the concept of model aliases which are auto added when you rename a model (as long as you agree to it). If you then open a sequence (including during batch render) and the alias exists with the old name then xlights will auto map the model without prompting ... this should eliminate most of these scenarios.
