### ISSUE TITLE
Enhancement: Set Low-end of 3D Fade options

### ISSUE THREAD

**Issue by ghost** [smeighan/xLights#426]
Probably most applicable to the single strand effect, but others as well (spiral?). It'd be awesome if I could specify the low end intensity of the 3d Fade option.  

Mega tree with Number of Chases = 2, Chase size 50, left-right, single color in palette selected

With these settings the chase reaches 0% intensity just as the next one comes around. I'd rather it never go lower than 25%. Intuitively I would expect setting my chase size to 75% would accomplish this as the next chase coming around should "overrun" the one fading out about the time it gets down to 25%, but instead the chase coming around is actually dimmer to start with (looks like it's being averaged with the one ahead of it, not sure).

Maybe just "fix" (not sure if this is a bug or by design) the chase size affecting the next chase coming around if it is set higher than (100 / number of chases)?

**Comment by AzGilrock** [comment]
Just remember when you suggest a change that it can't be something that's going to modify how everyone's existing sequences look unless we have a strong argument for it.  A lot of people have spent a lot of time designing the look of their effects and don't want us to do a release that changes the look.  So we can add additional options much easier but even that has a downside because it starts to clutter things up with too many options and there is a lot of overhead for every option we add to an effect.

**Comment by AzGilrock** [comment]
Pretty sure this won't get incorporated and I believe you can achieve the same thing using color curves in the effects now.
