### ISSUE TITLE
Changing duration of sequence, no longer able to see past current window

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#439]
When changing a sequence time from 30 seconds to 90 seconds (example). Can no longer use the Zoom In / Zoom out features to see past the 30 second mark. 

Saving the sequence and then re-opening allows you to see the entire 90 second sequence.

**Comment by PhilHilton** [comment]
Can I ask why this was filed under enhancement instead of bug without offending someone?

**Comment by stevegiron** [comment]
Since this is more of a "The application doesn't work the way I expect it
to" type of notification, the interpretation is that the request is to
alter the code so that the application has a workflow the way the user
requests. THAT is an enhancement request.  Every code change has
dependencies that may affect subsets of code.

All the developers see all the requests regardless of classifications. This
year we saw many closed before they were even classified. With a very small
volunteer developer network, the priorities, time spent, issues chosen, are
all at the free will of each developer.

**Comment by LightsOnHudson** [comment]
Hmm. Didn't mean to pull this type of response out of anyone. It simply was functionality that when you adjusted the timing, other functions no longer function. If this is a workflow topic, then ok, i accept an enhancement. If it was intended as such, I accept it.
There is a work around that allows for the behavior that i would like.
Thanks for looking into it.

**Comment by PhilHilton** [comment]
I didn't ask in order to question the issue's priority or developer resources available. I don't.

I asked simply because I didn't think it was the intended behavior for the zoom features to stop working when a sequence length is changed. In all of my development work, if a behavior is unexpected and/or un-intended, it's categorized as a bug. 

Though I guess fixing bugs can be categorized as an enhancement ;)
