### ISSUE TITLE
Snowflakes won't swirl unless you accumulate 

### ISSUE THREAD

**Issue by tmblue** [smeighan/xLights#450]
it's better to use meteors for snowflakes since you can make them swirl (move right to left (sort of random), where as snowflakes if you are not accumulating will fall right to left, no random no swirl).

I think the default for snowflakes is they should fall more naturally like they do when you click accumulate, but one doesn't  always want to accumulate.

**Comment by AzGilrock** [comment]
I've found the swirling changes based on the size of the model you put the effect on.  I have snowflake effects that do look like they are swirling.  I'm sure it was working for whoever created the effect they just didn't realize it didn't work on other sizes.  A different developer added the accumulate option and he noticed the same thing so he fixed for the accumulate option but he was reluctant to change the base behavior because it would change everyone's existing sequences.  Imagine if you have a sequence and are happy with how it was looking and then we do this logic change.  You are now happy and several existing customers might be upset.

**Comment by keithsw1111** [comment]
Gil is correct. I wrote the accumulate addition. I didn't want to break anyones existing shows so when I added accumulate I was very careful not to change the existing behaviour. This means it only swirls for accumulate.
If you wanted I could try to find a way to add swirl but dont accumulate.
Keith

**Comment by tmblue** [comment]
That would be awesome if you could, I love the more natural snow fall
pattern when it's set to accumulate, but on my matrix I don't want it
necessarily to accumulate.

Also I can't see how anyone would say ya that breaks my show, I mean snow
fall from right to left, vs a natural fall.. But ya would be nice to have a
switch or something.

Thanks guys!
Tory

**Comment by keithsw1111** [comment]
Next version will include swirling snowfall without accumulation.
