### ISSUE TITLE
Arches Set up problem 

### ISSUE THREAD

**Issue by Bevo1** [smeighan/xLights#454]
I have found with setting up arches if you select the start point from the right, the arches do not get data sent out in the right direction as in the visualizer.

If you have time to see if you can make this work it would be great.

If you watch the start of my video the two front arches and the back two on the left and you will see what I mean.

Thanks.

[https://vimeo.com/147931328](url)

**Comment by AzGilrock** [comment]
Ok for one your video link isn't working for me.  I did a test where I created an arch that was defined bottom left and I put a morph on it that moved left to right.  I went into the model definition and changed it to bottom right.  When I went back to the grid the house preview now shows the morph going from right to left which may appear to be incorrect but that was only because I had not re-rendered the data.  By clicking on the effect the morph switched back to moving from left to right like it should.  So my question to you is did you do a Render All or a Save with render turned on after you switched the model definition?

**Comment by Bevo1** [comment]
Hi,I have re-rendered after changes, but the actual out signal to the physical lights is not working correctly.
I have done saves after the changes and when I re open the model settings they are as when I saved them with the changed start points.
Try this link https://vimeo.com/147931328


Date: Sun, 31 Jan 2016 13:05:50 -0800

**Comment by AzGilrock** [comment]
How many arch models do you have to represent those front 4 arches?  I've never had an arch model with "# of arches" greater than 1 so I'm wondering if that's what you're using.

**Comment by Bevo1** [comment]
Sorry for not telling you the full set up.
Front arches are set up by 2 universes ( 2 arches each set, two start points in the center near the RGB tree) and the ones near the strip tree are also on two separate universes but on their universe they also have a spinner and candle and they both have start points from the center near the strip tree.
And I have set up each model of arches as two arches.
I hope this helps.

Date: Sun, 31 Jan 2016 16:32:10 -0800

**Comment by AzGilrock** [comment]
Ok so maybe we have a problem when you use # of arches greater than 1.  In my opinion I would never model my arches that way.  If you model each arch as its own model you probably could go forward without an issue.  But we'll keep this open to look at someday.
