### ISSUE TITLE
Engage xLights dev team in order to participate in code development

### ISSUE THREAD

**Issue by SteveGase** [smeighan/xLights#470]
For now I'm interested in getting my feet wet by creating a couple effects.  I've got a couple in mind and would like to slowly introduce them one at a time and get feedback from the team on process and best coding practices.  If this goes well, maybe I'd stretch my wings further by helping in other places.

I noticed another check-in that suggested that "normally" new people get in contact with the team before making changes to the core code. 

I'd like to initiate that communication... how can I get plugged in, and what's the next step?

I've built the code, installed SourceTree, created a branch, committed changes that add a new effect - but the unique logic is not yet written.  (just a copy of Bars).

I'm new to Code::Blocks and git and Github... so I will need someone to look over what I do to prevent unanticipated breaks.  Thanks!

**Comment by AzGilrock** [comment]
Sean is usually the gatekeeper for adding new people to the developer communications.  You know he's busy watching like 20+ forums and getting prepared for the seminar in April so if you email him directly it may speed up him noticing your interest.

**Comment by SteveGase** [comment]
Here are some effects that I'm considering...  please provide feedback on value, and improvements:

"Qix" subdividing the matrix by creating a rectangle by drawing a randomly-placed line horizontally or vertically across the available space... the rectangle is painted the "next" color, and the remaining space has the the same rule repeated until the original matrix is filled.  Options: adjust the min width of a rectangle, max width of the rectangle, the size of the remaining space before the image is wiped and it starts again, the selection of 3D edges, ...?

"Snake" like the old PC game, draw a snake that changes direction as it encounters an obstacle.  Multiple colors would exist on separate "planes" such that plane #1 would have color #1, plane #2 would have color #2, etc.  Options: number of snakes on a given plane, width of a snake, length of a snake, 3D edges, ...?

"Kaleidoscope" with a triangle (region) drawn to some pattern, and then mirrored and repeated around a central point.  Options: pattern selection for the first region, moving center point, number of segments (mirrors)

"Raindrops" round spots that get randomly placed on the matrix, drops are random sizes, colors are selected from the pallet.  Options: circles, squares, triangles, or mixtures of each.  min shape size, max shape size, number of shapes before "wiping" to start over with a clean canvas, life span: dim objects based on age util they are no longer seen.

**Comment by AzGilrock** [comment]
I'm not good at guessing what users will want.  I think a lot of these fall into the category where they are good ideas but sometimes don't come out that impressive on the low resolution display elements we tend to use.  The may be suited well for larger P10 matrices.

**Comment by keithsw1111** [comment]
One thing to think of is that most effects are not put onto matrixes but trees, candy canes, house outlines, and the whole house etc. Several of these are not likely to be all that useful outside the matrix use case. That doesn’t make them invalid but I would be looking at each of them and asking how can I make this effective on these other models or model groups.

Using this lens …


-          Quix potentially works as it displays large blocks

-          Snake … works if you let the snakes get really thick … otherwise they get lost in the gaps when applied to whole house.

-          Kaelidoscope … works but only if it scales up with model size such that your triangles get large

-          Raindrops … only works if you let the drops or objects get really large … and even then the effect is probably lost outside the matrix use case.

For the raindrops one that is really just a special case of the madrix S2L effect where shapes like squares, hearts (or your raindrops) are randomly placed on display … in the madrix case their placement and placement frequency is influenced by the music playing. You could optionally do that in your effect. I chose not to do this one because I couldn’t see it working outside the matrix use case and that seemed too limited.

**Comment by AzGilrock** [comment]
Closing this since I believe you and Sean made contact.
