### ISSUE TITLE
Bug: Mac click effect get ID_CHOICE_BufferStyle

### ISSUE THREAD

**Issue by jeffla** [smeighan/xLights#490]
Running latest pull from Xcode on Mac. This started happening about a week or two back. Seems like 2 additional colors were added to the palette?

https://vimeo.com/158138108

On effect top layer, twinkle effect 2nd-layer. Click an On effect and a previously-selected effect clears the selected color and resets the morph. Tried selecting a known bad effect first, cleared the alert and selected again and the program stopped on __tree line 126
```
// Returns:  pointer to the left-most node under __x.
// Precondition:  __x != nullptr.
template <class _NodePtr>
inline _LIBCPP_INLINE_VISIBILITY
_NodePtr
__tree_min(_NodePtr __x) _NOEXCEPT
{
--> while (__x->__left_ != nullptr)
        __x = __x->__left_;
    return __x;
}
```

Can I get past this by editing the XML file for the sequence directly?

**Comment by AzGilrock** [comment]
That usually happens when we've deleted an option from an effect and your xml has the old stuff.  We usually try to have code that fixes these when we detect the xml version is older than the current version but if you've been pulling your own code instead of running official releases you may run into this because of the intermediate state of the code when you do a pull.

But anyways what I see in that video is you click on an effect that has a problem.  When you clear the popup you aren't doing anything to fix the effect you clicked on you keep clicking back on another effect.  After you clear the popup try hitting the Update button because that should fix all the tags for the currently selected effect.  Hitting Update forces it to write the effect with the current settings.  Then you can go back and fix up the other effect.  If its a lot to fix then I'd fix one and diff the XML to see what changed and then you can see how to fix the others.

**Comment by jeffla** [comment]
@AzGilrock That worked. Thanks!
