### ISSUE TITLE
View WIndow and Model Group Crash

### ISSUE THREAD

**Issue by deplanche** [smeighan/xLights#494]
When I am selecting a View in the Sequencing Tab, I am getting a crash anytime I select a view other than the Master View and then double click to expand a model group.   I can expand the model group without problem if I don't select a view at all, or select the Master View, its only after choosing a different view that it crashes.  

A screen capture of the problem is here: https://youtu.be/xm4V0xomu54

The crash files are attached (if I did this right)

Let me know if you need any other information.

[xLights_dbgrpt-3760-20160311T232714.zip](https://github.com/smeighan/xLights/files/170263/xLights_dbgrpt-3760-20160311T232714.zip)

**Comment by AzGilrock** [comment]
Somehow you deleted models from your layout but they are still listed in the "Roof" view.  If you created a new View you wouldn't have a problem or if you edited the XML to fix it by deleting models that don't exist it will work like make it:
  <views>
    <view name="Roof" models="Roof,Roof Chase"/>
  </views>

instead of:
    <view name="Roof" models="Roof,Roof Chase,House Front,Door,Garage,Roof Multi-Lights,Sign"/>

Are you using any older files?  We used to have a bug that could cause this but you shouldn't be able to get yourself into this situation with today's code.

Here's a correct file that will work.
[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/170614/xlights_rgbeffects.zip)

**Comment by AzGilrock** [comment]
Well I guess GitHub deleted the XML I posted so just look at the file I attached.

**Comment by deplanche** [comment]
I was using last years files and getting rid of some stuff that I am changing this year.  Probably best just to start a new file and copy the few layouts that I need rather than trying to delete things.  

Thanks
