### ISSUE TITLE
Paste by buttons don't always toggle

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#529]
I was testing the new past by time / paste by cell buttons and found you can have both selected at the same time and wonder which one is active.  Similar to #527 

![image](https://cloud.githubusercontent.com/assets/10568498/14446070/deccbdbc-0006-11e6-89d2-6b516b849b82.png)

**Comment by AzGilrock** [comment]
I saw you demonstrate this for #527 but I can't duplicate this on my system.  Not sure how to fix it because there is no bug in that code.  The event handling code sets both button states at the same time as shown below so you tell me how one works and the other doesn't.

void xLightsFrame::OnAuiToolBarItemPasteByTimeClick(wxCommandEvent& event)  
{  
    ButtonPasteByTime->SetValue(true);  
    ButtonPasteByCell->SetValue(false);  
    mainSequencer->SetPasteByCell(false);  
}

**Comment by stevegiron** [comment]
Both buttons selected is not a bug. It's a random unexpected feature.

**Comment by AzGilrock** [comment]
Well I wasn't saying there isn't a problem because I witnessed it on your machine.  Be curious to see if others start running into it.
