### ISSUE TITLE
2016.19 Effect, Color, Layer Settings Popups

### ISSUE THREAD

**Issue by Phrog30** [smeighan/xLights#530]
1.  If you open the popup with the toggle buttons on toolbar, then close with the "x" on the popup, they won't open again from the toolbar.  I was able to load saved perspective to get it back working.
2.  The toggle buttons highlight to show the popup is opened, however, if you close with the "x" the state is not updated.  The layer setting and layer blending toggle buttons do not highlight like effect setting and effect colors.
#2 is obviously not important at all, just an observation.

James

**Comment by stevegiron** [comment]
Linking to #520 and #525

**Comment by AzGilrock** [comment]
This is why its bad to put two different ideas in one issue.  The first one is fixed but the second one is an enhancement.  For the second one I'd love to update the icon highlight but as of yet we haven't found a way to intercept the event when a floating popup panel is closed.  We've been trying in order to fix the focus issue when you close a panel and it jumps focus to another application.

**Comment by Phrog30** [comment]
You mention this is why it's bad... what is this?  The button and it's feedback are within the same "system".

**Comment by AzGilrock** [comment]
Its 2 different problems that have nothing to do with each other.
