### ISSUE TITLE
Timeline issue when using DMX FX, clicking an effect may disable the output, until you "tickle" the effect. wxWidget tool? 

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#540]
Create a audio sequence, add some manual timing marks.
Add some effects.
Play it and it looks OK.
Mouse click on one of the color effect and then try and play again and now that effect is not present.
Fix is to click the effect in the timeline again to get to come back.

See YouTube video:
https://youtu.be/ma_atya4DDY

Pat Delaney

**Comment by patdelaney** [comment]
I would like the priority raised. It has the potential for data loss. My example only displays 3 models. Lets say I have 200 models. If this issue reappears as I'm working on my sequence I may never see it if I am working on the mega tree for example. Let say while scrolling I accidentally touch an effect on the timeline and now that effect is not outputting. When I'm working on my sequence, I'm not looking at the model that accidentally just got broken. The UI looks correct, but the actual output is missing. You may actually never notice that data is missing if you don't watch the output. I think this needs to be investigated and fixed asap. I don't think just hitting the Render button fixes the issue.

**Comment by AzGilrock** [comment]
This really has nothing to do with the DMX effect.  It's the basic way the entire engine works.  If you click on an effect in the timeline it will write that data to the outputs.  So if your DMX model at the top of the grid overlaps the channels that the RGB portion of the DMX model maps to then clicking the top effect will send out whatever you have the sliders set to for those channels.  We don't render everything underneath the effect you click on.  That only happens when you hit Save or Render All.  An example of this is drop a Butterfly effect on a model group and then drop a bars effect on one of the individual models within that model group.  Assuming you have the render order setup with the group on top then clicking the butterfly effect in the grid will show the butterfly on everything.  Then if you click on the bars effect it will write that data to just that one model so everything will show the butterfly but that one model.

**Comment by patdelaney** [comment]
Ok I got it, user error, I'll look at the models again. But out of curiosity Lets say I create a single node effect (3 dmx channels) I only need 1 DMX channel to control over-all intensity of the output of the moving light. If I set the dropdown box in Effect setup to "Use 1 channel" what happens to the other 2 channels? Are you ignoring them or are you writing 0's out. Just thinking of the workflow that you have described if I have models with overlapping channels.

**Comment by AzGilrock** [comment]
Yeah it should ignore them.  That was the main reason I had that option.  I really want to see if I can get the effect working with the single color node option then you could create a 1 channel model or any other size.  I couldn't actually hear audio in your video from where I'm at so I'll have to watch this tonight to see if it's really a problem.  But my guess is its a rendering order thing.

**Comment by AzGilrock** [comment]
So watching the video and at 1:39 when you stop the playback and click on the top effect for the Motion row that had to have written zeroes to the color channels and then clicking on each color effect refreshes the data for those effects.  But you stated that the first model was only 1 node and was running channels 1 and 3.  Then you said the 2nd model was for the RGB but I don't think you mentioned which channels you mapped it to.  The 3rd model you said was channel 6.  Well that doesn't all add up because there are only 2 channels between 3 and 6 so not enough for your colors.  I really need to see all your model definitions for this to really know what's going on.  Did you really mean that first model was running channels 1 and 2 and the colors are 3, 4, and 5?

**Comment by patdelaney** [comment]
The video was made before your explanation of how it was supposed to work. I when back and checked the models and corrected the channel counts to avoid overlap. Once I did that the issue was resolved. Thanks for looking at this. I will try to do more testing of the moving heads and hope to have a demo sequence done in time for the Expo.

**Comment by AzGilrock** [comment]
Ok cool.  I do have a couple enhancement ideas for the DMX effect but I've got a couple things to knock out first that are non xLights related.
