### ISSUE TITLE
Multi-cell "Paste by Cell" Issue

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#549]
2016.22
If you have the "Paste by Cell" option selected and you paste a copied cell into more than one cell, it actually uses the "Paste by Time" option.  Coping and pasting using the "Paste by Cell" option for a single cell works correctly.

Thanks
Denny

**Comment by AzGilrock** [comment]
Paste by Cell and Paste by Time is not even looked at when dealing with a single effect.  I might consider changing that but for now don't think those buttons are making any difference.  And I don't believe single effects are ever pasted by time when a timing track is active.  They are pasted to fill up the selected cells or groups of cells.  If you select a block it will create one per row for that entire duration.  Now that we have these new options I'm looking into whether the way everything works makes sense.  Not getting much help from the development team so I guess I'll just do whatever I want.

**Comment by keithsw1111** [comment]
We are just recognising you know this space way better than we do ... and you'll probably get better feedback from users than from us.

**Comment by AzGilrock** [comment]
If you copy an effect that spans multiple cells and then select a single cell and do a paste by cell it won't just fill that one cell.  Paste by cell will cover the same number of cells as the original copy and based on a percentage if it's partial.  So if you select multiple cells to do that paste then paste by cell doesn't really make any sense because by definition paste by cell would ignore the number of target cells selected because it's only based on the number or cells that were copied.  Right now the paste by option isn't even used if you select multiple cells for the target paste.  So what if you want to copy an effect that cover 3.5 cells and then paste it to fill a single cell...how should we let you execute that?  Or what if you want it to fill say 5 cells that you select?  And we want you to be able to do the paste by cell that uses the original number of cells based on a proportion so how do we let you be able to accomplish all 3 of these actions?

**Comment by AzGilrock** [comment]
What further complicates things is not all paste data contains paste by cell info.  So I'm probably going to have to make it react differently based on whether it contains the info and then maybe I can make it work all these ways.  So for hotkeys which won't contain any cell info I can have paste by time paste into the full length of the selection whereas paste by cell could paste a copy into every cell so that would maintain the options already available.  And if it does contain cell info like a normal copy then the number of cells selected would be irrelevant and it would paste either the original time if by time or the original number of cells if by cell.

**Comment by dcwehw99** [comment]
For me what I was trying to do shown in the attached video is pretty basic.  I wasn't looking for anything complicated but just being consistent whether it's one cell or more than one.  The two different paste options do behave differently as you'll see in the video.  I think It's pretty self-explanatory.

All the recent changes/additions to the copy paste/pates functions have made life so more easier and are really appreciated.

Thanks
Denny
[Xlights Paste Issue.zip](https://github.com/smeighan/xLights/files/241696/Xlights.Paste.Issue.zip)

**Comment by AzGilrock** [comment]
The paste code is probably one of the most complicated sections of code in the program.  So yeah you might be looking for one basic thing but I gotta worry about the impact to the many variations.  Paste data may or may not contain cell information. It might be old paste data versus new paste data.  It may be coming from a preset or from a hotkey.  You may be pasting with or without a timing track active.  You can copy with no track active and then paste with a track active and vice versa.

**Comment by AzGilrock** [comment]
Also when you did the second to last paste that you thought was executed as paste by time it wasn't.   That was actually a paste by cell because paste by cell uses the original percentage the effect filled the cell.  So you need to paste into a different sized cell to see what I'm talking about.  Make a timing that's say 1 second and insert a 1/2 second effect and copy it.  Then paste it into a 2 second timing mark using paste by time and then paste by cell and you'll see the difference.  I agree the last paste was not consistent.  I also believe the first paste to be incorrect because it fully filled the cell when it was supposed to do a paste by time.

**Comment by dcwehw99** [comment]
Aha!  Now that you've explained the difference between the two paste options I would agree that the first paste is incorrect also.  Previously I was having a hard time understanding the "Past by Time" option because of its behavior.  I just always used the "Paste by Cell" option after it was added.

I tried pasting a 5 second cell into a 10 second using the "Past by Time" option and it completely filled the 10 second cell.  I'd expect it to only fill 5 seconds, i.e. half of it.  Also pasted it into a 2.5 second cell and it completely filled it truncating the last 2.5 seconds.

I wasn't trivializing the copy/paste functions but was trying to understand a single cell paste.  

Thanks
Denny
