### ISSUE TITLE
Enhancement Request: Redo / CTRL+Y

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#555]
It would be nice to have a way to undo a CTRL-Z.  I would use it to compare between different effects dropped on a model to be able to flip back and forth in viewing the results.

Thanks
Denny

**Comment by AzGilrock** [comment]
I've been waiting to back slap the first person that asks for this.  Well we might would do it.  Are you rich?

**Comment by stevegiron** [comment]
The way to compare effects on a model is to put them each on a different
layer. Change the layer blending mode between Layer1 and Layer2. I do this
with many effects, and often both are saved to the xml file, but only one
is used at render time because I chose Layer 1 or Layer 2.  Once you start
swimming with the current instead of against it, it's much easier.

**Comment by dcwehw99** [comment]
Gil,
I just knew you would jump at this one.  Being an old time developer, I some how figured this one wouldn't be fun.  Since I've gotten into Xlights heavily recently developing new sequences it's another feature that would exploit the power of Xlights but of course you have to pay the price with developing the code. 

Steve,
Thanks for tips and tricks.  I hadn't thought of using layers to accomplish it.  I little involved but it gets the job done as you said.

Thanks
Denny

**Comment by AzGilrock** [comment]
The problem is I've never been sitting there sequencing and said gosh darn I really wish there was a Redo.  So until it's something I desire I'm not going to be motivated to waste time on it.  Just don't make mistakes and you won't need Z or Y.
