### ISSUE TITLE
Enhancement Request: "Recent Files"

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#564]
Can a "Recent Files" option be added to the Files menu?  It would display the last few file names of the sequences you have been working on.  Selecting a file name would open the sequence.

Thanks
Denny

**Comment by AzGilrock** [comment]
I work in several show directories so a recent list can cause problems if you open up the wrong sequence from the wrong show directory.  We would almost have to store the show directory and the file and do a complete switch.

**Comment by dcwehw99** [comment]
In doing some snooping at how other applications have implemented "recent files" it appears they have stored the the complete path/file name either in registry keys or a configuration file.  Is that what you are talking about when you say " We would almost have to store the show directory and the file and do a complete switch."?

**Comment by AzGilrock** [comment]
I'm saying if you have 2 show directories like "Halloween" and "Christmas" or in my case I have show directories for the 50 users I help out that if you open up a sequence from the Christmas show folder while in the Halloween show folder you will get a bunch of errors telling you models are missing.

We actually already have a recent list under the File menu but right now that list is your recent Show directories.  That's helps people like me that switch show directories a lot.  So if we have recent files we would probably have to store which show directory is associated with every file in the recent list so that we could swap over to that show directory when that file is selected.  And then what if you have the same file name in multiple show directories.

Just saying these issues that sound simple in Denny's world of one show folder get much more complex when you gotta consider everything our program has to deal with.

**Comment by stevegiron** [comment]
The way I determine the sequences I've worked on is by looking at the timestamp of the xml files. It works 100% of the time. It works for every application I've ever used too.  When it gets closer to show time in December I use a pen and paper to keep track of what's done and what needs more work.

**Comment by dcwehw99** [comment]
Aah!  Now I understand and can appreciate the implications of what I'm requesting.  In my simple world I have one Christmas show per year and one directory for each year.  I'm always working out of the same directory just moving around to different sequences within that directory.  Occasionally I pull a sequence from a previous years directory to view something without fully realizing Xlights was not using the rgbeffects (models) file from that year.  For me that worked out OK because I typically just copy of rgbeffects from the previous year and add new models to it for the next year.

Thinking outside the box and I don't know if this is possible or even feasible but maybe besides or in addition to having to associate the show directory to every file in the "recent files list" you could check the sequence files path name against the current show directory.  If there's a mismatch throw up a dialog box advising the user and ask them what they want to do; switch directories or stay with the current show directory.  You could even go as far as checking to see if there's a rgbeffects file in the directory before asking the question. Of course this assumes that the Xlights XML system files and the user sequence files are in the same directory.

Obviously more complex than I was originally thinking and needs to be digested.

Thanks
Denny

**Comment by AzGilrock** [comment]
Well I wasn't saying we need help designing it.  Just saying its not easy enough to knock out in 5 minutes. ;)

**Comment by AzGilrock** [comment]
We now have recent files and recent show folders available.
