### ISSUE TITLE
Screen Flash on "Pause" Restart

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#565]
2016.28
This started happening with the implementation of OpenGL 3 (2016.23) although it also happens using the OpenGL 2 option.
Problem:  If you press the "Pause" key after you allow the grid screen to scroll to a second or subsequent screen, on the restart of the pause, i.e. pressing the pause key again, will cause the grid to flash the first screen you started playing for approximately 1/4 second before re-displaying the correct screen.
Attached is a video of the issue.

Thanks
Denny
[Xlights Pause Issue.zip](https://github.com/smeighan/xLights/files/260057/Xlights.Pause.Issue.zip)

**Comment by AzGilrock** [comment]
Everyone is so focused on OpenGL changes they think it causes everything.  This issue has nothing to do with OpenGL.  If you look through the change history you will see an issue I fixed that jumps the grid to where the play start marker is so I didn't account for a pause that needs to start back at the paused position instead of the play start marker.  Also 1/4 second?  That sounds 10 times slower than my PC.
