### ISSUE TITLE
Bug: Time and FPS blacked out after switching tabs

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#576]
I noticed that if I have a sequence loaded and I switch to the Layout tab, then back to the Sequencer tab (twice), that the Time and FPS text is getting redacted.  Must be a secret.  :)

I can only duplicate this by switching between the Layout and Sequencer tags.  I can't do it with the other tabs.

Mac OSX 10.11.4
xLights 2016.31

![untitled](https://cloud.githubusercontent.com/assets/12144876/15346274/f7c4f334-1c7b-11e6-8309-67c83b16cce5.png)

**Comment by AzGilrock** [comment]
FPS only shows when the sequence is playing.  Are switching the tab during play?  Luckily for you we are on a quest to delete all tabs so you won't be able to switch them.

**Comment by dkulp** [comment]
I'm not seeing the blackout, but I AM seeing my background image on the house preview disappearing after 2 page flips.   It looks like there is a problem with the GL textures (the text on that panel is a texture).   For some reason, the glBindTexture call is returning an INVALID_OPERATION error, but no idea why, especially since the textures worked the first several times they were displayed.

**Comment by kppankratz** [comment]
Yes, the sequence was playing when I switched tabs.  I'll check this afternoon to see if my background image is disappearing as well (mine is on a second monitor off to the side so it didn't catch my attention like the time and fps text).  I look forward to only the sequencer window down the road.  Could this bug persist using the future method of switching to the layout function that you guys come up with?

**Comment by AzGilrock** [comment]
Sounds like you are replying to my statement which is kind of obsolete if you read Dan's reply.  By the way I for one think we will miss the tabs.  I kinda like being able to quickly jump over and see my models and setup page so I'm hoping whatever is dreamed up isn't more of a burden just because we had one user that told Sean modern Windows programs don't use tabs and it set him out on a mission.
