### ISSUE TITLE
Use arrow keys to select models from model list on layout panel

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#582]
If you select a model on the list of models on the layout tab panel, and press the down arrow, the expected result is that the next model in the list is highlighted - This does work.  However, a subsequent down arrow does not do the same, but instead switches to the highlighted and now selected model on the layout visual window and moves the model instead of selecting the next model down on the list.

**Comment by AzGilrock** [comment]
You must be reading the developer emails.

**Comment by stevegiron** [comment]
That's what happens when you have such basic passwords :)

**Comment by AzGilrock** [comment]
Heck almost every website is requiring such restrictive passwords I can't even remember half my own passwords.  Some websites I use the forgot password every time now.  I believe things have gotten less secure because everyone now tends to need to write down passwords more than they used to.  But back on topic yeah I reported this issue way back when the Layout was first changed.  Sean just discovered it and emailed us a day or so ago.
