### ISSUE TITLE
Move XY Coordinate Sliders to Layer Settings Tab

### ISSUE THREAD

**Issue by MCStoff** [smeighan/xLights#588]
Move the XY coordinate sliders from the individual effects to the Layer Settings Tab and make it available for every effect, much like the new Roto-Zoom.

**Comment by AzGilrock** [comment]
Which effects do you think this would be useful for?  I'm betting its not as many as you think.  We discussed this quite a bit already when roto-zoom stuff was added.  One problem is parameters in the roto-zoom window are applied after an effect has been rendered but some of the effects wouldn't render properly unless they know the X/Y before they are rendered.  For instance my Galaxy effect.  If you wanted to draw it starting in the bottom right corner and then have it fan out across the model it wouldn't work to have the effect routine render it in the middle and then move it to the corner because you would end up with 75% of the pixels being black because when you translate you will be moving pixels into view that were not rendered.  Unless they have a change that allows the position to be fed into the effect render routines this won't be done.  And then they would realize the roto-zoom name was stupid and they should have used tabs like Position, Scale, and Rotate list I suggested.

**Comment by MCStoff** [comment]
No in-fighting on naming tabs!  Your response gives me some insight into the unseen complexity of the program.  What prompted my suggestion was the new tab in the Layer Settings and I wanted to move the starting point on the Ripple effect. I ended up using the Shockwave to get pretty close to what I wanted. I understand the issue and why it wouldn't work for all effects unless there was a way to render immediately after the reset of the X Y coordinates.
Thank you for the response and all the great work you do on the program.  After 10 years of LOR, I am reinvigorated and plan on redoing my entire display in pixels.  The learning curve for the program was not too bad and once I understood the logic behind the various tools I found everything to be very intuitive.  Again, thank you for making such a great tool for our hobby.
Michael
 

    On Saturday, June 4, 2016 7:43 AM, Gil Jones <notifications@github.com> wrote:
 

 Which effects do you think this would be useful for? I'm betting its not as many as you think. We discussed this quite a bit already when roto-zoom stuff was added. One problem is parameters in the roto-zoom window are applied after an effect has been rendered but some of the effects wouldn't render properly unless they know the X/Y before they are rendered. For instance my Galaxy effect. If you wanted to draw it starting in the bottom right corner and then have it fan out across the model it wouldn't work to have the effect routine render it in the middle and then move it to the corner because you would end up with 75% of the pixels being black because when you translate you will be moving pixels into view that were not rendered. Unless they have a change that allows the position to be fed into the effect render routines this won't be done. And then they would realize the roto-zoom name was stupid and they should have used tabs like Position, Scale, and Rotate list I sugge sted.—
