### ISSUE TITLE
Do not render on save still saves FSEQ

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#621]
When deselecting 'Render on Save', a save will still create an FSEQ file. I believe the original intent was for  a quick save that would update the XML only. That is now how it's working now.

**Comment by dkulp** [comment]
This is working as designed.   This allows people that use the "Render All" button to still produce a usable fseq file at save time.

**Comment by AzGilrock** [comment]
I told him to log this cause I don't like it either.  I want an option that just saves XML.  With the larger setup we have at the Expo I kept wondering why the hell is it taking so long to save when I'm not rendering.  The way it works now the file is only valid if you do not touch a single effect after the render all because if you do you can easily change the rendering order of the buffer and have different data than what a normal save would give.

**Comment by dkulp** [comment]
Gil, can you retry with what I just pushed?    It should be MUCH MUCH faster to save the fseq file now.   Doesn't change the behavior, but should make your issue much less noticeable.   I also updated the read code a bit so it's also faster.   My 1/2 million channel 30 second test sequence loads in 3 seconds (down from 8.5) and saves in 1.7 (down from 7).   Then again, I'm on an SSD which is the biggest help for this.
