### ISSUE TITLE
Modify Layer Mask to use User Defined Polygon instead of Square

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#626]
Currently the layer mask is a square. Its functionality would be enhanced exponentially if rather than a square this was a marquee where the mask was a bounding box of user added points that could be moved to create polygon shapes of their choosing.

**Comment by stevegiron** [comment]
A layer mask comes in the shape of any effect.  You can use the picture effect with a picture of any shape and use that as the mask.  You could use the built in movement options with picture to move your mask to add even more effect dazzle.

**Comment by dkulp** [comment]
Note:  it's not a mask.  It's a sub buffer.  In xLights, a render buffer is always a rectangular shape.   The bounding box is just defining the sub-section of the complete buffer to use for rendering that effect.   It creates a new buffer of exactly that size for the purpose of rendering.   It is not a mask.

**Comment by idleup** [comment]
Steve-- using the picture as a mask is a great work around but it is an imported bitmap and getting it to mask the desired area of the model that is a complex model may require many iterations between the graphic creation software and xLights. Much easier if you could just create a shape and move the dots, add points, etc, until just the pixels you desire to show are showing

**Comment by idleup** [comment]
Dan-- Okay, its not a mask, but it is being used as one by at least some of us... Is there another way to do the same thing (mask an effect above to show an effect below) where the points of that mask can be added dynamically and moved to fine tune the pixels shown on the effect below rather than relying on an imported bitmap shape like Steve suggested?

**Comment by AzGilrock** [comment]
The reason we are saying it's not a mask is because the effect will scale down to the size of the sub-buffer.  So if you drop an effect like Fan and then reduce the sub-buffer it doesn't cutoff part of the fan blades it reduces the entire size of the Fan.  But I guess you could say it's masking part of the model.

The main problem with Steve's layer mask suggestion is lets say you have layers stacked as Layer1, Layer2, Layer3.  There is no way to use Layer1 to mask Layer2 but not also mask Layer3.  We don't have the concept of a blending mode only applying to the one layer below it.  Blending modes always operate on the entire stack below it because they all have been blended together starting at the bottom.

**Comment by AzGilrock** [comment]
This one is just not possible.  All models are represented by a rectangular buffer and all the sub-buffer feature does is redefine that buffer.  For instance if you draw a star shape and shrink the sub-buffer to 1/4 size then the star shrinks to 1/4 size it does not clip the image.  Need to use an image with masking to do clipping.
