### ISSUE TITLE
Crash when using random effects

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#630]
This happened on 38,39,40 as well. Not sure if it's the rgbeffects file or the code.

New sequence, pick audio, add beats/bars timing, select all timing marks for a small set of model groups, random effects, crash.

Previous crash to this one was New sequence, pick audio, add beats/bars, select a 30 second range of audio to play and hit spacebar to start - Crash

Debug at www.stevesimages.com/xl4/108

**Comment by AzGilrock** [comment]
I was doing a whole lot of random effect creation last night because that's how I test my selection logic.  I didn't see any issues so it's either gotta be a particular size/type of a model you're using or some specific settings that end up in an effect that cause things to blow up.  I'd say we need your rgbeffects file to try to reproduce those steps and see if we can get it to crash.

**Comment by AzGilrock** [comment]
I've tried a few times and couldn't reproduce.  If you can get it to happen again package the log files and post them in a new issue.
