### ISSUE TITLE
Implement Mass Editing of Like Effects

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#641]
In Vixen 3 if you multiple select effects of the same type you can change the color, effect settings, etc. and it will change all that are selected. This saves a great deal of time and I would like to see it in xLights as well.

If the user selects multiple effects that are not the same type and changes color it should still change for all the effects since color is a common attribute (this should be the case for other attributes that are shared with all selected effects). However if they change an attributes that only applies to one type of effect in the multiple selected group it should pop up a dialog saying that only effects with that attribute have been updated. The attributes that are shown for editing in XL is the type of the last effect selected as part of the multiple selected group which is fine. 

EXAMPLE:
User selects 20 fill effects but the last one selected as part of the select group is a garland, so in the effect settings it shows attributes specific to garland. If the user changes the "Garland Type" attribute than only 1 effect will be updated and the popup will notify them of such. If they change color than all 21 selected effects will be modified to match the new colors. Likewise, if the last effect selected as part of the group was a fill and they change the "Cycle Count" attribute than the popup will say that 20 effects were updated (since the garland does not have that attribute).

**Comment by keithsw1111** [comment]
For the colour I thought that was what happened if you pressed the update button next to the colour options ... it updates the colours on all selected items.

**Comment by AzGilrock** [comment]
That feature already exists for color.  Hit the Update button beside the colors after you make the change.  You can also change a bunch of effects at once by using the Update button in the Effect Settings but it will make every effect you've selected identical.

**Comment by AzGilrock** [comment]
I don't even know if the rest of that request is possible.  We don't really keep track of which setting you're changing.  A timer is running that compares the selected effect settings from the last pass and if different it renders the changes.  At least that's how I believe it works since I didn't write that part.

**Comment by idleup** [comment]
You are correct, it does work with color :-)

For the effect update would it be possible to only update the attribute that was changed instead of making the effects identical?

**Comment by AzGilrock** [comment]
With what I know about that part of the design I wouldn't know how to do it.  The issue is we don't update effects as you drag sliders or click checkboxes.  A timer runs every 50ms to check whether you made a change so you could technically make several changes if you're superhuman.  But after that it's already latched in the new settings.  So when you click Update all we have is what are the current settings there is no frame of reference for what you would like to diff the current settings to for knowing what's changed.

**Comment by stevegiron** [comment]
Mass editing of effects can be done with Notepad++ and your xml file. Been there, done that many times.
