### ISSUE TITLE
Keyboard movement only works when single effect selected

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#642]
When a single effect is selected the keys can be used to nudge the effect up/down/left/right. Once you multiple select you can no longer use the keys. Keyboard movement should be allowed for multiple selected effects.

**Comment by AzGilrock** [comment]
So I can make it work for left and right pretty easy.  Up and down is a nightmare.  Just think of how complex our grid is.  You can have a model group that contains arch1 through arch 6 and then you can have each of those models on the grid by itself.  So if the group is expanded you actually see 2 copies of every effect on that model and anything you try to do to one copy gets echoed onto the other copy.  I've got up and down partially working but only with rows that are visible on the screen.  Once I start trying to include rows you can't see then it gets tricky because are they not seen because they are off-screen due to scrolling or hidden due to a collapsed model.  I don't think any other program has to deal with these complexities.

**Comment by idleup** [comment]
Gil, even if you only implement left and right that is still a huge improvement. In fact, 80% of the time people nudge I would say it is left and right anyway.

**Comment by AzGilrock** [comment]
Another hiccup I'm seeing with up and down is with the expanded model groups.  If you have an effect on Arch2 you may see that effect in an expanded Arches group but Arch2 may also exist by itself where maybe Arch1 is not above it.  So technically its the same effect shown twice but if you move the one in the group it lands on Arch1 but if you move the one by itself it lands on maybe Candy Cane 1.
