### ISSUE TITLE
Add functionality to Nest Groups

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#653]
Add the ability to add groups inside other groups and propagate effects accordingly.

**Comment by AzGilrock** [comment]
LOL...that's been a goal since before you used the program.  The developers just don't log our own wishlist. :)

**Comment by idleup** [comment]
I actually did all kinds of searches of the issues before posting this because I could have sworn it would be in here already.

**Comment by AzGilrock** [comment]
I thought it was here too.  Just saying I think you know we were already working towards this.  The change to the TreeView for Layout, ability to have layers on strands (since sub-models act like strands), and sub-models in this release were things that needed to happen prior to having nested groups.  The main issue now is being able to make sure you don't create groups with circular references and a way to handle them on the grid.  Currently it was setup for the 3 tiers.

**Comment by idleup** [comment]
Yes, I knew you were working towards this functionality with those latest features. I just wanted to formalize it by creating an issue for it so I could keep track of the things I want to be notified about. 

Sorry, it must be the Project Manager in me... :-/

**Comment by AzGilrock** [comment]
Completed.
