### ISSUE TITLE
Right scrolling arrow 

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#67]
When working on a sequence the scroll right arrow does not work I can scroll left,up,down but not right.

**Comment by smeighan** [comment]
what object are you scrolling? I need to know how to duplicate this?

**Comment by RichardRennII** [comment]
Hello Sean I am trying to scroll the sequencing screen the slider bar works well but when I try to move to the right with the little scroll arrow it will not move

**Comment by smeighan** [comment]
i have verified this. I am going to mark this as a bug to be fixed in 4.1 as it is not a blocker. 
Dev team. Open a sequence , like "test_for_crash.xml". Zoom in enouight so horiz scroll bar appears.

You can click the left arrorw, up arrow and down arros on the scroll bars and the sequencer window moves. if you click on the right arrow (bottow right corner), nothing moves.

dragging scroll bars with the mouse works so i am moving this to 4.1 since there is a workaround.
