### ISSUE TITLE
Question: Save vs Render All and .fseq file

### ISSUE THREAD

**Issue by kppankratz** [smeighan/xLights#676]
I've been playing around with settings for my P10 panels recently and do not have them connected directly to my computer for testing, so I've been rendering the .fseq file and uploading it into the FPP.  I was noticing that after I made changes to the sequence and rendered, the uploaded file didn't have the changes made when played.

So I would delete the .fseq file to make sure I would have the most recent/up to date version to upload, then render all to create the file.  That's when I noticed that a new .fseq file wasn't being created even though the progress bar was indicating otherwise.

From my testing I found that clicking on Save first will always create the .fseq file in a matter of seconds that xLights is saving the .xml file.  Even the status bar in the lower left indicates that the .fseq file was saved after clicking the Save button.  Not sure if only a container file is being created upon save for the .fseq, then the actual data being dumped into the file upon Render All being clicked?  But that wouldn't explain why making a change then clicking Render All wasn't updating the .fseq file for me.  Clicking Save first, then Render All would update the .fseq file.

I don't recall experiencing this in the past.  I know one FB user is having a problem getting a .fseq file created (posted in the last couple of days), and we couldn't get it figured out on his end even after I figured out I had to save first then render.

Maybe this is a possible bug versus a question?  I'm curious if anyone else can replicate this?  Or maybe I'm not understanding the order of process for generating the .fseq recently?

I'm running under OS X, have render on save turned off and render mode set to erase.  I believe the other FB user is running under Windows

**Comment by AzGilrock** [comment]
It's pretty easy.

Render All only renders data to the local program buffer.
Save has 2 modes.
Save (with Render on Save turned off):  Does a quick save which saves the XML and saves the local program buffer to a .fseq file.
Save (with Render on Save turned on):  Does a full render then saves the XML and the .fseq file.

By default Render on Save is turned on so if you aren't seeing it take time to render when you hit Save then you turned it off.  We provided that option because most of the time you don't need a .fseq created you just want to save the XML file which can always be used to create the .fseq data.  So you could do a Save, Save, Save, Save, Render All, Save.
