### ISSUE TITLE
Version Number no longer in Xlights title bar

### ISSUE THREAD

**Issue by Clyde-L** [smeighan/xLights#685]
I noticed that after some recent updates, the Xlights version number is not listed in the title bar.  I do see the sequence name is now view-able in it's place.  Was hoping to have that version number added as well if that is possible. 

I can't seem to find a way to locate the version number once a sequence is open.  

The version number is displayed upon opening Xlights or after closing a sequence.

**Comment by dkulp** [comment]
Help -> About  will work.   No other program anywhere sticks the version number in the title bar ever.   Not sure we should put it back.

**Comment by stevegiron** [comment]
Objection!
![image](https://cloud.githubusercontent.com/assets/10568498/18524177/368c5dde-7a6c-11e6-9de5-6d83960f76cb.png)

**Comment by Clyde-L** [comment]
This is the current ABOUT screen Dan... I looked there first  
;)

![screenshot 2016-09-14 14 13 11](https://cloud.githubusercontent.com/assets/12719816/18524228/8e3ec1a2-7a85-11e6-8380-9972a8f76813.png)

**Comment by Clyde-L** [comment]
haha now I see it... at the top of the box... doh!

**Comment by AzGilrock** [comment]
The main reason I've liked it is users don't tell us the version they are using a lot of times and when they post screenshots or videos there's been a lot of times I've picked up on the version they had from the header.

**Comment by Clyde-L** [comment]
Same thing here as Gil, I help a BUNCH of people via Team Viewer.  Most of the time, the new people using the program have no clue what they downloaded.

**Comment by patdelaney** [comment]
Actually years ago when I coded a VB6 app I put the version number in the Title Bar, I did it so end users would have an easy way for make sure they didn’t have conficting versions. The Client App did not have a Help->About dropdown menu.

 

But that was a weird issue

**Comment by kmacmaster** [comment]
When I program, I always put the version number in the title bar.  Mostly because the version changes all the time... like this program.  This is not like QuickBooks that comes out with a new version once a year where the point releases don't really matter, the version changes weekly.  Maybe make it say "XLights v2016.49 - c:\users\yournamehere\xlights\my crappy sequence.xml"

**Comment by Clyde-L** [comment]
Yes, there are more updates to XLights than any other program I use.  I understand that the ABOUT box will show it, but it's not the first think I come to look at when helping others.

**Comment by mmalewski** [comment]
Yes, I completely agree.  I am a new xLights user, and I downloaded the "Beta" version (latest) as of a week ago, and it has changed several times since then.  I was so confused as to what version I was running (or even had installed) and was having lots of problems with "View -> Windows -> House Preview" not working.  So I was trying to figure out where the "version" number would be located.

My FIRST reaction (as a new user) would be to check the title bar, where it says "xLights" and there was no version number there.  Then I started clicking things, and even after 3 days, I could NOT find the version number.

I even checked "Help -> About" but there was no version number there either.

Finally after 7 days, I stumbled upon this "Bug" and after reading it, I realized that "Clyde-L" is EXACTLY on point!

Yes, I can confirm that this is DEFINITELY a bug, and xLights is NOT "user friendly".  Maybe a developer thought it was a good idea to "remove" it, but from a new user (or even a "lay person" that has never used xLights before), this current placing of the version is IMPOSSIBLE to find.

I had to go back and look at Clyde-L's screen shot, and even after looking at it 3 times, I still didnt' see the version.  It wasn't until he posted his "Doh" comment, that I realized the version number was NOT in the About page, but actually in the "Title bar" of the About page (a place that I would have NEVER thought to look, and still didn't notice it, even after looking at Clyde-L's screenshot.

This is really bad.  I mean I've just spent the past 7 days flipping through the "user Manual" and there is so much wrong (and broken) with this program (and bad links or unclear instructions) in the user Manual.

I'm just hoping that the developers will begin to listen to us (as a new user), so that we can improve the documentation, user manual, and also begin "fixing" things that seem like "common sense" to the developers, but are DEFINITELY not "common sense" to end users.

It should be simple to use, and even the version number was difficult/impossible to find.  If you sat someone down (who never used xLights before), and asked them to find the version number, I know that I couldn't do it.  It took me SEVEN DAYS, and several google searches, and sifting through hundreds of articles, and it wasn't until I found this GitHub, and found this "Bug" report, explaining the same thing (that I was thinking and looking for).  

If possible, could we please "revert" back to the "old way" (which is the "common sense" way) and yes I would think (as a new user) to look at the title bar (just like every other program that I use).

I do agree that this program is an early alpha/beta, and the version numbers seem to change almost DAILY, so it's too difficult to even figure out what version you are using (as a new user) and putting it back in the title bar would make things MUCH easier on new users.

I honestly shouldn't have had to spend 7+ days looking for (and trying to find) a "hidden" version number.  The "title bar" of an "About" page is something I have never in my life EVER seen before, and never would have even thought to look, and even after clicking on "About" (over 200+ times), I still didn't see it or find it.

It wasn't until I saw Clyde-L's post (on this bug issue) that when he said "Doh", that's when I realized that I had "missed it" as well.

My brother, my dad, my girlfriend, and even both of my cousins couldn't find the version number.  So no, this is NOT "intuitive" and the current idea of "hiding" the version number in the "title bar" of the About page, is just a bad idea (for new users).

If possible, please take the time to change this.

It shouldn't be a difficult "fix" but it would definitely make life easier on new users, and I can definitely say that as a new user, xLights is NOT "user friendly".  I've spent 7+ days trying to figure xLights out, and I still can't do anything on it.  The User Manual is in really bad shape, many of the menu items are not working.  If I click on things, things don't work.  It took me 7+ days just to figure out the "Queen VAMP plugins" which pointed to a bad link in the user manual, and after 5 days, I finally found an "archived" post (from April 2017) that was "closed" and "archived" that had some step by step instructions, and various questions, from other users asking the same exact thing I was trying to figure out.

In the end, nothing worked... and then I stumbled across a "QM Vamp Plugins" folder (on my computer) which I must have somehow created (by how/what/when/why?) I had no clue, but I opened that folder, and there was an executable, and I clicked on it, and it somehow installed Vamp!

Apparently the User Manual is EXTREMELY outdated, and has VERY VERY WRONG instructions, and it should be updated to point towards the xLights.org downloads section, and point towards the "QM Vamps Plugin" (exe) instead of pointing towards a bad link for: http://isophonics.net/QMVampPlugins

Yes, there are MORE UPDATES to xLights than any other program I have EVER used (or ever seen), and it does seem "problematic" (for new users and experienced users) that don't even know what version they are running.  I wasn't even sure if I was running a Beta, or stable release.

Finally, I just re-downloaded and installed over the version I had previously installed, because I couldn't even figure out what version I had installed (previously).  

> I understand that the ABOUT box will show it, but it's not the first think I come to look at 
> when helping others.

I agree.  As a new user, looking for answers, I couldn't even find it.  It's really bad, and I've found hundreds of "issues" (that as a "new user") are difficult to understand, or the manual needs to be fixed, and just various problems that I've spent over 40+ hours trying to "figure out" because the manual is either wrong, or unclear, or bad links, or just very "unintuitive" things (like the "version number" placement).  Hopefully this can be fixed.

I really do appreciate all the hard work the developers are doing, and I'm not here to complain, I'm just here to voice my concern (as a new user) as to what is "wrong" (and why is it so hard to learn and use this program) and hopefully we can work together to make it "easier" for new people to understand and use.  The User Manual definitely needs a LOT LOT LOT of work.  I know the "QM Vamp Plugins" had me stumped for over a week... and the User Manual is just plain wrong.

**Comment by Clyde-L** [comment]
mmalewski 
I invite you to check out the following link to a vast video library that users have compiled.  I totally understand your frustrations as a new user.   I often forget what it's like to be a noob, learning everything you need to understand in order to make RGB and pixels work.   
http://videos.xlights.org/

You can also check out the "Official"  xLights Support Group on Facebook.  There are nearly 3000 users of the software with varied ranges of skill and talent.  Plenty of people to help make learning this software easier.
https://www.facebook.com/groups/628061113896314/

Finally, if you are still stuck (frustrated, confused, etc...) after all of this support, feel free to get in touch with me thought my website.  Clyde Lindsey
www.leechburglights.com

I don't use the forums too much.  I  hang out mostly on Facebook.   

Clyde L
