### ISSUE TITLE
Rendering issue in .49

### ISSUE THREAD

**Issue by jediknight2** [smeighan/xLights#688]
I have a rendering issue in .49 with the attached sequence.  I step back to .48 and it renders fine.
[xLights_dbgrpt-9564-20160915T222731.zip](https://github.com/smeighan/xLights/files/475955/xLights_dbgrpt-9564-20160915T222731.zip)

**Comment by AzGilrock** [comment]
We already discovered and fixed the Blur crash.  It happens if you had a value curve for Blur that returned a value of 1 or 0.  You can prevent the crash by removing any Blur curves that are set to those low values.  Those aren't really valid values but we will prevent it from crashing next release.
