### ISSUE TITLE
Effects not overwritten after a data import

### ISSUE THREAD

**Issue by jediknight2** [smeighan/xLights#689]
In .48, after I have imported a data layer, then right  clicked on that model and converted effects...if I delete one of those effects, then place an XL effect in that spot ...it doesn't overwrite the data, even after render is pressed.  Even if a layer is placed above or below that effect...the imported data layer effects stays.  This is using an HLS data import.  Same file that was for my crash report today.

**Comment by jediknight2** [comment]
https://drive.google.com/file/d/0B71_WLJUoWJKXzhGQnFBaVBEVXM/view?usp=sharing

**Comment by AzGilrock** [comment]
First just a comment.  Once a data layer has been converted to effects and the data layer deleted its the same as if you have dragged all the effects there manually.  So it doesn't really matter how the effects got to where they are they render the same way.

Now I looked at your sequence and the problem in your video is you never expanded the Pumkin4 model to notice that you have the same effect repeated on the Strand 1 layer and then again on the Node 1 layer.  So those are 3 different effects.  You need to delete all the effects that are on the nodes and strands since it appears you have exact copies at the model level.  So you deleted a model level effect but still had the strand and node level effect rendering.

**Comment by AzGilrock** [comment]
See the red square I drew.  Each of those white boxes is a different effect so it's 3 copies at 3 different levels on the same model.
![effects](https://cloud.githubusercontent.com/assets/2024669/18574182/7767f868-7b7f-11e6-9b95-f29b7502f12e.png)

**Comment by jediknight2** [comment]
OK, I see what's going on...I just assumed since I was deleting the effect on the main model, everything was deleting...I didn't think to expand that model to look at the nodes.  Thanks for pointing that out!
