### ISSUE TITLE
Ongoing crash

### ISSUE THREAD

**Issue by Shawn4242** [smeighan/xLights#697]
I've got an ongoing crash happening (9 times so far) in a one sequence. The backup file has been HUGELY helpful but I want to figure out why I am having this issue. What files (besides the rgbeffects and sequence) do I need to post for someone to be able to diagnose the issue? The crash report?
Link to those are here:

http://nutcracker123.com/forum/index.php?topic=3460.msg21603#msg21603

Basically in the middle of sequencing I get a crash report and xlights shuts down. Nothing fancy happening and the sequencing thus far has been standard stuff. I have never had this so I am not sure what I am looking for in order to diagnose. 'Check Sequence' only brings up one minor warning about overlapping.

**Comment by AzGilrock** [comment]
I can tell from the log it crashed because you tried to paste invalid/empty data.  This has already been fixed by a checkin of mine a couple days ago and we usually close tickets when the code fix is checked in.

2016-09-21 16:27:24,528 13476 log_base [INFO] Pasting data: CopyFormat1	0	0	5	0	777	PASTE_BY_CELL
2016-09-21 16:27:24,528 13476 log_base [INFO] mPartialCellSelected 0,   OneCellSelected: 1    paste_by_cell:  0
2016-09-21 16:27:24,528 13476 log_base [CRIT] Crash handler called.
