### ISSUE TITLE
Add color selection to sparkle in color effects

### ISSUE THREAD

**Issue by Beldwain** [smeighan/xLights#720]
This would be a nice enhancement, the ability to change the color of the sparkle slider in the color effects window.  This effect is currently very useful in white but even just changing it to a different color could enhance the use of red or green in a wreath, blue or grey on silver bells, yellow or orange on jack-o-lanterns.  Of course this keeps the imagination flowing with other sparkle combinations.  As an example, someone would consider glitter and painting with the right combination of colors.

**Comment by AzGilrock** [comment]
We've shot this idea down a couple times before.  If you need this its easy to do by just using 2 layers and something like the Twinkle effect on top.  I personally do not want to see more color selection controls added just for this sparkle feature.  If it was up to me I'd delete the sparkle thing altogether since its not doing anything you can't do with 2 effects.

**Comment by Beldwain** [comment]
understood.
