### ISSUE TITLE
Application allows multiple simultaneous instances to be launched

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#74]
Once XL4 is running, a subsequent start of the application does not bring the current instance to the foreground, instead a new instance is launched. (Windows)

**Comment by AzGilrock** [comment]
Yeah I'm not sure if we want to disallow this or not.  It  could come in useful if it was possible to open up two instances and copy/paste a section of effects to another sequence.  I'm not sure if that works since I haven't tested it.  It would really be nice if we had a multi-document design and you could cut/paste between two sequences right in the same app but unfortunately that would take a lot of redesign.   That's something you usually gotta do from day one when you start an app.

**Comment by stevegiron** [comment]
Not an issue for me. Closing out.
