### ISSUE TITLE
Change Value Curves to 255 scale on DMX Effect

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#744]
Hello! I spent the night programming moving-head intelligent lights and a pain-point for me was the constant need to convert 255 values into a percentage in order to use value curves. 

Currently, if I want to swing between between 25-185 in DMX values, I have to find the percentage of 25 and 185 in relation to 255 and round to the nearest whole number to put inside the value curve. 

It would be great if the value curve options were in the 255 scale for that effect.

**Comment by AzGilrock** [comment]
This is not specific to the DMX effect its a common issue for all Value Curves because they all use a common dialog.  I actually asked for this same thing when they were created.

**Comment by idleup** [comment]
Can this be done ASAP? I am doing the same thing right now! :-)

**Comment by keithsw1111** [comment]
I wont get to this before Christmas so if someone else wants to take a cut at it they are welcome to do so. Changing the maximum is not the challenge. The challenges come from:
- Handling the conversion from prior versions
- More significantly deciding what the range should be ... I dont think 0-255 is much better than 0-100 ... in reality the range should be setting specific as some settings have more than 256 discrete possible values.
I firmly believe we should change this once to a better target state which is why this is on my list but i have not tackled it yet.

**Comment by AzGilrock** [comment]
You're right it shouldn't be a fixed number of 0-255 either.  It needs to be dynamic.  When I call the SetLimits() function for the curve that should be what sets the limits for the sliders.

**Comment by keithsw1111** [comment]
This is now fixed as of 2017.24
