### ISSUE TITLE
Random crash 2 different computers

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#75]
ver March 13
Workflow:
New sequence, pick MP3, add 50ms timings, add 2 models. 
Add a single effect to model #1, add a single effect to model #2, and then this came up

![image](https://cloud.githubusercontent.com/assets/10568498/6654806/0dcfe3ee-ca9a-11e4-9c27-7079af0ce3f6.png)

**Comment by AzGilrock** [comment]
Did this save a bug report at "C:\Users\steve\AppData\Local\Temp"?  The error window kinda looks like it was trying to copy a file which is done as part of creating the crash report file so maybe the other files are in there.  The backtrace.txt is the most import because the lines at the top will show what function the code was in when it crashed.  Also there were several ways to crash due to how I was trying to capture the mouse in the effects grid and I think I got those ironed out so I'm hoping that fixes some of the crashes.

**Comment by stevegiron** [comment]
Here you go:
0x0052cf9b              RgbEffects::RenderSpirals(int, int, int, int, bool, bool, bool, bool)

**Comment by AzGilrock** [comment]
Usually try to give the top 4 or 5 lines.  You will see where it transitions to no indents and looks more like Windows functions.  But if that line was the top line it probably doesn't matter for this one.  That seems like an unusual spot to crash.

If you want send me the xlights_networks.xml and xlights_rgbeffects.xml files and I'll try to follow the steps you did.  You should have my email from one of the alpha testers emails.

**Comment by stevegiron** [comment]
That was the entire file.  The previous crash only contained the xml files in that folder.

**Comment by stevegiron** [comment]
Unable to reproduce error with 4.0.9 closing issue.
