### ISSUE TITLE
make error on fedora 25

### ISSUE THREAD

**Issue by ccsuhr** [smeighan/xLights#772]
About a week now been unable to make in linux.  Attached error for make command.  have kill folder for xlight and reclone from github and no luck.

file:///home/clsuhr/Documents/error%20fedora%2025.txt

**Comment by keithsw1111** [comment]
We recommend you access the Linux version here: https://launchpad.net/~chris-debenham/+archive/ubuntu/xlights/

If you really want to build the Linux code you either take a copy from when Chris updates the makefiles or you accept responsibility for fixing the makefile. The problem is the code changes often and those making changes only fix them for their own compile tools. Others then take this and update their build tools to work with new/deleted code objects. This can happen days or weeks later.

**Comment by cjd** [comment]
If you attach the actual error output we can have a look - but it is likely that the makefile was simply not up to date at that time.
I update the makefile when I notice a change is needed - or you can install 'cbp2make' and the top-level makefile will automatically rebuild the other makefiles as needed
