### ISSUE TITLE
Not able to move Models up and down in the sequence list.  

### ISSUE THREAD

**Issue by Edwardschristmas** [smeighan/xLights#780]
When moving models up or down in the "Display Elements" tab some will move and other will not.   Examp
![model list](https://cloud.githubusercontent.com/assets/24615212/21282293/cbe6c09e-c3b0-11e6-81b3-d696d595f1e3.PNG)
le pic:

Link to Dropbox:  https://www.dropbox.com/s/udf0nuvt57opdxi/xlights_rgbeffects.xml?dl=0

**Comment by AzGilrock** [comment]
What is that pic supposed to show?

I will say there is a bug with moving models I found a few days ago.  The problem seems to appear if you have multiple timing tracks in the view.  It will move a model and then all of a sudden the selection will jump to another model.  I found if you keep clicking the one you want to move and hit the move button again eventually it will move the one you want.  Seems like the number of failed moves equals the number of extra timing tracks you have.

**Comment by Edwardschristmas** [comment]
The picture was just a reference to the tab where the problem is located.    The description of whats going on is EXACTLY how you described it.  I'll have to try it in another sequence where there are no timing tracks and see if that makes  a difference.

**Comment by Edwardschristmas** [comment]
No problem with sequences that have no timing tracks.  Must be some relation for sure.

**Comment by AzGilrock** [comment]
Yep its definitely a problem.  I must have had only one timing track when I tested this functionality.

**Comment by AzGilrock** [comment]
When I found it I was surprised no one else had reported it then you found it 2 days later.

**Comment by Edwardschristmas** [comment]
I noticed that it was only in Logan's sequences that have numerous timing tracks.  Never noticed it in mine with a single track.  Well glad someone else had the problem that knows how things work.  Thanks Steve and Gil

**Comment by keithsw1111** [comment]
Given this window has been entirely reworked I am closing this issue.
