### ISSUE TITLE
Windows 10 crash when xLights stops "Output to Lights" with LOR controller on USB dongle

### ISSUE THREAD

**Issue by neilsunw** [smeighan/xLights#797]
I have one LOR controller (16 channel) on USB COM3 57600 baud. 
Test works for LOR channels but will crash Windows 10 when I uncheck "Output to Lights".
Sequencer works for LOR channels but also will crash Windows 10 when I unselect "Output to Lights".
Setup has 1 LOR and 14 E131 universes.

xLights (Ver 2016.51) -- desktop PC, Windows 10 Home
Windows 10 Stop code: KERNEL_SECURITY_CHECK_FAILURE

I did not have crashes when I was only using my E1.31 DMX universes and had my LOR channels going to a dummy DMX universe (no light control).

Light-O-Rama Hardware Utility and Sequence Editor are not having any troubles with Windows 10 and USB COM3 dongle.

**Comment by AzGilrock** [comment]
So who sells the dongle and which driver is used to run it?

**Comment by neilsunw** [comment]
original Light-O-Rama dongle (USB to RS485, black) purchased in 2013
http://www.lightorama.org/siteimages/USB485-Front.jpg

**Comment by AzGilrock** [comment]
Ok that's what I thought just wanted to double-check.  I have the same equipment so I'll try to spend some time checking it out this weekend.  It's been reported several times.  Its not easy for us because its not like LOR will tell us all the inner workings of their hardware and driver.

**Comment by neilsunw** [comment]
Thank you, I let Windows 10 auto load the FTDI driver (Microsoft ver 2.12.24.0 9/28/2016)
USB Serial Port (COM3)

My system is running the 64-bit operating system, Intel i5-2500K CPU @ 3.3GHz, 8 GB memory
Windows 10 Home (ver 1607)

**Comment by AzGilrock** [comment]
Good news is I was able to duplicate the blue screen crash using my LOR USB dongle and equipment.  I'm able to prevent the crash with a delay statement after turning off the channels to 0 so my theory is we have a race condition where data can still be sent to the driver after we close the port and that's what's causing the blue screen.  So even though the delay seems to fix it I'm not sure it's the best fix so looking into it deeper cause if I'm right it could affect other USB output devices.

**Comment by newusertothis** [comment]
Hello.... I am new to this forum.  I am having the exact same issue, using the same equipment.  I have never used Xlights before and need some help   I uninstalled the "production" release and used the latest " Beta" release thinking the fix might be in there.  However, it didn't fix the crash issue.  Please help!

**Comment by AzGilrock** [comment]
Sorry nothing else I can do.  The change I committed in January fixed the problem on my setup so there is no other way for me to troubleshoot it.

**Comment by newusertothis** [comment]
Thanks for the quick response.  However, I am confused.  What did you do?  The "delay statement" ? are you an Xlights programmer?  sorry for the newbie questions. I am fairly savvy when it comes to this, but just learning Xlights.

Thanks in advance

**Comment by AzGilrock** [comment]
Yes I sometime program. I checked in that change and it was the only way I could get it to quit blue screen crashing on my system.  You sure you are running 2017.6?

**Comment by newusertothis** [comment]
Yes.  If I can sequence then I'm fine... But I assumed since I can't test properly, I'm toast from the beginning.  I haven't tried yet

On Mar 7, 2017 7:08 PM, Gil Jones <notifications@github.com> wrote:

Yes I sometime program. I checked in that change and it was the only way I could get it to quit blue screen crashing on my system. You sure you are running 2017.6?

**Comment by newusertothis** [comment]
2017.6  Feb 27, 2017


Good Morning,


I made sure I turned off everything and it crashed right after I unclicked "output to lights".   I really want to use this software as it looks very useful and powerful for design.


Thanks,


Mike


________________________________

**Comment by AzGilrock** [comment]
Well you can always quit using the LOR dongle and find a way to run he boxes using DMX.  You also not try to run the lights from xLights.  Just sequence in xLights and run from the FPP.  All we are doing is sending a block of zeroes to turn off the lights and then disconnecting the output so I have no idea why that causes a crash.  Without having inside info from LOR I can't do anything more than what's been done.

**Comment by keithsw1111** [comment]
So this problem occurred with 2016.51 as well. That is interesting because it means it occurred with the code prior to the refactoring of all the code that sends output to the controllers.

When you say you are having the same problem I assume you mean you are also getting a BSOD ... a BSOD cannot occur directly from our code ... it actually occurs in the driver as a result of an action we trigger in our code. At this point to progress this one of a couple of things need to happen.

- First you need to check you are running the latest drivers for your hardware. In fact can you share details about which drivers you are using.
- Second we need the BSOD details. What does the BSOD say happened exactly.
- Three ... exactly which device are you using ... it would be nice to know if other users are using the same hardware and having or not having problems. I dont just want to know the brand ... I want to know the specific version.
- Four ... can you share your networks file so we can see how you have it set up

**Comment by newusertothis** [comment]
Thanks for the quick response.  I'll forward you all that info this weekend.


Much thanks!!!


Mike


________________________________
