### ISSUE TITLE
Layer buffer question

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#801]
When changing an effect where the layer buffer size has been set, the buffer switches to 100%. 
Is there a way to change an effect between timing marks and have the layer setting not switch?

www.stevesimages.com/xl4/buffer-question.mp4

**Comment by keithsw1111** [comment]
First of all Steve while these are called layer settings they are really nothing of the sort ... they are effect settings.

We used to have a problem where users played with these settings particularly the transition in/out and then only realising later and had to manually go back and change them all. So that way was not perfect either. 

Someone else suggested we add an update button like the colour panel ... again not ideal as it was not clear what was being updated ... all fields, just the sub buffer etc.

The only thing i can think of is to add a checkbox on the layer and buffer panels to lock the settings and stop them resetting when you change effect types. That way when you want them locked you have it ... when you dont ... you dont.

Would that work?

**Comment by stevegiron** [comment]
The checkbox would be most welcome.

**Comment by Clyde-L** [comment]
Yaaay, I like this request :)

**Comment by keithsw1111** [comment]
This was in 2017.4 as a checkbox that stops it being reset.
