### ISSUE TITLE
Bug  Importing of LOR timing marks do not show up in sequence

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#805]
I showed this to the group on the Wed chat session of 01.18.17.  Some could create the bug others could not.    I am running Win 7  the bug showed on xLights ver 2016.54, I upgraded to .56 and it was still there.  Here are the steps,

Load xLights  (duh)
File / New Sequence / Musical Sequence.   navigated to C:\Program Files\xLights\ Audio 2017, selected my Mp3 files
In the Sequence settings window selected 20fps
In the Sequence settings window selected the Timings tab, clicked Import
Navigated to  Libraries \ Light-O-Rama\Sequences clicked drop down selected  LOR (*.lms)
Selected 2015 Sec 1 Three Ships Wonderful Xmas.lms  clicked Open  and waited until the window  came up with Unnamed0 clicked it, clicked OK,    2015 Sec 1 Three Ships Wonderful Xmas:Unnamed was then listed in the timing grids selection window, clicked Done.
The screen re-drew to the Sequence tab and the 2015 Sec 1 Three Ship radio button was there, in teal.  Click on that radio button and there are no timing marks.

What other details would you need?

**Comment by AzGilrock** [comment]
I bet it will work if you create the sequence first and then open up Sequence Settings and import the timings.  The way you are doing it technically the sequence has not been created yet when the timings are attempted to be imported.  I wish we hadn't ever given the option to do it that way.

**Comment by AzGilrock** [comment]
Well I see what's wrong and it's like I suspected it will work if you import after sequence creation.  The strange thing is it looks like this would have never worked before sequence creation but there is code to handle it.  The problem is I have to round the imported times to the nearest frequency mark for the sequence timing but at that point the sequence object didn't have the value stored yet.  I have it working now though since I have the frequency stored in another object I can access.
