### ISSUE TITLE
DMX model dissappears

### ISSUE THREAD

**Issue by djgra79** [smeighan/xLights#821]
When creating a 2nd DMX model (moving head) in the Layout screen, whilst assigning channel numbers for Pan, Tilt & RGB, the image of the model disappears. The model still exists but the image is gone, so I can no longer click on it. It also means once in Sequencer tab it does not show up on house or model previews.
![dmx missing](https://cloud.githubusercontent.com/assets/25606394/22683852/0724e17c-ed6e-11e6-8b74-788b8ef43a7c.jpg)

**Comment by AzGilrock** [comment]
It's because you entered the channel assignments incorrectly.  You need to subtract 14 from all the channel numbers because its a new model and they start at 1 again.  That makes it easy to just copy/paste a new DMX model and then  all you gotta change is the start channel I don't make your figure out what all the absolute channel assignments are.
