### ISSUE TITLE
Bug Crash when editing at the node level from a copy and paste

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#833]
I copied and pasted a section from earlier in the wreath model to another section in the wreath model in the seq.  The results did not line up so I was manually adjusting the shortest cells to one more to the left  at the node level.  When I got to node 135 the bug report happened.  NOTE: this copy and paste in the wreath model  is from the section of the sequence that was an LOR import.   Not sure that matters 

Also, for some reason I get this error when trying to attached the crash report zip file to this e-mail  We don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. Let me know if you want a copy of that zip (RAR file) and I can e-mail it to you.

**Comment by AzGilrock** [comment]
Pretty sure you can attach zip files if you actually use an internet browser to interact with GitHub.  But if you hit Ok on the debug report window then it uploaded it us already and if it was something obvious we could fix then it was fixed already.  Otherwise we would need detailed instructions for how to reproduce the problem.  Since this was opened in March I'm going to close and have you create a new issue if you have further problems.
