### ISSUE TITLE
Crash when creating new sequence with no timing track selected

### ISSUE THREAD

**Issue by smeighan** [smeighan/xLights#84]
If i create a new sequence and do not select a timing track, xlight crashes
I am using version http://nutcracker123.com/nutcracker/xl4/xLights_Nutcracker_20150318_2146.exe

**Comment by RichardRennII** [comment]
Sean
 I have created a new sequence with no timings and no crash I am using the latest dated 3-18-15

**Comment by AzGilrock** [comment]
I confirmed this bug last night but didn't have time to fix it.  There's a specific way to cause it because it's a few pointers that are not set until an event gets fired in the current design and there are several ways you can cause that event to fire and may not realize it but you just avoided the bug.  It took me awhile to figure out how to cause it.

**Comment by RichardRennII** [comment]
okay so I danced around it some how
