### ISSUE TITLE
2 is Unmask Adds White Background

### ISSUE THREAD

**Issue by MCStoff** [smeighan/xLights#856]
Windows 10, 64 bit 2017.12.

First layer is Spiral with three colors, none of which are white.  Layer blending set to 2 is Unmask.
Second layer is Shockwave.  Shockwave reveals colors of palette, but instead of a black (clear) background, the background is white.

**Comment by AzGilrock** [comment]
Paste a picture cause I have no idea whether first layer means its on top or bottom.

**Comment by stevegiron** [comment]
Set the effects so that Layer 1 is the mask and 2 is normal. White will go away.

**Comment by AzGilrock** [comment]
So I looked into the code to see why this happens.  It turns out that is the result of how an Unmask is calculated.  We convert the top and bottom color to HSV color space so the V or Value part of the HSV color is used and if greater than 0 then it is used to replace the V of the other color.  So lets say I have a white On effect below a Spirals set to 2 is Unmask.  In the spots where there is black between the spirals the HSV is 0,0,0 for black and for the On effect the HSV is 0,0,1.  So when the On effect is used to "Unmask" the upper color it replaces its V value so the final color results in HSV = 0,0,1 so you actually will see white.  I believe the confusion is you expected an Unmask to be an inversion of what Mask does and it's not.

Everyone has been using this color blending algorithm coded this way for years so we can't change the algorithm

**Comment by stevegiron** [comment]
The way I've worked around this is to sometimes use a custom color of 1,1,1 that is too low to actually turn the LEDs on, but still not 0,0,0 in the software to create white where it's not expected.

**Comment by AzGilrock** [comment]
That will work for Mask but not Unmask.  The brightness of the color being used as the Unmask is what determines brightness here.  So if the bottom color is White and is used to Unmask an RGB color of 1,1,1 then you will still end up with White.

**Comment by AzGilrock** [comment]
To see the concept put a Red (255,0,0) On effect on top and Unmask it with half white (128,128,128).  The result will be a color that looks half red (128,0,0) because RGB 255,0,0 is HSV 0,1.0,1.0 and half white is RGB 128,128,128 which is HSV 0, 1.0. 0.5.  So replace the red's V of 1.0 with 0.5 and you get an HSV value of 0, 1.0. 0.5 which is RGB 128,0,0 a half darkened red.

**Comment by AzGilrock** [comment]
Well if I wasn't clear.  This isn't changing.
