### ISSUE TITLE
Custom Model Angle Issue

### ISSUE THREAD

**Issue by TKW1969** [smeighan/xLights#870]
I created a matrix with both sides on a 45 degree angle. It was only 7 strings tall skipping a row in between each string. But in the layout the sides or on what looks like a 22.5 degree angle.  I am using 2017.14 64bit version.
[roof matrix.xlsx](https://github.com/smeighan/xLights/files/1053445/roof.matrix.xlsx)

**Comment by AzGilrock** [comment]
First thing I can say is its very unlikely we will change how custom models data is displayed.  It would break all existing layouts.  Second is we can't just look at your Excel spreadsheet and know how that would look because the appearance of a custom model depends on the shape of the rectangle you created when you import the model.  Are your X and Y size values equal?

**Comment by TKW1969** [comment]
No problem, and no my Width and Height are not the same. When you do that the ends are only about 10 degrees. I have found out that it takes a 6 to 1 ratio to get the ends on a 45 degrees angle. the width has to be 6 times the Height no matter what size the matrix is.

**Comment by AzGilrock** [comment]
Yeah I forgot the X and Y will only be the same if its a square.  But I used your Excel data and created a custom model of size 161x13 and pasted the data and it looks great to me.  If you size it so that the vertical and horizontal distance is equal which is how you designed it inside Excel then it sure looks pretty close to 45 degrees to me.  I don't see an issue so I'm closing this.

![angle](https://user-images.githubusercontent.com/2024669/26859649-0ef5b16e-4aee-11e7-9719-f2f62a01732c.png)
