### ISSUE TITLE
After upgrading to .17, now getting Unable to load RGB effects file

### ISSUE THREAD

**Issue by FlyingPlanes99** [smeighan/xLights#875]
Everything was working fine in .16 x64 but when I just upgraded to .17, I started getting the error above then another error after it saying 'XML parsing error 'not well-formed (invalid token)' at line 4 and all of my layouts are gone.  

I've uploaded to the same share as before the zip file with my files so you can inspect them.

**Comment by AzGilrock** [comment]
Actually the bug in your file is what version .17 fixed but your file had already been corrupted by version .16.  I'll edit the file and fix it for you when I can today.

**Comment by FlyingPlanes99** [comment]
Thank you.

On Jun 20, 2017, at 9:03 AM, Gil Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually the bug in your file is what version .17 fixed but your file had already been corrupted by version .16. I'll edit the file and fix it for you when I can today.

**Comment by AzGilrock** [comment]
Yeah if you edited a model that had individual start channels it saved the attributes wrong because an extra space got inserted in the string name.  But you would not have seen the error until next time you ran the program so that just happened to be when you upgraded.  I posted about this issue last night on Facebook.  Try the attached file...you need to unzip it.  I'm not at home to test it but there were only 3 space characters that needed to be deleted.

[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/1088281/xlights_rgbeffects.zip)

**Comment by FlyingPlanes99** [comment]
That worked!  Thanks for your help

**Comment by AzGilrock** [comment]
No problem.
