### ISSUE TITLE
Crash on render and export to LCB file

### ISSUE THREAD

**Issue by PKingRoch** [smeighan/xLights#878]
[xLights_dbgrpt-11032-20170626T192529.zip](https://github.com/smeighan/xLights/files/1104899/xLights_dbgrpt-11032-20170626T192529.zip)
In the sequencer, I selected a model created from separate models that contain additional models that make up the prop, in this case 'Tiny Pixel Trees', 'PoleStar 1' or 'Polestar 2'.  Right clicked and selected 'Render and Export Model'.  Crashes every time and debug report is included here.

xLights 2017.14 - 64-bit Windows.

**Comment by keithsw1111** [comment]
I went back to 2016.51 and this problem dates at least back to then. The problem seems to be that the render for export creates a pixel buffer equal to the size of the group ... 1680 channel but then tries to index into it using the absolute channel number ... and it crashes.

As a workaround ... dont use the render and export. Instead manually render all and then just choose the export option ... this avoids the problem as the crash occurs in the render of the group.

**Comment by PKingRoch** [comment]
That works for me!  Thanks Keith!!!

**Comment by PKingRoch** [comment]
Correction.  While it doesn't crash, the LCB file is also empty, so it doesn't work.  I selected the "Render All" Icon in the taskbar, then right clicked and exported the model.  The resulting LCB file for the tiny pixel trees is attached.
[Tiny Pixel Trees.zip](https://github.com/smeighan/xLights/files/1108635/Tiny.Pixel.Trees.zip)

**Comment by AzGilrock** [comment]
I thought we never really supported exporting a model group we just never put in code to prevent the attempt.

**Comment by PKingRoch** [comment]
That would be a feature I _really_ need considering my plans this year.

**Comment by AzGilrock** [comment]
If you _really_ need a feature the trick is to make sure your name shows up high on the donation list.

**Comment by PKingRoch** [comment]
I have no problem with that - where is the list so I can get an idea of what I can contribute?

**Comment by AzGilrock** [comment]
You don't get to see the list....lol.  Its like bidding on a government contract...you don't get to see what your competitors are bidding.  But in all seriousness never donate expecting anything in return because you should be donating based on being happy with what you've already received.

**Comment by PKingRoch** [comment]
OK, I used the program pretty heavily last year and I've invested quite a bit in it this year, so I just made a donation because you guys deserve it.  I hope you can fix this bug or add it as a feature because with my setup this year, I really need it.

**Comment by AzGilrock** [comment]
Thanks but I was really kidding whenever I talk about donations.  I actually don't have visibility into the donations.  It all goes to Sean and he manages that stuff.  He will distribute to the active developers on occasion and also use it for costs like when xLights needs to pay for something at an Expo for example.  Sean is very generous and almost never wants to keep anything for himself.  I do get to see a list maybe once a year so its sometimes many months after someone donates before I might know about it.  I'm always impressed to see there are some people out there giving really nice donations and I didn't know because they never mentioned a word about it and there are others I see that are donating on a regular basis.

**Comment by keithsw1111** [comment]
Another workaround for you would be to create a shadow model (say a single line) covering the same range of channels as the group and then export it. I suspect that will do what you need.
I have never used LOR and so I tend to take whatever xlights does as gospel in this area. When I change things as long as it did what it did before I just have to assume is correct. I guess what i am saying is unless Gil or Dan know what needs to be done here this is not likely to change unless it is just to prevent your choosing to export model groups ... that is something I could do ... but it wouldnt help you at all.

**Comment by PKingRoch** [comment]
If the single line isn't in the shape of my prop, how will the effects be mapped?  That's why I created the models the way I did in the first place.  Each of the models or groups of models builds on the previous models to map effects onto them as a whole.  I expect to have even more groups like an all Pixel group that I will want to drop effects onto and export as well.

If I could find any other workaround I would love to hear it.  This has me stopped on sequencing until I can find a way to make this work.

**Comment by keithsw1111** [comment]
Dont drop effects on the single line. Just use it for the export. Because it maps to the same channels it will pick up the data from the models which seems to me to be all you need. Dont take my word for it ... try it.

The thing you need to realise is where you drop the effects and which model you export dont need to be the same. If you drop an effect on all models but export the tree the all models effects that impact the tree will be included in the export.

**Comment by PKingRoch** [comment]
Ahhh, I see now.  That is a work around I can get to work here.

I'd love to see this fixed, just because it is more intuitive, but this work around unblocks me.

Thank you so much!!!

**Comment by dkulp** [comment]
Fixed in 1eb23b2a625d990e1884143200d03855fc852cd9
