### ISSUE TITLE
2017.18 XML parsing error when importing SUP File

### ISSUE THREAD

**Issue by FlyingPlanes99** [smeighan/xLights#880]
Trying to import a SUP effect file but whenever I try, I keep getting a 'XML parsing error: 'not well-formed (invalid token)' at line 120757.

I've uploaded the ZIP file so you can see what I'm using when the error occurs.

**Comment by AzGilrock** [comment]
The problem here is the SuperStar file has incorrect XML.  You can fix the file manually.  Open in Notepad++ and goto the end of the file.  You will find the end tag "</SuperStarMetaFile>" listed 3 times.  There should only be one of them so delete 2 of those end tags and save the file and import it again.
