### ISSUE TITLE
Some sequences never finish rendering (Linux)

### ISSUE THREAD

**Issue by m00dawg** [smeighan/xLights#900]
I seem to be having a Linux specific problem (or rather the current stable version of xLights on Windows does not seem to be having this issue) where some sequences get stuck rendering indefinitely which should normally only take a few seconds. In looking at `top` on Linux, it seems to indicate xLights is stuck waiting on some sort of event as it's not consuming much CPU. I've include the sequence plus an output of strace and ltrace in case it proves helpful. The debug output doesn't show that anything is wrong:

```
tim@lindawg ~ $ xLights  --debug

(xLights:29333): Gtk-CRITICAL **: IA__gtk_window_resize: assertion 'width > 0' failed
WaveForm - glVer:  3.3.0 NVIDIA 381.09  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
EffectGrid - glVer:  3.3.0 NVIDIA 381.09  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
TimeDisplay - glVer:  3.3.0 NVIDIA 381.09  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
ModelPreview - glVer:  3.3.0 NVIDIA 381.09  (GeForce GTX 1070/PCIe/SSE2)(NVIDIA Corporation)
```

This started happening perhaps a week ago. I'm honestly not sure if it's Linux specific but I don't have a way to build the sources on Windows currently so haven't been able to test anything other than the prebuilt binaries that are available on xlights.org.

There doesn't seem to be much correlation at least with my models. Seems like different sequences get stuck on different models (in looking at the rendering details dialog box).

[bug.zip](https://github.com/smeighan/xLights/files/1236812/bug.zip)

**Comment by cjd** [comment]
Can you please grab the /tmp/xLights_l4cpp.log logfile from your system?
I gave this a test with your layout/sequence with both current git and the last few releases - and was unable to reproduce.
Which wxwidgets build are you using? (ie: the one built by xlights or a system-provided one)
If you restrict xLights to one cpu via 'taskset -c 0 xLights' does it still occur?
Are you able to try with some of the appimage builds from https://www.adebenham.com/xlights-linux/ ?
That might help to narrow down when the problem was introduced

**Comment by m00dawg** [comment]
Tried using taskset for both the git version from yesterday and this morning as well as the latest deb from the PPA (2017.22-0~4052~ubuntu16.04.1) with and without taskset. They all get stuck in the same place. For the git version I believe I am using the version of wxWidgets that comes with it. I uninstalled the system versions to make sure. For the latest git I did a full make clean and make all (which I believe rebuilds wxWidgets if I'm reading the Makefile right?)

xLights cpp log is attached. I didn't see anything of note with debug mode off or on. I thought initially maybe it was an issue with Windows vs Linux paths (though I had the problem before I tried it on Windows and updated the pathing). Fixed those references at least for the images I have in the sequence. On that note I thought there might be an issue with images rendering (since I am using some animated gifs in places) so I tried removing those effects but it still seems to get stuck in the same spots.

I'm now trying to go through the sequence to see if removing effects makes it work to see if I can isolate the problem.

[xLights_l4cpp.log.gz](https://github.com/smeighan/xLights/files/1237217/xLights_l4cpp.log.gz)

**Comment by keithsw1111** [comment]
Can you send us Filename: /home/tim/Holiday Lights/xLights/media/The Legend of Zelda Main Theme Medley.ogg
2017-08-20 

There are warnings in the log that are a concern ... which means the audio data is incompletely loading ... which in turns blocks rendering that needs the audio ...

2017-08-20 12:06:09,000 139868898633472 log_base [WARN] DoLoadAudioData: This shouldnt happen ... read [11836928] + nb_samples [1024] > _tracksize [11836928] .
2017-08-20 12:06:09,000 139868898633472 log_base [DEBUG] DoLoadAudioData: Song data loaded in 273.

**Comment by m00dawg** [comment]
I might have to submit that privately as it's from the Zelda 25th Anniversary album that came with Skyward Sword but I certainly can do if there's a means to do that? You got me thinking though about trying other formats and, sure enough, a lame-encoded MP3 using a constant bitrate of 320kb allowed me to properly render the scene. I have other shows that use OGG files without issue so I gotta think there's something causing that which I may wanna play around with. But the MP3 worked so I at least have a work-around for the interim.

**Comment by AzGilrock** [comment]
All because some OGG files work doesn't mean there's not an issue with others.  Its like when we first got MP3 support we ran into a few MP3 files that caused a problem.   There are so many encoders out there that sometimes you get files that are improperly encoded so it's a matter of how much error checking is put into the decoder.

**Comment by m00dawg** [comment]
Indeed, barring a DMCA claim against me or GitHub I'm still happy to provide the test files :) Just probably shouldn't publicly. Of note all my ogg's were encoded by me using `oggenc -q8 <input>` where <input> was usually a FLAC file. This was on Linux but it's been over the course of a few years now so chances are it may have been from various versions of oggenc.

I have a feeling it may be perhaps one of the effects that sync's to music perhaps causing it. I'm gonna test that theory as soon as I have time to have a good xLights session this week.

**Comment by keithsw1111** [comment]
So send it to me directly.

**Comment by m00dawg** [comment]
Sent to the e-mail from the git log. As noted in the e-mail, I sent you a different sequence and song because it turns out I accidentally fixed the sequence mentioned here. I re-encoded the OGG using different quality settings (-q10) and that somehow managed to allow the render to complete. So I tried re-encoding the OGG back to the settings I used previously (-q8) and it still worked. While doing this I neglected to copy the original OGG that didn't work so kinda messed up the test case in doing so.

I've left the sequence I did send you untouched (and confirmed it gets stuck rendering on Linux). Curious what you find here and depending on that I may try to just re-encode the files and see if that does it.

I think Gil is onto something there with OGG being finicky but am not sure what is going on specifically. As I recall when I used Vixen a few seasons ago VBR codecs were known to have issues with sequencing and timing. Since OGG files are VBR by default (in fact I couldn't figure out a way to make them CBR at all), wondering if that is perhaps causing shenaigans in xLights too? I use it mostly because it seems to have better quality at the same bitrate, but an MP3 at 320kbps is likely more than sufficient for low power FM anyway and can simply use that if it's better implemented. If given the option my full preference would be to use FLAC since that's the format I use for my music for listening  but I suspect there is a size concern say for when using FPP?

**Comment by keithsw1111** [comment]
The way we handle audio is we feed the audio file through the libavcodec library. The same library that sits behind software like VLC. From it we get essentially a WAV file which is what we keep in memory and process. This data is then passed into a spectrum analyser that does a frequency breakdown of the song in case you decide to use the VU Meter. All of this is done on background threads but when you go to use the data it checks to see if it is done and if it isnt it waits. From your original log I can see this happening ...

2017-08-20 12:06:08,457 139869405489984 log_base [DEBUG] Setting media file to: T:\Holiday Lights\xLights\media\The Legend of Zelda Main Theme Medley.ogg
2017-08-20 12:06:08,457 139869405489984 log_base [DEBUG] Memory allocated for frame data. Frames=10736, Channels=20404, Memory=219057344.
2017-08-20 12:06:08,726 139869405489984 log_base [DEBUG] Preparing to load song data.
2017-08-20 12:06:08,726 139869405489984 log_base [INFO] Audio file loaded.
2017-08-20 12:06:08,726 139868898633472 log_base [DEBUG] DoLoadAudioData: Doing load of song data. ****** NOTE THIS IS ON THE BACKGROUND THREAD CONVERTING OGG to WAV
2017-08-20 12:06:08,726 139868898498304 log_base [INFO] DoPrepareFrameData: Start processing audio frame data. ****** THIS IS ON YET ANOTHER THREAD ABOUT TO DO THE SPECTRUM ANALYSING
2017-08-20 12:06:08,726 139868898498304 log_base [INFO] DoPrepareFrameData: waiting for audio data to load. ******* BUT THE WAV FILE CONVERSION HAS NOT COMPLETED SO IT WAITS
2017-08-20 12:06:09,000 139868898633472 log_base [DEBUG] DoLoadAudioData: Song data loaded in 273. ****** THIS IS THE WAV FILE CONVERSION COMPLETING
2017-08-20 12:06:09,726 139868898498304 log_base [INFO] DoPrepareFrameData: waiting for audio data to load. ****** BUT THE SPECTRUM ANALYSER IS STILL WAITING ... MAYBE WE HAVE A BUG BECAUSE THIS SHOULD BE RELEASED
2017-08-20 12:06:13,727 139868898498304 log_base [INFO] DoPrepareFrameData: waiting for audio data to load. ***** STILL WAITING AND IT SEEMS TO BE TRYING TO RENDER AN EFFECT THAT NEEDS THE DATA SO IT WAITS FOREVER

Chris @cjd  is it possible the mutex code I have is not correct on Unix?

**Comment by cjd** [comment]
m00dawg - can you send me the problem ogg file to test on  my system?
Also what linux distro/release are you running on?

**Comment by m00dawg** [comment]
Sent to the e-mail noted in the git logs. Let me know if you didn't receive it!

I'm running on Linux Mint 18.1 which itself is based on Ubuntu 16.04. Some further info just in case it proves helpful:

```
tim@lindawg ~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

tim@lindawg ~ $ uname -a
Linux lindawg 4.11.8-ryzen #1 SMP Sat Jul 1 14:37:42 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux

tim@lindawg /etc/apt $ cat sources.list.d/official-package-repositories.list 
deb http://packages.linuxmint.com serena main upstream import backport 

deb http://archive.linux.duke.edu/ubuntu xenial main restricted universe multiverse
deb http://archive.linux.duke.edu/ubuntu xenial-updates main restricted universe multiverse
deb http://archive.linux.duke.edu/ubuntu xenial-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
deb http://archive.canonical.com/ubuntu/ xenial partner

```

**Comment by cjd** [comment]
I've reproduced the problem now on my system (Ubuntu 17.04) so it isn't specific to your distro.
Looking at the code currently

**Comment by cjd** [comment]
I've reproduced the problem now on my system (Ubuntu 17.04) so it isn't specific to your distro.
Looking at the code currently

**Comment by cjd** [comment]
It does look to come down to problems with _trackSize.
Because it is smaller than expected xLights never thinks it is fully loaded.
That it happens only on linux suggests a difference in OGG handling from libraries.
I tested a quick fix/workaround by modifying AudioManager.cpp
In the DoLoadAudioData function where it notes:
           // I dont understand why this happens ... add logging when i can
          logger_base.warn("DoLoadAudioData: This shouldnt happen ... read ["+ wxString::Format("%i", (long)read) +"] + nb_samples ["+ wxString::Format("%i", frame->nb_samples) +"]  _tracksize ["+ wxString::Format("%i", (long)_trackSize) +"] .");

If I add a line:
     _trackSize=read + frame->nb_samples;
 
To force the _trackSize to what is expected it worked without issue.
But not certain of any side effects of that.  I'm thinking it would only potentially cause an extra frame. 
It shouldn't impact any cases where we weren't already hitting a media load issue.
@keithsw1111 what do you think about that (before I submit such a change)
                                        }

**Comment by AzGilrock** [comment]
I remember when working with MP3's having to add enough extra bytes to cover an additional frame because when you did the math for how many bytes there should be in the track it fell short.  I also remember not liking some of the formats like MP3 where you pretty much had to read the entire file once to determine exact length.  You can see on line 1621 of the AudioManager.cpp file where it already had a fudge factor built in.  Maybe that number was too small.  We kept increasing it as we ran into files that crashed.

**Comment by m00dawg** [comment]
I noticed xLights doesn't support WAV directly (didn't check for AIFF) but if it's internally converting to that, perhaps that might be a good feature to have as a work-around? Converting to WAV is no big deal for me. I could see others finding that a bit inconvenient perhaps since FPP doesn't currently support WAV last I checked. I'd just convert the files to OGG for FPP. Although on that note, assuming it doesn't cause I/O issues, SD cards are big enough to where I don't think the extra size of WAV files is a problem at all for something like FPP.

**Comment by keithsw1111** [comment]
I think you will find xlights can load wav files.

**Comment by keithsw1111** [comment]
BTW ... the reason I closed this is because it is fixed for the next release.

**Comment by m00dawg** [comment]
Ooops sorry I thought you just closed the code PR Chris made. Werd, if it's fixed I'll stop talking :) (Also I swore I tried loading a WAV file in xLights and didn't see them in the file browser when selecting 'xLights Audio Files' but sure nuff I checked again and they showed up - thanks for the tip!)

**Comment by cjd** [comment]
When you choose an audio file there is the option for "FPP Audio files" or "xLights Audio files" to be used as the filter (down the bottom right of the dialog)
By default "FPP Audio files" is selected - and that doesn't include WAV.  That would be what you are seeing.
From SeqSettingsDialog.cpp
wxFileDialog OpenDialog(this, "Choose Audio file", wxEmptyString, wxEmptyString, "FPP Audio files|*.mp3;*.ogg;*.m4p;*.mp4|xLights Audio files|*.mp3;*.ogg;*.m4p;*.mp4;*.avi;*.wma;*.au;*.wav;*.m4a;*.mid;*.mkv;*.mov;*.mpg;*.asf;*.flv;*.mpeg", wxFD_OPEN | wxFD_FILE_MUST_EXIST, wxDefaultPosition);

**Comment by m00dawg** [comment]
:rocket: :guitar: 

It was just me not seeing the obvious WAV file in the list is what it actually was haha.
