### ISSUE TITLE
Lower GLIBCXX_3.4.20 requirement

### ISSUE THREAD

**Issue by probonopd** [smeighan/xLights#919]
Currrently the AppImage refuses to run on many systems including Ubuntu 14.04 with

```
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-7061/usr/bin/xLights)
```

This is because it requires a "too new" `libstdc++.so.6`. Do you think you could compile against an older libstdc++.so.6, e.g., the one that comes with stock Ubuntu 14.04?

The same goes for `libkeyutils.so.1` and `libgpg-error.so.0`.

It is generally a reasonable practice to target the oldest still-supported Ubuntu LTS or something like that, in order to increase compatibliity with older than the most recent distributions.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/277155815#L695-L699

**Comment by cjd** [comment]
The problem is that Ubuntu 14.04 is too old for a bunch of libraries (mainly the ffmpeg-related ones - but also a few others) so it can't be simply compiled on that.
Ubuntu 15.04 was the oldest release I could get xLights working on without having to backport ffmpeg.
If I can find a suitable repository with new enough ffmpeg libraries for 14.04 I can probably get it working on there.

**Comment by probonopd** [comment]
What version of ffmpeg is the absolute minimum required?

**Comment by cjd** [comment]
I thought back to why I limited building to vivid or later and realised that it was because in the past I build the appimage from the ubuntu package (which only compiled on vivid as it couldn't depend on PPAs)
Since I recently changed how I build the appimage to create it directly I don't have this limitation anymore :)
I found a suitable ffmpeg ppa at ppa:kirillshkrogalev/ffmpeg-next - but then hit the next issue :(
xLights uses some c++14 features which are not supported in gcc-4.8 as in trusty (not fully supported until gcc-5)
I can add a ppa for a newer gcc from ppa:ubuntu-toolchain-r/test which allows xLights to compile/run
But building the AppImage ends up depending on the newer glibc from gcc-5 (and so it can't run on 14.04 without adding that PPA)
I'm now looking into if there is a way to build with the newer gcc but only depend on the standard glibc from 14.04

**Comment by cjd** [comment]
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 may help here

**Comment by cjd** [comment]
I think I have it working now.
Can you download/test https://www.adebenham.com/wp-content/uploads/xlights/xLights-2017.29-bcfbc17.glibc2.17-x86_64.AppImage and let me know if it fixes things?
If so I will adjust my build recipe to work that way in the future

**Comment by probonopd** [comment]
Works now. Thank you very much! 👍
