### ISSUE TITLE
Export to LOR - Fade vs intensity

### ISSUE THREAD

**Issue by Brandonw88** [smeighan/xLights#929]
When converting a sequence into Light O Rama, the fades are shown as intensities in LOR, causing flickering when fading the lights.  this flickering is basically the frame rate at which they fade and it is worse at lower intensities.  this is not an issue when using LOR's fade function, this function render's the fades smooth without flickers.

It would be nice if Xlights could convert fades to LOR fades rather than LOR intensities.  Thanks

**Comment by AzGilrock** [comment]
Can you tell us how to do that?

**Comment by AzGilrock** [comment]
I don't remember the LOR sequences having anything like that.  You need to show us the difference between the two in the LOR XML.

**Comment by dkulp** [comment]
The intensity effect can have start/ends, like 

`<effect type="intensity" startCentisecond="2798" endCentisecond="2928" startIntensity="100" endIntensity="0"/>`

The issue is that when we export, we have no idea that data is a fade or not as we just have the channel data at any given time.  Thus, we'd have to look at the channel data over a period of time and see if it follows a ramp up/down.

**Comment by AzGilrock** [comment]
Ok I hadn't looked so I thought we were already using those start and end intensities.  Yeah it seems like we could do a better export if we used the sequence since we know where the fades are but I'm not sure anyone wants to spend that time.

**Comment by dkulp** [comment]
Using the sequence wouldn't really help much...  what if the fade is due to a morph tail?   Or due to the "3d" effect of a pinwheel/fan?  or similar.   

There are ways to do it... when we import Vixen and HLS files, we do go through all the channel data and look for things that look like ramps and attempt to map those to longer on effects with start/end values.   Thus, the code is "somewhat" there.    That said, it would likely require a large re-write of the LMS export code to really use it.    As Gil said, not sure if anyone feels like spending the time enhancing the xLights->LOR stuff.   Folks should just start using xLights and drop LOR.  :)

**Comment by Brandonw88** [comment]
Thanks for the response on this. I realize this request may not be something that anyone really cares about.   I may just look into using x lights in the future.

**Comment by AzGilrock** [comment]
With the introduction of LOR S5 I don't see us trying to make the export to LOR any smarter.
