### ISSUE TITLE
Model group selecting

### ISSUE THREAD

**Issue by RobertVan** [smeighan/xLights#940]
Would be nice if you could click on a prop to add it to a model group

**Comment by keithsw1111** [comment]
I have no idea what this request means.

**Comment by RobertVan** [comment]
On the layout tab, when you create a model group. To be able to click on the physical drawn model to add it to the group. If possible. It was just a thought to make thing easier. 

Please excuse brevity and mistakes as this was sent from my iPhone

**Comment by AzGilrock** [comment]
I don't like this idea because you would have to create a special mode that is turned on / off to know whether you actually want to select or add.  Plus the selection logic when you click would make this very error prone.  When you click there could be many overlapping model envelopes and you're not always sure which model the program is going to select.

**Comment by keithsw1111** [comment]
I agree. I dont think this is practical because of overlapping models. For those without them it makes sense but we have to handle all cases.
