### ISSUE TITLE
Wave Ramp is not smooth

### ISSUE THREAD

**Issue by PKingRoch** [smeighan/xLights#945]
I'm 64-bit windows xlights v31. I'm trying to get a sine wave across all of my pixel elements in my display with a ramp on the speed from 0 to 20. The effect I'm looking for is I want the wave to speed up over time. Right now, it looks like every speed increase drops frames from the gradual increase I am doing; it looks like the render shifts to the left a frame or two each time the speed increases for my Right to Left Wave Direction. Is there a way to smooth this out so I don't get the drops? I'm doing this increase over 20 seconds with 1012 waves, 69 for thickness, 72 for scale height with white, red and green for the pallet colors.   I did a ramp - since that's what I'm after with a starting value of 0 and an ending value of 20. It increases in speed as I expected, but frames are being dropped when the speed increases instead of having a smooth increase in speed.  Video of the issue is on facebook - https://www.facebook.com/PkingRoch/videos/10155457680548941/

**Comment by AzGilrock** [comment]
None of these effects had value curves when they were created so the underlying algorithms were never designed to make changes like this smooth.  The result you get when a parameter changes with the value curve is the wave is drawn as if that curve was running at that speed the whole time.   So with most requests like this the problem is there are hundreds of sequences out there that are expecting their wave effects to look like they do today so if we mess with the algorithm there is a good chance we change the look of someone's sequence in a way they don't like.

**Comment by PKingRoch** [comment]
Is there another way to achieve this smoothly?  Perhaps an option that isn't on by default?

**Comment by Clyde-L** [comment]
Perhaps try layering the effects with a short fade in/out transition time.  Also try checking the MORPH check box in the Layer Blending box to smooth it out.

**Comment by AzGilrock** [comment]
Can't really fix it that way because its more to do with how it calculates the position when you use a curve.  It's doesn't try to adjust based on where it was last time around.   Also I think that Morph checkbox and slider should be deleted.  It does nothing you can't do with a Fade transition and is an outdated feature now that we have multiple layers.  I've seen users put that slider in the wrong position and it makes it look like none of the effects are rendering.
