### ISSUE TITLE
xLights 2017.32 linux (openSuse 42.2) applying text effect crashes application

### ISSUE THREAD

**Issue by hdamveld** [smeighan/xLights#950]
xLights version: 2017.32 prod 64bit (a610afdc)
OS: OpenSuse 42.2 (64bit)
Setup: 5 E131 universes, see attached zip file
Layout: icicles and single lines, see attached zip file

Description:
When starting a new animation sequence (File->New Sequence->Animation->20fps->Done) and dragging the text effect to any of the model/groups, xLights shows a debug report window and closes after pressing ok. In the terminal from which xLights was started, the following text appears:

** (xLights:4538): WARNING **: Invalid borders specified for theme pixmap:
        /usr/share/themes/Breeze/gtk-2.0/../assets/line-h.png,
borders don't fit within the image

(xLights:4538): Gtk-CRITICAL **: IA__gtk_window_resize: assertion 'width > 0' failed

None of the other effects that I used have this problem. The crash can also be reproduced by first selecting any other effect, and then selecting 'text' in the pull-down menu in the Effect Settings window.

[xLights_dbgrpt-5035-20171013T202423.zip](https://github.com/smeighan/xLights/files/1384380/xLights_dbgrpt-5035-20171013T202423.zip)

**Comment by cjd** [comment]
You can ignore the WARNING/gtk-critical messages - they are just issues with gtk 2 themes and how wxwidgets uses gtk.  They should not be contributing to this failure.

I gave this a test using latest git compile and the provided appimage binary - neither crashed when following that process.
It looks to be crashing when getting the font specific so may be related to what you have installed on the system for font handling.
Can you please try and reproduce with the appimage binary from https://www.adebenham.com/xlights-linux/ (this will help exclude most system-libraries/compile options)

When did this last work for you on this system?
What has changed since then (system updates, xlights updates etc)

**Comment by hdamveld** [comment]
The appimage binary (2017.32) seems to produce the same error, see attached zipfile:

[xLights_dbgrpt-7734-20171013T214139.zip](https://github.com/smeighan/xLights/files/1384418/xLights_dbgrpt-7734-20171013T214139.zip)

I tried the other appImages as well: only 2017.6 seems to work. 2017.7 is not available. 2017.8 and up all give the same error, so something must have been changed between 2017.6 and 2017.8.

I did the same with my old openSuse rpm files: in 2017.6 the text effect works, in 2017.7 and up it is broken.

Sorry, I cannot recall the last time when I used the text effect, so it's hard to tell what has changed. I'm running a pretty standard openSuse 42.2 distro.

**Comment by hdamveld** [comment]
I compiled wxWidgets and xLights 2017.32 with debug symbols and ran xLights with ddd. It looks like things start to go wrong in the buffer.GetTextDrawingContext()->Clear() function call in TextEffect::Render(), and ultimately a segfault occurs in RenderBuffer.cpp, in the GetContext function in the ContextPool class, see the screenshot below.

![screenshot_20171014_003830](https://user-images.githubusercontent.com/18729233/31573871-e61147ea-b078-11e7-9343-9e57a55bd112.png)

That matches my findings that the bug emerged in 2017.7, because the ContextPool class was added in 2017.7.

**Comment by cjd** [comment]
I can't reproduce the problem on Ubuntu - so I'm setting up a OpenSuse VM to try and reproduce.
I tested with the 2017.32 appimage binary and couldn't get it to crash as you did.
Are you using KDE or Gnome as your desktop (assuming KDE based on screenshot)?
When you built it yourself which packages did you need to add to get it to compile (so I have same setup as you)
Are you able to provide a list of what you have installed so I can try and reproduce your system to test it?

**Comment by cjd** [comment]
How many CPUs does your system have?
If you limit the number of CPUs does it still crash?
IE: taskset -c 1 xLights

**Comment by hdamveld** [comment]
Chris,

Thanks for looking into this, I'll try to get the answers tonight.

Thanks
Herman

**Comment by hdamveld** [comment]
Ok, here are some answers:

1) My computer has 8 CPUs (kabylake i7). I tried 'taskset -c 1 xLights'  but no changes.

2) I'm using a stock OpenSuse 42.2 with KDE deskktop. I've installed the following packages from the OpenSuse repos to build the executable:

gtk2-devel-2.24.31-12.1.x86_64
gstreamer-devel-1.8.3-2.3.1.x86_64
gstreamer-plugins-base-devel-1.8.3-5.3.2.x86_64
freeglut-devel-2.8.1-6.5.x86_64
libSDL-devel-1.2.15-17.5.x86_64
pkg-config-0.28-9.54.x86_64
libnotify-devel-0.7.6-6.5.x86_64
libjpeg8-devel-8.0.2-33.1.x86_64
libtiff-devel-4.0.7-17.3.1.x86_64
libSM-devel-1.2.2-6.3.x86_64
libwebkitgtk-devel-2.4.11-2.10.x86_64
cppunit-devel-1.13.2-4.5.x86_64
update-desktop-files-12.1-30.2.noarch
ffmpeg2-devel-2.8.11-25.5.2.x86_64

I also had to install the following:
log4cpp-devel-1.1.2~rc3-6.1.x86_64
cbp2make-rev147-6.1.x86_64
Because they are not part of the standard OpenSuse repos I built and packaged them myself. You can get them from:
http://download.opensuse.org/repositories/home:/heda/openSUSE_Leap_42.2/

3) I usually package xLights using the open build service. The packages used there should be identical to the ones I use on my local machine, but minor differences might occur. You can grab the xLights rpm there:
http://download.opensuse.org/repositories/home:/heda/openSUSE_Leap_42.2/x86_64/xLights-2017.32-1.1.x86_64.rpm

Hope this helps, I'll try to dig a bit further as well.

**Comment by cjd** [comment]
Hmm - just tried with your rpm and it didn't crash for me :(
I did notice it used the libavcodec libraries instead of the ffmpeg ones - but I wouldn't expect that to impact things in this way.
Is there anything 'special' about your system I may be missing to reproduce this?

**Comment by hdamveld** [comment]
Ok that's good news I guess, at least my rpms aren't fundamentally broken.
My notebook is indeed a little special, it's a Dell Precision 5520 with two graphics cards, and in OpenSuse I am using the integrated one, which has no hardware openGL support, so I'm using software rendering (mesa).
I just tried xLights on my Ubuntu partition on the same laptopo with hardware openGL support, and the text effect works fine there.
I'll keep looking into this, it's a little weird because I don't have issues with other openGL applications. I'm not sure I fully understand the way xLights switches openGL contexts, but I'll try to figure out what happens.

**Comment by cjd** [comment]
In the xlights menus there isnthe option to force the OpenGL level used.
Can you try each of them and see if they make any difference?
Xlights really ' utilises ' gl so it wouldn't surprise me if mesa is
missing a bit of context handling


On 19 Oct. 2017 3:25 pm, "hdamveld" <notifications@github.com> wrote:

Ok that's good news I guess, at least my rpms aren't fundamentally broken.
My notebook is indeed a little special, it's a Dell Precision 5520 with two
graphics cards, and in OpenSuse I am using the integrated one, which has no
hardware openGL support, so I'm using software rendering (mesa).
I just tried xLights on my Ubuntu partition on the same laptopo with
hardware openGL support, and the text effect works fine there.
I'll keep looking into this, it's a little weird because I don't have
issues with other openGL applications. I'm not sure I fully understand the
way xLights switches openGL contexts, but I'll try to figure out what
happens.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/smeighan/xLights/issues/950#issuecomment-337795970>,
or mute
the thread

**Comment by hdamveld** [comment]
I've been digging a little deeper... Changing the OpenGL level to be used does not seem to have any effect, xLights crashed every time the text effect was used.

I'm suspecting there is something fishy going on with the Mesa software openGL drivers, although any other openGL application seems to run fine.

To test if the Mesa software openGL drivers were to blame, I installed openSUSE Leap 42.2 as a virtual machine (which uses Mesa by default) and ran it from Windows, Ubuntu and OpenSUSE, and the text effect was working fine.

For now I can only conclude that the combination of Mesa drivers with the Kaby lake graphics adapter are causing trouble. I'll keep digging...

**Comment by cjd** [comment]
There have been a lot of updates since this issue was occurring.
I'll close off this issue for now - but if you re-test and it is still occurring with current xLights then please re-open it.
