### ISSUE TITLE
Layout - Width Adjust is broken

### ISSUE THREAD

**Issue by bhensley86** [smeighan/xLights#957]
I'm on 2017.33 and when I adjust my height up or down the size of my canvas changes appropriately.  When I change the width to grow it larger, it actually shrinks my canvas width. Doing the reverse of shrinking the canvas size (kind of makes it bigger) but I don't get a black canvas. Something seems wrong here.

**Comment by AzGilrock** [comment]
You really need to put an image on the background so you can see what's happening.  It's probably just trying to maintain an aspect ratio.  Nothing has changed in Layout and I highly doubt anything is "broken".  Just doesn't work how you expect.

**Comment by bhensley86** [comment]
Weird after a restart of the app and trying an image it works correctly. Removing the image it works now too. No idea how to re-create it, but it was shrinking the black background when I was trying to make it larger. Guess you can mark it as a sighting :)

**Comment by AzGilrock** [comment]
Well the window does not scroll so when you try to make it larger we try to fit more pixels into the same area.  Its easier to see when there is an image.  If you give it small number part of the image will be clipped.  You make the numbers bigger and then you see the whole image.  Since the canvas has to fit on the screen because we do not scroll making it larger numbers can make it appear to shrink because its fitting it into an aspect ratio.
